import { PropertyValues, SpectrumElement, TemplateResult } from '@spectrum-web-components/base';
import '@spectrum-web-components/theme/sp-theme.js';
import '@spectrum-web-components/theme/src/themes.js';
import '@spectrum-web-components/theme/src/spectrum-two/themes.js';
import '@spectrum-web-components/theme/src/express/themes.js';
import '@spectrum-web-components/field-label/sp-field-label.js';
import '@spectrum-web-components/picker/sp-picker.js';
import '@spectrum-web-components/menu/sp-menu.js';
import '@spectrum-web-components/menu/sp-menu-item.js';
import '@spectrum-web-components/switch/sp-switch.js';
import { Color, Scale, SystemVariant } from '@spectrum-web-components/theme';
import './types.js';
import { type Locale } from './locales.js';
export declare let dir: 'ltr' | 'rtl';
export declare const theme: SystemVariant;
export declare let system: SystemVariant;
export declare let color: Color;
export declare let scale: Scale;
export declare let reduceMotion: boolean;
export declare const screenshot: boolean;
export declare const locale: string;
export declare const direction: string;
export declare class StoryDecorator extends SpectrumElement {
    static get styles(): import("@spectrum-web-components/base").CSSResult[];
    system: SystemVariant;
    color: Color;
    scale: Scale;
    direction: 'ltr' | 'rtl';
    reduceMotion: boolean;
    lang: Locale;
    screenshot: boolean;
    private themeRoot;
    ready: boolean;
    startManagingContentDirection(el: HTMLElement): Promise<void>;
    stopManagingContentDirection(el: HTMLElement): Promise<void>;
    private updateTheme;
    get backgroundStyle(): "background-color: var(--spectrum-gray-50)" | "background-color: var(--spectrum-gray-100);";
    protected handleKeydown(event: KeyboardEvent): void;
    protected render(): TemplateResult;
    protected checkReady({ target, }: Event & {
        target: HTMLSlotElement;
    }): Promise<void>;
    private get manageTheme();
    private get systemControl();
    private get colorControl();
    private get scaleControl();
    private get localeControl();
    private get dirControl();
    private get reduceMotionControl();
    protected willUpdate(changes: PropertyValues<this>): void;
}
