/**
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */

import { spawnSync } from 'node:child_process';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, relative } from 'node:path';
import postcss from 'postcss';

const LAYER = 'swc-global-elements';
const FENCE_OPEN_RE = /^@global-exclude(?:\s*:.*)?$/;
const FENCE_CLOSE = '@global-exclude-end';

// Attributes in the stable SWC API whose modifier values are prefixed with the
// first hyphen-segment of the attribute name to avoid ambiguous short tokens:
//   size="l"           → sizeL   (bare "l" conveys nothing in a global stylesheet)
//   static-color="white" → staticWhite  ("static" is the semantic distinguisher)
const SWC_PREFIXED_ATTRS = ['size', 'static-color'];

// ── File header ─────────────────────────────────────────────────────────────

/**
 * @param {string} sourcePath - Path relative to project root.
 * @returns {string}
 */
function makeHeader(sourcePath) {
  const year = new Date().getFullYear();
  return (
    '/**\n' +
    ` * Copyright ${year} Adobe. All rights reserved.\n` +
    ' * This file is licensed to you under the Apache License, Version 2.0 (the "License");\n' +
    ' * you may not use this file except in compliance with the License. You may obtain a copy\n' +
    ' * of the License at http://www.apache.org/licenses/LICENSE-2.0\n' +
    ' *\n' +
    ' * Unless required by applicable law or agreed to in writing, software distributed under\n' +
    ' * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS\n' +
    ' * OF ANY KIND, either express or implied. See the License for the specific language\n' +
    ' * governing permissions and limitations under the License.\n' +
    ' */\n\n' +
    '/* DO NOT EDIT — auto-generated by vite-global-elements-css.\n' +
    ` * Source: ${sourcePath}\n` +
    ' * Edit that file and rerun the dev server or build. */\n\n'
  );
}

// ── Block name derivation ───────────────────────────────────────────────────

/**
 * Derives the BEM block class from a component name: 'button' → 'swc-Button',
 * 'action-button' → 'swc-ActionButton'.
 *
 * @param {string} component - Component identifier, e.g. 'button' or 'action-button'.
 * @returns {string}
 */
export function deriveBlock(component) {
  return (
    'swc-' +
    component
      .split('-')
      .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
      .join('')
  );
}

/**
 * Returns the resolved BEM block class for an entry.
 *
 * @param {import('./index.d.ts').GlobalElementEntry} entry - Entry to resolve the block for.
 * @returns {string}
 */
function getBlock(entry) {
  return entry.rootElementSelector ?? deriveBlock(entry.component);
}

// ── Selector transformation ─────────────────────────────────────────────────

/**
 * Splits a comma-separated selector list while respecting parentheses nesting.
 *
 * @param {string} list
 * @returns {string[]}
 */
function splitSelectors(list) {
  const parts = [];
  let depth = 0;
  let current = '';
  for (const ch of list) {
    if (ch === '(') {
      depth++;
    } else if (ch === ')') {
      depth--;
    } else if (ch === ',' && depth === 0) {
      parts.push(current.trim());
      current = '';
      continue;
    }
    current += ch;
  }
  if (current.trim()) {
    parts.push(current.trim());
  }
  return parts;
}

/**
 * Parses attribute selectors from a :host() argument string.
 *
 * @param {string} args - e.g. '[variant="primary"][fill-style="outline"]'
 * @returns {{ name: string; value?: string }[]}
 */
function parseHostAttrs(args) {
  /** @type {{ name: string; value?: string }[]} */
  const attrs = [];
  const re = /\[([^\]=\s]+?)(?:="([^"]*)")?\]/g;
  let m;
  while ((m = re.exec(args)) !== null) {
    attrs.push({ name: m[1], value: m[2] });
  }
  return attrs;
}

/**
 * Builds the BEM modifier string for a single host attribute.
 *
 * Attributes in SWC_PREFIXED_ATTRS get prefixed with the first hyphen-segment
 * of the attribute name followed by a PascalCase value:
 *   size="l"             → 'sizeL'
 *   static-color="white" → 'staticWhite'
 *
 * All other attributes use the raw value (string attrs) or the attribute name
 * itself (boolean attrs).
 *
 * @param {string} attrName
 * @param {string | undefined} value
 * @returns {string}
 */
function buildModifier(attrName, value) {
  if (value === undefined) {
    return attrName;
  }
  if (SWC_PREFIXED_ATTRS.includes(attrName)) {
    const prefix = attrName.split('-')[0];
    return prefix + value.charAt(0).toUpperCase() + value.slice(1);
  }
  return value;
}

/**
 * Transforms `slot[name="X"]::slotted(*)` occurrences to `.block-X`.
 *
 * @param {string} fragment
 * @param {string} block
 * @returns {string}
 */
function transformSlotted(fragment, block) {
  return fragment.replace(
    /slot\[name="([^"]+)"\]::slotted\([^)]*\)/g,
    (_, name) => `.${block}-${name}`
  );
}

/**
 * Transforms a single (no-comma) shadow-DOM selector to its global BEM equivalent.
 *
 * Rules:
 *   *                            → .block, .block * (scoped wildcard)
 *   :host                        → .block
 *   :host([attr="value"])        → .block--value   (value becomes modifier)
 *   :host([boolAttr])            → .block--boolAttr (attr name becomes modifier)
 *   :host([a="x"][b="y"])        → .block--x.block--y (compound, same element)
 *   :host([a="x"]) .block__el   → .block--x .block-el
 *   slot[name="X"]::slotted(*)  → .block__X
 *
 * @param {string} selector
 * @param {string} block
 * @returns {string}
 */
function transformSingle(selector, block) {
  // Wildcard → scoped to the block and all its descendants, preserving the
  // intent of shadow-root-scoped rules (e.g. * { box-sizing: border-box })
  // without leaking into the global scope.
  if (selector.trim() === '*') {
    return `.${block}, .${block} *`;
  }

  const m = selector.match(/^:host(\(([^)]+)\))?\s*([\s\S]*)/);
  if (!m) {
    return transformSlotted(selector, block);
  }

  const [, , rawArgs, rawRest] = m;
  const rest = (rawRest ?? '').trim();

  if (!rawArgs) {
    // Bare :host → .block
    const r = transformSlotted(rest, block);
    return r ? `.${block} ${r}` : `.${block}`;
  }

  // :host([attr="value"][boolAttr]) → modifier classes joined (no space = same element)
  const attrs = parseHostAttrs(rawArgs);
  const hostClass = attrs
    .map(({ name, value }) => `.${block}--${buildModifier(name, value)}`)
    .join('');

  const r = transformSlotted(rest, block);

  // When the rest is exactly the block class, the shadow-DOM inner element is
  // the root element in global context — collapse into the modifier so styles
  // apply directly rather than producing an unreachable descendant combinator.
  if (r === `.${block}`) {
    return hostClass;
  }

  return r ? `${hostClass} ${r}` : hostClass;
}

/**
 * Transforms a full comma-separated selector list from shadow-DOM form to global BEM form.
 *
 * @param {string} list
 * @param {string} block
 * @returns {string}
 */
export function transformSelector(list, block) {
  return splitSelectors(list)
    .map((s) => transformSingle(s, block))
    .join(',\n');
}

// ── PostCSS transformation ──────────────────────────────────────────────────

/**
 * Removes nodes enclosed by @global-exclude / @global-exclude-end comment fences.
 * Works at any nesting depth: fences inside a media query strip only rules within
 * that block. After stripping, at-rules left empty are removed.
 *
 * @param {import('postcss').Container} container - PostCSS container to strip fences from.
 *
 * @returns {boolean} `true` if the operation succeeded (all fences were closed).
 */
function stripExcludedBlocks(container) {
  /** @type {import('postcss').Node[]} */
  const toRemove = [];
  let excluding = false;

  container.each((node) => {
    if (node.type === 'comment') {
      const text = node.text.trim();
      if (FENCE_OPEN_RE.test(text)) {
        excluding = true;
        toRemove.push(node);
        return;
      }
      if (text === FENCE_CLOSE) {
        excluding = false;
        toRemove.push(node);
        return;
      }
    }
    if (excluding) {
      toRemove.push(node);
    } else if (node.type === 'atrule' && node.nodes) {
      // Recurse so fences inside @media, @supports, etc. work within their scope
      if (!stripExcludedBlocks(node)) {
        excluding = true;
      }
    }
  });

  for (const node of toRemove) {
    node.remove();
  }

  // Remove at-rules left empty after fence removal (e.g. @media with only fenced content)
  container.each((node) => {
    if (node.type === 'atrule' && node.nodes && node.nodes.length === 0) {
      node.remove();
    }
  });
  return !excluding;
}

/**
 * Removes all comment nodes from the AST. Called after fence stripping so that
 * fence comments are already gone and only source comments remain.
 *
 * @param {import('postcss').Root} root
 */
function stripComments(root) {
  /** @type {import('postcss').Comment[]} */
  const toRemove = [];
  root.walkComments((c) => toRemove.push(c));
  for (const c of toRemove) {
    c.remove();
  }
}

/**
 * Walks all rules in the AST (including those nested inside @media etc.) and
 * applies BEM selector derivation.
 *
 * @param {import('postcss').Root} root
 * @param {string} block
 */
function applySelectTransform(root, block) {
  root.walkRules((rule) => {
    rule.selector = transformSelector(rule.selector, block);
  });
}

/**
 * Merges rules that share the same selector within the same container, combining
 * all declarations into the first occurrence and deduplicating (last wins per property).
 * Recurses into at-rules so nested rules inside @media are also merged.
 *
 * @param {import('postcss').Container} container
 */
function mergeRules(container) {
  // Recurse into at-rules first so inner rules are merged before outer grouping
  container.each((node) => {
    if (node.type === 'atrule' && node.nodes) {
      mergeRules(node);
    }
  });

  // Group direct-child rules by selector, recording first occurrence
  /** @type {Map<string, import('postcss').Rule>} */
  const selectorFirst = new Map();

  container.each((node) => {
    if (node.type !== 'rule') {
      return;
    }
    const sel = node.selector;
    if (!selectorFirst.has(sel)) {
      selectorFirst.set(sel, node);
      return;
    }
    // Append all declarations from duplicate to the first occurrence
    const first = selectorFirst.get(sel);
    node.each((decl) => {
      if (decl.type === 'decl') {
        first.append(decl.clone());
      }
    });
    node.remove();
  });

  // Deduplicate within merged rules — last declaration wins per property
  for (const rule of selectorFirst.values()) {
    /** @type {Map<string, import('postcss').Declaration>} */
    const lastSeen = new Map();
    /** @type {import('postcss').Declaration[]} */
    const toRemove = [];
    rule.each((decl) => {
      if (decl.type !== 'decl') {
        return;
      }
      if (lastSeen.has(decl.prop)) {
        toRemove.push(lastSeen.get(decl.prop));
      }
      lastSeen.set(decl.prop, decl);
    });
    for (const dup of toRemove) {
      dup.remove();
    }
  }
}

/**
 * Moves all remaining nodes into `@layer swc-global-elements { }` and appends
 * the all:revert-layer rule after the layer.
 *
 * @param {import('postcss').Root} root
 * @param {string} block
 */
function wrapInLayer(root, block) {
  /** @type {import('postcss').ChildNode[]} */
  const children = [];
  root.each((node) => children.push(node));
  for (const node of children) {
    node.remove();
  }

  const layer = postcss.atRule({
    name: 'layer',
    params: LAYER,
    raws: { afterName: ' ', between: ' ', after: '\n' },
  });
  for (const node of children) {
    layer.append(node);
  }
  root.append(layer);

  // Escape-hatch rule outside the layer. Allows page styles on .block to
  // revert any property to the layer-defined value rather than being
  // overridden by unlayered application CSS.
  const revert = postcss.rule({ selector: `.${block}` });
  revert.append(
    postcss.decl({ prop: 'all', value: 'revert-layer !important' })
  );
  root.append(revert);
}

/**
 * Derives a global-elements stylesheet from one or more component shadow-DOM CSS sources.
 *
 * Pipeline:
 *   1. stripExcludedBlocks  — remove fenced blocks (fence comments are consumed here)
 *   2. stripComments        — remove all remaining comments
 *   3. applySelectTransform — :host/::slotted → BEM classes; * → .block, .block *
 *   4. mergeRules           — combine duplicate selectors, deduplicate declarations
 *   5. wrapInLayer          — wrap in @layer and add revert-layer escape hatch
 *
 * @param {string} sourceCss - Concatenated raw CSS (base + component, token() calls intact).
 * @param {string} block - BEM block class name, e.g. 'swc-Button'.
 * @returns {string}
 */
export function deriveCSS(sourceCss, block) {
  const root = postcss.parse(sourceCss);
  if (!stripExcludedBlocks(root)) {
    throw new Error(
      '[vite-global-elements-css] Unclosed @global-exclude fence — missing @global-exclude-end'
    );
  }
  stripComments(root);
  applySelectTransform(root, block);
  mergeRules(root);
  wrapInLayer(root, block);
  return root.toResult({ map: false }).css;
}

// ── Path helpers ────────────────────────────────────────────────────────────

/**
 * @param {import('./index.d.ts').GlobalElementEntry} entry
 * @returns {string}
 */
function getSourceName(entry) {
  return entry.source ?? entry.component;
}

/**
 * @param {import('./index.d.ts').GlobalElementEntry} entry
 * @param {string} projectRoot
 * @returns {string}
 */
function getSourcePath(entry, projectRoot) {
  const name = getSourceName(entry);
  return join(projectRoot, 'components', name, `${name}.css`);
}

/**
 * Returns the path to `{name}-base.css` if it exists alongside `{name}.css`, else null.
 *
 * @param {import('./index.d.ts').GlobalElementEntry} entry
 * @param {string} projectRoot
 * @returns {string | null}
 */
function getBasePath(entry, projectRoot) {
  const name = getSourceName(entry);
  const p = join(projectRoot, 'components', name, `${name}-base.css`);
  return existsSync(p) ? p : null;
}

/**
 * @param {import('./index.d.ts').GlobalElementEntry} entry
 * @param {string} projectRoot
 * @returns {string}
 */
function getOutputPath(entry, projectRoot) {
  return join(
    projectRoot,
    'stylesheets',
    'global',
    `global-${entry.component}.css`
  );
}

// ── Post-processing ──────────────────────────────────────────────────────────

/**
 * Walks up from startDir through node_modules/.bin to find a binary.
 *
 * @param {string} name
 * @param {string} startDir
 * @returns {string | null}
 */
function findBin(name, startDir) {
  let dir = startDir;
  for (let i = 0; i < 6; i++) {
    const p = join(dir, 'node_modules', '.bin', name);
    if (existsSync(p)) {
      return p;
    }
    const parent = join(dir, '..');
    if (parent === dir) {
      break;
    }
    dir = parent;
  }
  return null;
}

/**
 * Runs stylelint --fix on the generated file if stylelint is available in the
 * workspace. Silently skips if the binary cannot be found or the command fails.
 *
 * @param {string} filePath - Absolute path to the generated CSS file.
 * @param {string} projectRoot - Vite project root (used to find the binary).
 */
function runStylelintFix(filePath, projectRoot) {
  const bin = findBin('stylelint', projectRoot);
  if (!bin) {
    return;
  }
  try {
    spawnSync(bin, ['--fix', filePath], {
      stdio: 'pipe',
      cwd: projectRoot,
    });
  } catch {
    // Best-effort — ignore failures
  }
}

// ── Generation ──────────────────────────────────────────────────────────────

/**
 * Reads source(s), derives global CSS, and writes to the output path.
 *
 * @param {import('./index.d.ts').GlobalElementEntry} entry
 * @param {string} projectRoot
 */
function generateEntry(entry, projectRoot) {
  const src = getSourcePath(entry, projectRoot);

  if (!existsSync(src)) {
    console.warn(`[vite-global-elements-css] Source not found: ${src}`);
    return;
  }

  const base = getBasePath(entry, projectRoot);
  const combined = [
    base ? readFileSync(base, 'utf-8') : '',
    readFileSync(src, 'utf-8'),
  ]
    .filter(Boolean)
    .join('\n\n');

  const block = getBlock(entry);
  const derived = deriveCSS(combined, block);
  const out = getOutputPath(entry, projectRoot);
  const sourcePath = relative(projectRoot, src);

  mkdirSync(dirname(out), { recursive: true });
  writeFileSync(out, makeHeader(sourcePath) + derived, 'utf-8');
  runStylelintFix(out, projectRoot);
}

// ── Vite plugin ─────────────────────────────────────────────────────────────

/**
 * Vite plugin that derives `global-{component}.css` from a component's shadow-DOM
 * stylesheet, transforming selectors to BEM class equivalents and stripping
 * component-only blocks marked with @global-exclude fences.
 *
 * Runs in `configResolved` (covers both dev and build) so derived files are
 * written before `processStylesheets` runs in `closeBundle`. In dev mode,
 * `configureServer` watches source files and re-derives on save.
 *
 * @param {import('./index.d.ts').GlobalElementCSSOptions} options
 * @returns {import('vite').Plugin}
 */
export function globalElementCSS(options) {
  let projectRoot = '';

  return {
    name: 'vite-global-elements-css',

    configResolved(config) {
      projectRoot = config.root;
      for (const entry of options.elements) {
        generateEntry(entry, projectRoot);
      }
    },

    configureServer(server) {
      for (const entry of options.elements) {
        const src = getSourcePath(entry, projectRoot);
        const base = getBasePath(entry, projectRoot);
        const toWatch = [src, base].filter(Boolean);

        for (const file of toWatch) {
          server.watcher.add(file);
        }

        server.watcher.on('change', (changed) => {
          if (!toWatch.includes(changed)) {
            return;
          }
          generateEntry(entry, projectRoot);
          // Global CSS lives in <link> tags, not the JS module graph — full reload required.
          server.ws.send({ type: 'full-reload' });
        });
      }
    },
  };
}
