/*
Copyright 2025 Adobe. All rights reserved.
This file is licensed to you under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License. You may obtain a copy
of the License at http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software distributed under
the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
OF ANY KIND, either express or implied. See the License for the specific language
governing permissions and limitations under the License.
*/
/*
 * Generated by @fastly/compute-js-static-publish.
 */

// Commented items are defaults, feel free to modify and experiment!
// See README for a detailed explanation of the configuration options.

/** @type {import('@fastly/compute-js-static-publish').PublishContentConfig} */
const config = {
    rootDir: '../projects/documentation/_site',
    // excludeDirs: [ './node_modules' ],
    // excludeDotFiles: true,
    // includeWellKnown: true,
    // kvStoreAssetInclusionTest: (assetKey) => true,
    // contentCompression: [ 'br', 'gzip' ],
    // contentTypes: [
    //   { test: /.custom$/, contentType: 'application/x-custom', text: false },
    // ],

    // Server settings are saved to the KV Store per collection
    server: {
        publicDirPrefix: '',
        staticItems: [],
        allowedEncodings: ['br', 'gzip'],
        spaFile: false,
        notFoundPageFile: '/404.html',
        autoExt: [],
        autoIndex: ['index.html', 'index.htm'],
    },
};

export default config;
