/**
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */

/**
 * Icon and preset cell data plus the per-cell timing derivation for the pixel
 * loader animation.
 */

/**
 * Grid position as `[col, row]`, with `row` 0 at the visual top (row index
 * increases downward, matching the grid's row placement).
 */
export type CellPosition = readonly [col: number, row: number];

export type StaggerMode = 'individual' | 'grouped' | 'by-row';

export interface BuildCellsOptions {
  /** Frame step between consecutively staggered cells. */
  staggerInterval?: number;
  stagger?: StaggerMode;
  /** Shifts every cell's row to center icons that don't use all 7 rows. */
  rowOffset?: number;
}

export interface Cell {
  col: number;
  row: number;

  /**
   * Marks a cell for the high-DPI subpixel-seam nudge. Only ever `true` on the
   * hand-authored `aiLogo`.
   */
  outer: boolean;

  /**
   * Frame at which this cell starts dropping in. All downstream timing (exit,
   * fade, loop length) is derived from this by `animation.ts`; see
   * `exitStartOf`/`loopFramesFor`.
   */
  stagger: number;
}

// The loop length and duration are derived per icon from its stagger spread;
// see `loopFramesFor`/`durationForCells` in animation.ts.

function computeStaggerValues(
  positions: readonly CellPosition[],
  mode: StaggerMode,
  interval: number
): number[] {
  if (mode === 'individual') {
    return positions.map((_, index) => index * interval);
  }

  // Sort rows bottom-to-top (highest row index, the visual bottom, first) so
  // the icon assembles from the bottom up and the earliest exit starts at the
  // bottom, matching the hand-authored `aiLogo`. Ascending order would build
  // and clear top-down, reversing the intended motion.
  const rows = Array.from(new Set(positions.map(([, row]) => row))).sort(
    (a, b) => b - a
  );

  if (mode === 'by-row') {
    return positions.map(([, row]) => rows.indexOf(row) * interval);
  }

  // grouped (default): rows processed bottom-to-top; cells within a row
  // stagger by `interval`; consecutive rows overlap by one stagger step so
  // the reveal reads as a continuous wave rather than strictly row-by-row.
  const staggerValues = new Array<number>(positions.length).fill(0);
  let rowStart = 0;

  rows.forEach((row) => {
    const indexesInRow = positions.reduce<number[]>((acc, position, index) => {
      if (position[1] === row) {
        acc.push(index);
      }
      return acc;
    }, []);

    indexesInRow.forEach((index, order) => {
      staggerValues[index] = rowStart + order * interval;
    });

    rowStart += (indexesInRow.length - 1) * interval;
  });

  return staggerValues;
}

/** Derives per-cell stagger timing from a list of grid positions. */
export function buildCells(
  positions: readonly CellPosition[],
  options: BuildCellsOptions = {}
): Cell[] {
  const { staggerInterval = 2, stagger = 'grouped', rowOffset = 0 } = options;
  const staggerValues = computeStaggerValues(
    positions,
    stagger,
    staggerInterval
  );

  return positions.map(([col, row], index) => ({
    col,
    row: row + rowOffset,
    outer: false,
    stagger: staggerValues[index],
  }));
}

/**
 * Hand-authored 12-cell diamond logo mark. Not generated by `buildCells`; it
 * uses irregular stagger steps.
 */
const aiLogo: Cell[] = [
  { col: 3, row: 6, outer: true, stagger: 0 },
  { col: 1, row: 5, outer: true, stagger: 2 },
  { col: 5, row: 5, outer: true, stagger: 4 },
  { col: 2, row: 4, outer: false, stagger: 6 },
  { col: 4, row: 4, outer: false, stagger: 8 },
  { col: 0, row: 3, outer: true, stagger: 10 },
  { col: 6, row: 3, outer: true, stagger: 14 },
  { col: 2, row: 2, outer: false, stagger: 16 },
  { col: 4, row: 2, outer: false, stagger: 18 },
  { col: 1, row: 1, outer: true, stagger: 20 },
  { col: 5, row: 1, outer: true, stagger: 22 },
  { col: 3, row: 0, outer: true, stagger: 24 },
];

const brush = buildCells(
  [
    [0, 6],
    [1, 6],
    [2, 6],
    [1, 5],
    [3, 5],
    [2, 4],
    [3, 4],
    [3, 3],
    [4, 3],
    [4, 2],
    [5, 2],
    [5, 1],
    [6, 1],
    [6, 0],
  ],
  { staggerInterval: 2, stagger: 'grouped' }
);

const eye = buildCells(
  [
    [2, 4],
    [3, 4],
    [4, 4],
    [1, 3],
    [3, 3],
    [5, 3],
    [0, 2],
    [2, 2],
    [3, 2],
    [4, 2],
    [6, 2],
    [1, 1],
    [2, 1],
    [3, 1],
    [5, 1],
    [2, 0],
    [3, 0],
    [4, 0],
  ],
  { staggerInterval: 2, stagger: 'grouped', rowOffset: 1 }
);

const hourglass = buildCells(
  [
    [0, 6],
    [1, 6],
    [2, 6],
    [3, 6],
    [4, 6],
    [5, 6],
    [6, 6],
    [1, 5],
    [2, 5],
    [3, 5],
    [4, 5],
    [5, 5],
    [1, 4],
    [2, 4],
    [4, 4],
    [5, 4],
    [2, 3],
    [3, 3],
    [4, 3],
    [1, 2],
    [2, 2],
    [3, 2],
    [4, 2],
    [5, 2],
    [1, 1],
    [5, 1],
    [0, 0],
    [1, 0],
    [2, 0],
    [3, 0],
    [4, 0],
    [5, 0],
    [6, 0],
  ],
  { staggerInterval: 1, stagger: 'grouped' }
);

const mag = buildCells(
  [
    [6, 6],
    [5, 5],
    [1, 4],
    [2, 4],
    [3, 4],
    [0, 3],
    [4, 3],
    [0, 2],
    [4, 2],
    [0, 1],
    [4, 1],
    [1, 0],
    [2, 0],
    [3, 0],
  ],
  { staggerInterval: 2, stagger: 'grouped' }
);

const crop = buildCells(
  [
    [5, 6],
    [1, 5],
    [2, 5],
    [3, 5],
    [4, 5],
    [5, 5],
    [6, 5],
    [1, 4],
    [1, 3],
    [5, 3],
    [1, 2],
    [5, 2],
    [0, 1],
    [1, 1],
    [3, 1],
    [4, 1],
    [5, 1],
    [1, 0],
  ],
  { staggerInterval: 2, stagger: 'grouped' }
);

const flower = buildCells(
  [
    [3, 6],
    [3, 5],
    [2, 4],
    [4, 4],
    [2, 3],
    [5, 3],
    [1, 2],
    [4, 2],
    [6, 2],
    [0, 1],
    [2, 1],
    [5, 1],
    [1, 0],
  ],
  { staggerInterval: 2, stagger: 'grouped' }
);

const image = buildCells(
  [
    [0, 6],
    [1, 6],
    [2, 6],
    [3, 6],
    [4, 6],
    [5, 6],
    [6, 6],
    [0, 5],
    [1, 5],
    [2, 5],
    [3, 5],
    [4, 5],
    [5, 5],
    [6, 5],
    [0, 4],
    [1, 4],
    [2, 4],
    [3, 4],
    [5, 4],
    [6, 4],
    [0, 3],
    [2, 3],
    [6, 3],
    [0, 2],
    [4, 2],
    [6, 2],
    [0, 1],
    [6, 1],
    [0, 0],
    [1, 0],
    [2, 0],
    [3, 0],
    [4, 0],
    [5, 0],
    [6, 0],
  ],
  { staggerInterval: 1, stagger: 'grouped' }
);

const lasso = buildCells(
  [
    [1, 6],
    [2, 5],
    [1, 4],
    [2, 4],
    [0, 3],
    [3, 3],
    [4, 3],
    [5, 3],
    [0, 2],
    [6, 2],
    [1, 1],
    [6, 1],
    [2, 0],
    [3, 0],
    [4, 0],
    [5, 0],
  ],
  { staggerInterval: 2, stagger: 'grouped' }
);

const page = buildCells(
  [
    [0, 6],
    [1, 6],
    [2, 6],
    [3, 6],
    [4, 6],
    [5, 6],
    [6, 6],
    [0, 5],
    [6, 5],
    [0, 4],
    [6, 4],
    [0, 3],
    [3, 3],
    [4, 3],
    [5, 3],
    [6, 3],
    [0, 2],
    [3, 2],
    [6, 2],
    [0, 1],
    [3, 1],
    [5, 1],
    [0, 0],
    [1, 0],
    [2, 0],
    [3, 0],
    [4, 0],
  ],
  { staggerInterval: 1, stagger: 'grouped' }
);

const wand = buildCells(
  [
    [6, 6],
    [5, 5],
    [0, 4],
    [4, 4],
    [2, 3],
    [1, 2],
    [3, 2],
    [2, 1],
    [0, 0],
    [4, 0],
  ],
  { staggerInterval: 2, stagger: 'grouped' }
);

const bargraph = buildCells(
  [
    [0, 6],
    [2, 6],
    [4, 6],
    [6, 6],
    [2, 5],
    [4, 5],
    [6, 5],
    [0, 4],
    [2, 4],
    [4, 4],
    [6, 4],
    [1, 3],
    [6, 3],
    [2, 2],
    [4, 2],
    [6, 2],
    [3, 1],
    [5, 1],
    [6, 0],
  ],
  { staggerInterval: 2, stagger: 'grouped' }
);

const trefoil = buildCells(
  [
    [0, 6],
    [1, 6],
    [1, 5],
    [2, 4],
    [3, 4],
    [5, 4],
    [6, 4],
    [2, 3],
    [4, 3],
    [3, 2],
    [3, 1],
    [3, 0],
  ],
  { staggerInterval: 2, stagger: 'grouped' }
);

const dial = buildCells(
  [
    [0, 4],
    [6, 4],
    [0, 3],
    [3, 3],
    [6, 3],
    [0, 2],
    [4, 2],
    [6, 2],
    [1, 1],
    [5, 1],
    [2, 0],
    [3, 0],
  ],
  { staggerInterval: 2, stagger: 'grouped', rowOffset: 1 }
);

const folder = buildCells(
  [
    [0, 5],
    [1, 5],
    [2, 5],
    [3, 5],
    [4, 5],
    [5, 5],
    [6, 5],
    [0, 4],
    [6, 4],
    [0, 3],
    [6, 3],
    [0, 2],
    [6, 2],
    [0, 1],
    [3, 1],
    [4, 1],
    [5, 1],
    [6, 1],
    [1, 0],
    [2, 0],
  ],
  { staggerInterval: 1, stagger: 'grouped', rowOffset: 1 }
);

const arrow = buildCells(
  [
    [0, 4],
    [1, 3],
    [3, 3],
    [2, 2],
    [4, 2],
    [6, 2],
    [5, 1],
    [6, 1],
    [4, 0],
    [5, 0],
    [6, 0],
  ],
  { staggerInterval: 2, stagger: 'grouped', rowOffset: 2 }
);

const cloud = buildCells(
  [
    [0, 4],
    [1, 4],
    [2, 4],
    [3, 4],
    [4, 4],
    [5, 4],
    [6, 4],
    [0, 3],
    [6, 3],
    [1, 2],
    [5, 2],
    [1, 1],
    [2, 1],
    [5, 1],
    [3, 0],
    [4, 0],
  ],
  { staggerInterval: 1, stagger: 'grouped', rowOffset: 1 }
);

const comment = buildCells(
  [
    [1, 6],
    [1, 5],
    [2, 5],
    [1, 4],
    [3, 4],
    [4, 4],
    [5, 4],
    [0, 3],
    [6, 3],
    [0, 2],
    [6, 2],
    [0, 1],
    [6, 1],
    [1, 0],
    [2, 0],
    [3, 0],
    [4, 0],
    [5, 0],
  ],
  { staggerInterval: 1, stagger: 'grouped' }
);

const filter = buildCells(
  [
    [2, 6],
    [3, 6],
    [2, 5],
    [4, 5],
    [2, 4],
    [4, 4],
    [2, 3],
    [4, 3],
    [1, 2],
    [5, 2],
    [0, 1],
    [6, 1],
    [0, 0],
    [1, 0],
    [2, 0],
    [3, 0],
    [4, 0],
    [5, 0],
    [6, 0],
  ],
  { staggerInterval: 1, stagger: 'grouped' }
);

const microphone = buildCells(
  [
    [1, 6],
    [2, 6],
    [3, 6],
    [4, 6],
    [2, 5],
    [3, 5],
    [1, 4],
    [4, 4],
    [0, 3],
    [1, 3],
    [4, 3],
    [5, 3],
    [1, 2],
    [4, 2],
    [1, 1],
    [4, 1],
    [2, 0],
    [3, 0],
  ],
  { staggerInterval: 1, stagger: 'grouped' }
);

const pencil = buildCells(
  [
    [0, 6],
    [1, 6],
    [2, 6],
    [0, 5],
    [1, 5],
    [3, 5],
    [0, 4],
    [4, 4],
    [1, 3],
    [5, 3],
    [2, 2],
    [4, 2],
    [6, 2],
    [3, 1],
    [6, 1],
    [4, 0],
    [5, 0],
  ],
  { staggerInterval: 2, stagger: 'grouped' }
);

const potion = buildCells(
  [
    [1, 6],
    [2, 6],
    [3, 6],
    [4, 6],
    [5, 6],
    [0, 5],
    [6, 5],
    [0, 4],
    [2, 4],
    [6, 4],
    [1, 3],
    [3, 3],
    [5, 3],
    [2, 2],
    [4, 2],
    [2, 1],
    [4, 1],
    [1, 0],
    [2, 0],
    [3, 0],
    [4, 0],
    [5, 0],
  ],
  { staggerInterval: 1, stagger: 'grouped' }
);

const slider = buildCells(
  [
    [4, 5],
    [0, 4],
    [1, 4],
    [2, 4],
    [3, 4],
    [5, 4],
    [6, 4],
    [4, 3],
    [2, 2],
    [0, 1],
    [1, 1],
    [3, 1],
    [4, 1],
    [5, 1],
    [6, 1],
    [2, 0],
  ],
  { staggerInterval: 1, stagger: 'grouped', rowOffset: 1 }
);

const timeline = buildCells(
  [
    [3, 6],
    [0, 5],
    [1, 5],
    [3, 5],
    [4, 5],
    [5, 5],
    [6, 5],
    [0, 4],
    [1, 4],
    [3, 4],
    [4, 4],
    [5, 4],
    [6, 4],
    [3, 3],
    [2, 2],
    [4, 2],
    [1, 1],
    [5, 1],
    [1, 0],
    [2, 0],
    [3, 0],
    [4, 0],
    [5, 0],
  ],
  { staggerInterval: 1, stagger: 'grouped' }
);

const eyedrop = buildCells(
  [
    [0, 6],
    [1, 6],
    [0, 5],
    [2, 5],
    [1, 4],
    [3, 4],
    [2, 3],
    [4, 3],
    [6, 3],
    [3, 2],
    [4, 2],
    [5, 2],
    [4, 1],
    [5, 1],
    [6, 1],
    [3, 0],
    [5, 0],
    [6, 0],
  ],
  { staggerInterval: 1, stagger: 'grouped' }
);

const adobeA = buildCells(
  [
    [0, 6],
    [1, 6],
    [2, 6],
    [3, 6],
    [5, 6],
    [6, 6],
    [1, 5],
    [2, 5],
    [5, 5],
    [1, 4],
    [2, 4],
    [4, 4],
    [5, 4],
    [1, 3],
    [2, 3],
    [4, 3],
    [5, 3],
    [2, 2],
    [3, 2],
    [4, 2],
    [2, 1],
    [3, 1],
    [4, 1],
  ],
  { staggerInterval: 2, stagger: 'grouped' }
);

const adobeD = buildCells(
  [
    [2, 6],
    [3, 6],
    [4, 6],
    [5, 6],
    [1, 5],
    [2, 5],
    [4, 5],
    [5, 5],
    [1, 4],
    [2, 4],
    [4, 4],
    [5, 4],
    [1, 3],
    [2, 3],
    [4, 3],
    [5, 3],
    [2, 2],
    [3, 2],
    [4, 2],
    [5, 2],
    [4, 1],
    [5, 1],
  ],
  { staggerInterval: 2, stagger: 'grouped' }
);

const adobeO = buildCells(
  [
    [2, 6],
    [3, 6],
    [4, 6],
    [1, 5],
    [2, 5],
    [4, 5],
    [5, 5],
    [1, 4],
    [2, 4],
    [4, 4],
    [5, 4],
    [1, 3],
    [2, 3],
    [4, 3],
    [5, 3],
    [2, 2],
    [3, 2],
    [4, 2],
  ],
  { staggerInterval: 2, stagger: 'grouped', rowOffset: -1 }
);

const adobeB = buildCells(
  [
    [1, 6],
    [2, 6],
    [3, 6],
    [4, 6],
    [1, 5],
    [2, 5],
    [4, 5],
    [5, 5],
    [1, 4],
    [2, 4],
    [4, 4],
    [5, 4],
    [1, 3],
    [2, 3],
    [4, 3],
    [5, 3],
    [1, 2],
    [2, 2],
    [3, 2],
    [4, 2],
    [1, 1],
    [2, 1],
  ],
  { staggerInterval: 2, stagger: 'grouped' }
);

const adobeE = buildCells(
  [
    [2, 6],
    [3, 6],
    [4, 6],
    [1, 5],
    [2, 5],
    [1, 4],
    [2, 4],
    [3, 4],
    [4, 4],
    [5, 4],
    [1, 3],
    [2, 3],
    [4, 3],
    [5, 3],
    [2, 2],
    [3, 2],
    [4, 2],
  ],
  { staggerInterval: 2, stagger: 'grouped', rowOffset: -1 }
);

export const PIXEL_LOADER_ICON_NAMES = [
  'aiLogo',
  'brush',
  'eye',
  'hourglass',
  'mag',
  'crop',
  'flower',
  'image',
  'lasso',
  'page',
  'wand',
  'bargraph',
  'trefoil',
  'dial',
  'folder',
  'arrow',
  'cloud',
  'comment',
  'filter',
  'microphone',
  'pencil',
  'potion',
  'slider',
  'timeline',
  'eyedrop',
  'adobeA',
  'adobeD',
  'adobeO',
  'adobeB',
  'adobeE',
] as const;

export type PixelLoaderIconName = (typeof PIXEL_LOADER_ICON_NAMES)[number];

export const ICONS: Record<PixelLoaderIconName, Cell[]> = {
  aiLogo,
  brush,
  eye,
  hourglass,
  mag,
  crop,
  flower,
  image,
  lasso,
  page,
  wand,
  bargraph,
  trefoil,
  dial,
  folder,
  arrow,
  cloud,
  comment,
  filter,
  microphone,
  pencil,
  potion,
  slider,
  timeline,
  eyedrop,
  adobeA,
  adobeD,
  adobeO,
  adobeB,
  adobeE,
};

export const PIXEL_LOADER_PRESET_NAMES = [
  'cc',
  'dc',
  'exp',
  'analyze',
  'mega',
] as const;

export type PixelLoaderPresetName = (typeof PIXEL_LOADER_PRESET_NAMES)[number];

export const PRESETS: Record<PixelLoaderPresetName, PixelLoaderIconName[]> = {
  cc: [
    'aiLogo',
    'brush',
    'wand',
    'crop',
    'eye',
    'hourglass',
    'adobeA',
    'adobeD',
    'adobeO',
    'adobeB',
    'adobeE',
    'eyedrop',
  ],
  dc: [
    'aiLogo',
    'page',
    'trefoil',
    'image',
    'cloud',
    'mag',
    'adobeA',
    'adobeD',
    'adobeO',
    'adobeB',
    'adobeE',
    'pencil',
  ],
  exp: [
    'aiLogo',
    'bargraph',
    'dial',
    'filter',
    'slider',
    'folder',
    'adobeA',
    'adobeD',
    'adobeO',
    'adobeB',
    'adobeE',
    'arrow',
  ],
  analyze: [
    'flower',
    'image',
    'brush',
    'eye',
    'eyedrop',
    'wand',
    'lasso',
    'crop',
  ],
  mega: [
    'aiLogo',
    'brush',
    'wand',
    'crop',
    'eye',
    'hourglass',
    'page',
    'trefoil',
    'image',
    'eyedrop',
    'mag',
    'bargraph',
    'dial',
    'folder',
    'flower',
    'lasso',
    'adobeA',
    'adobeD',
    'adobeO',
    'adobeB',
    'adobeE',
    'arrow',
    'cloud',
    'comment',
    'filter',
    'microphone',
    'pencil',
    'potion',
    'slider',
    'timeline',
  ],
};
