/**
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */

/**
 * Icon/preset cell data and timing derivation for the pixel loader animation.
 * Ported from the design spec (sections 1-9, 15); see that document for the
 * full behavioral spec this file implements.
 */

/**
 * Grid position as `[col, row]`, `row` 0 at the visual top. The design
 * spec's section 3 prose says "row 0 at the visual bottom", but its own
 * `cy = 120 + row * CELL` formula (SVG y increases downward) implies the
 * opposite; this follows the formula.
 */
export type CellPosition = readonly [col: number, row: number];

export type StaggerMode = 'individual' | 'grouped' | 'by-row';

export interface BuildCellsOptions {
  /** Frame step between consecutively staggered cells. */
  staggerInterval?: number;
  stagger?: StaggerMode;
  /** Shifts every cell's row to center icons that don't use all 7 rows. */
  rowOffset?: number;
}

export interface Cell {
  col: number;
  row: number;

  /**
   * Marks a cell for the high-DPI subpixel-seam nudge (see the design spec,
   * section 12). Only ever `true` on the hand-authored `aiLogo`.
   */
  outer: boolean;
  /** Frame at which this cell starts dropping in. */
  stagger: number;
  /** Frame at which this cell starts dropping out. */
  exitStart: number;
  fadeIn: readonly [number, number];
  fadeOut: readonly [number, number];
}

export const TOTAL_FRAMES = 72;
export const FPS = 30;
export const DURATION_MS = (TOTAL_FRAMES / FPS) * 1000;

function computeStaggerValues(
  positions: readonly CellPosition[],
  mode: StaggerMode,
  interval: number
): number[] {
  if (mode === 'individual') {
    return positions.map((_, index) => index * interval);
  }

  const rows = Array.from(new Set(positions.map(([, row]) => row))).sort(
    (a, b) => a - b
  );

  if (mode === 'by-row') {
    return positions.map(([, row]) => rows.indexOf(row) * interval);
  }

  // grouped (default): rows processed bottom-to-top; cells within a row
  // stagger by `interval`; consecutive rows overlap by one stagger step so
  // the reveal reads as a continuous wave rather than strictly row-by-row.
  const staggerValues = new Array<number>(positions.length).fill(0);
  let rowStart = 0;

  rows.forEach((row) => {
    const indexesInRow = positions.reduce<number[]>((acc, position, index) => {
      if (position[1] === row) {
        acc.push(index);
      }
      return acc;
    }, []);

    indexesInRow.forEach((index, order) => {
      staggerValues[index] = rowStart + order * interval;
    });

    rowStart += (indexesInRow.length - 1) * interval;
  });

  return staggerValues;
}

/**
 * Derives per-cell stagger/exitStart/fadeIn/fadeOut timing from a list of
 * grid positions, per the design spec, section 8.
 */
export function buildCells(
  positions: readonly CellPosition[],
  options: BuildCellsOptions = {}
): Cell[] {
  const { staggerInterval = 2, stagger = 'grouped', rowOffset = 0 } = options;
  const staggerValues = computeStaggerValues(
    positions,
    stagger,
    staggerInterval
  );
  const maxStagger = Math.max(1, ...staggerValues);

  return positions.map(([col, row], index) => {
    const cellStagger = staggerValues[index];
    const exitStart = 47 + (cellStagger / maxStagger) * 12;

    return {
      col,
      row: row + rowOffset,
      outer: false,
      stagger: cellStagger,
      exitStart,
      fadeIn: [cellStagger + 1, cellStagger + 4],
      fadeOut: [exitStart, exitStart + 12],
    };
  });
}

/**
 * Hand-authored 12-cell diamond (per the design spec, section 9). Not
 * generated by `buildCells` — irregular stagger steps and custom fade
 * ranges, carried over verbatim.
 */
const aiLogo: Cell[] = [
  {
    col: 3,
    row: 6,
    outer: true,
    stagger: 0,
    exitStart: 47,
    fadeIn: [1, 4],
    fadeOut: [47, 59],
  },
  {
    col: 1,
    row: 5,
    outer: true,
    stagger: 2,
    exitStart: 48,
    fadeIn: [4, 7],
    fadeOut: [48, 60],
  },
  {
    col: 5,
    row: 5,
    outer: true,
    stagger: 4,
    exitStart: 49,
    fadeIn: [6, 9],
    fadeOut: [49, 61],
  },
  {
    col: 2,
    row: 4,
    outer: false,
    stagger: 6,
    exitStart: 50,
    fadeIn: [9, 12],
    fadeOut: [50, 62],
  },
  {
    col: 4,
    row: 4,
    outer: false,
    stagger: 8,
    exitStart: 51,
    fadeIn: [13, 16],
    fadeOut: [51, 63],
  },
  {
    col: 0,
    row: 3,
    outer: true,
    stagger: 10,
    exitStart: 52,
    fadeIn: [14, 17],
    fadeOut: [52, 64],
  },
  {
    col: 6,
    row: 3,
    outer: true,
    stagger: 14,
    exitStart: 54,
    fadeIn: [18, 21],
    fadeOut: [54, 66],
  },
  {
    col: 2,
    row: 2,
    outer: false,
    stagger: 16,
    exitStart: 55,
    fadeIn: [21, 24],
    fadeOut: [55, 67],
  },
  {
    col: 4,
    row: 2,
    outer: false,
    stagger: 18,
    exitStart: 56,
    fadeIn: [23, 26],
    fadeOut: [56, 68],
  },
  {
    col: 1,
    row: 1,
    outer: true,
    stagger: 20,
    exitStart: 57,
    fadeIn: [26, 29],
    fadeOut: [57, 69],
  },
  {
    col: 5,
    row: 1,
    outer: true,
    stagger: 22,
    exitStart: 58,
    fadeIn: [27, 30],
    fadeOut: [58, 70],
  },
  {
    col: 3,
    row: 0,
    outer: true,
    stagger: 24,
    exitStart: 59,
    fadeIn: [31, 34],
    fadeOut: [59, 71],
  },
];

const brush = buildCells(
  [
    [0, 6],
    [1, 6],
    [2, 6],
    [1, 5],
    [3, 5],
    [2, 4],
    [3, 4],
    [3, 3],
    [4, 3],
    [4, 2],
    [5, 2],
    [5, 1],
    [6, 1],
    [6, 0],
  ],
  { staggerInterval: 2, stagger: 'grouped' }
);

const eye = buildCells(
  [
    [2, 4],
    [3, 4],
    [4, 4],
    [1, 3],
    [3, 3],
    [5, 3],
    [0, 2],
    [2, 2],
    [3, 2],
    [4, 2],
    [6, 2],
    [1, 1],
    [2, 1],
    [3, 1],
    [5, 1],
    [2, 0],
    [3, 0],
    [4, 0],
  ],
  { staggerInterval: 2, stagger: 'grouped', rowOffset: 1 }
);

const hourglass = buildCells(
  [
    [0, 6],
    [1, 6],
    [2, 6],
    [3, 6],
    [4, 6],
    [5, 6],
    [6, 6],
    [1, 5],
    [2, 5],
    [3, 5],
    [4, 5],
    [5, 5],
    [1, 4],
    [2, 4],
    [4, 4],
    [5, 4],
    [2, 3],
    [3, 3],
    [4, 3],
    [1, 2],
    [2, 2],
    [3, 2],
    [4, 2],
    [5, 2],
    [1, 1],
    [5, 1],
    [0, 0],
    [1, 0],
    [2, 0],
    [3, 0],
    [4, 0],
    [5, 0],
    [6, 0],
  ],
  { staggerInterval: 1, stagger: 'grouped' }
);

const mag = buildCells(
  [
    [6, 6],
    [5, 5],
    [1, 4],
    [2, 4],
    [3, 4],
    [0, 3],
    [4, 3],
    [0, 2],
    [4, 2],
    [0, 1],
    [4, 1],
    [1, 0],
    [2, 0],
    [3, 0],
  ],
  { staggerInterval: 2, stagger: 'grouped' }
);

const crop = buildCells(
  [
    [5, 6],
    [1, 5],
    [2, 5],
    [3, 5],
    [4, 5],
    [5, 5],
    [6, 5],
    [1, 4],
    [1, 3],
    [5, 3],
    [1, 2],
    [5, 2],
    [0, 1],
    [1, 1],
    [3, 1],
    [4, 1],
    [5, 1],
    [1, 0],
  ],
  { staggerInterval: 2, stagger: 'grouped' }
);

const flower = buildCells(
  [
    [3, 6],
    [3, 5],
    [2, 4],
    [4, 4],
    [2, 3],
    [5, 3],
    [1, 2],
    [4, 2],
    [6, 2],
    [0, 1],
    [2, 1],
    [5, 1],
    [1, 0],
  ],
  { staggerInterval: 2, stagger: 'grouped' }
);

const image = buildCells(
  [
    [0, 6],
    [1, 6],
    [2, 6],
    [3, 6],
    [4, 6],
    [5, 6],
    [6, 6],
    [0, 5],
    [1, 5],
    [2, 5],
    [3, 5],
    [4, 5],
    [5, 5],
    [6, 5],
    [0, 4],
    [1, 4],
    [2, 4],
    [3, 4],
    [5, 4],
    [6, 4],
    [0, 3],
    [2, 3],
    [6, 3],
    [0, 2],
    [4, 2],
    [6, 2],
    [0, 1],
    [6, 1],
    [0, 0],
    [1, 0],
    [2, 0],
    [3, 0],
    [4, 0],
    [5, 0],
    [6, 0],
  ],
  { staggerInterval: 1, stagger: 'grouped' }
);

const lasso = buildCells(
  [
    [1, 6],
    [2, 5],
    [1, 4],
    [2, 4],
    [0, 3],
    [3, 3],
    [4, 3],
    [5, 3],
    [0, 2],
    [6, 2],
    [1, 1],
    [6, 1],
    [2, 0],
    [3, 0],
    [4, 0],
    [5, 0],
  ],
  { staggerInterval: 2, stagger: 'grouped' }
);

const page = buildCells(
  [
    [0, 6],
    [1, 6],
    [2, 6],
    [3, 6],
    [4, 6],
    [5, 6],
    [6, 6],
    [0, 5],
    [6, 5],
    [0, 4],
    [6, 4],
    [0, 3],
    [3, 3],
    [4, 3],
    [5, 3],
    [6, 3],
    [0, 2],
    [3, 2],
    [6, 2],
    [0, 1],
    [3, 1],
    [5, 1],
    [0, 0],
    [1, 0],
    [2, 0],
    [3, 0],
    [4, 0],
  ],
  { staggerInterval: 1, stagger: 'grouped' }
);

const wand = buildCells(
  [
    [6, 6],
    [5, 5],
    [0, 4],
    [4, 4],
    [2, 3],
    [1, 2],
    [3, 2],
    [2, 1],
    [0, 0],
    [4, 0],
  ],
  { staggerInterval: 2, stagger: 'grouped' }
);

const bargraph = buildCells(
  [
    [0, 6],
    [2, 6],
    [4, 6],
    [6, 6],
    [2, 5],
    [4, 5],
    [6, 5],
    [0, 4],
    [2, 4],
    [4, 4],
    [6, 4],
    [1, 3],
    [6, 3],
    [2, 2],
    [4, 2],
    [6, 2],
    [3, 1],
    [5, 1],
    [6, 0],
  ],
  { staggerInterval: 2, stagger: 'grouped' }
);

const trefoil = buildCells(
  [
    [0, 6],
    [1, 6],
    [1, 5],
    [2, 4],
    [3, 4],
    [5, 4],
    [6, 4],
    [2, 3],
    [4, 3],
    [3, 2],
    [3, 1],
    [3, 0],
  ],
  { staggerInterval: 2, stagger: 'grouped' }
);

const dial = buildCells(
  [
    [0, 4],
    [6, 4],
    [0, 3],
    [3, 3],
    [6, 3],
    [0, 2],
    [4, 2],
    [6, 2],
    [1, 1],
    [5, 1],
    [2, 0],
    [3, 0],
  ],
  { staggerInterval: 2, stagger: 'grouped', rowOffset: 1 }
);

const folder = buildCells(
  [
    [0, 5],
    [1, 5],
    [2, 5],
    [3, 5],
    [4, 5],
    [5, 5],
    [6, 5],
    [0, 4],
    [6, 4],
    [0, 3],
    [6, 3],
    [0, 2],
    [6, 2],
    [0, 1],
    [3, 1],
    [4, 1],
    [5, 1],
    [6, 1],
    [1, 0],
    [2, 0],
  ],
  { staggerInterval: 1, stagger: 'grouped', rowOffset: 1 }
);

const arrow = buildCells(
  [
    [0, 4],
    [1, 3],
    [3, 3],
    [2, 2],
    [4, 2],
    [6, 2],
    [5, 1],
    [6, 1],
    [4, 0],
    [5, 0],
    [6, 0],
  ],
  { staggerInterval: 2, stagger: 'grouped', rowOffset: 2 }
);

const cloud = buildCells(
  [
    [0, 4],
    [1, 4],
    [2, 4],
    [3, 4],
    [4, 4],
    [5, 4],
    [6, 4],
    [0, 3],
    [6, 3],
    [1, 2],
    [5, 2],
    [1, 1],
    [2, 1],
    [5, 1],
    [3, 0],
    [4, 0],
  ],
  { staggerInterval: 1, stagger: 'grouped', rowOffset: 1 }
);

const comment = buildCells(
  [
    [1, 6],
    [1, 5],
    [2, 5],
    [1, 4],
    [3, 4],
    [4, 4],
    [5, 4],
    [0, 3],
    [6, 3],
    [0, 2],
    [6, 2],
    [0, 1],
    [6, 1],
    [1, 0],
    [2, 0],
    [3, 0],
    [4, 0],
    [5, 0],
  ],
  { staggerInterval: 1, stagger: 'grouped' }
);

const filter = buildCells(
  [
    [2, 6],
    [3, 6],
    [2, 5],
    [4, 5],
    [2, 4],
    [4, 4],
    [2, 3],
    [4, 3],
    [1, 2],
    [5, 2],
    [0, 1],
    [6, 1],
    [0, 0],
    [1, 0],
    [2, 0],
    [3, 0],
    [4, 0],
    [5, 0],
    [6, 0],
  ],
  { staggerInterval: 1, stagger: 'grouped' }
);

const microphone = buildCells(
  [
    [1, 6],
    [2, 6],
    [3, 6],
    [4, 6],
    [2, 5],
    [3, 5],
    [1, 4],
    [4, 4],
    [0, 3],
    [1, 3],
    [4, 3],
    [5, 3],
    [1, 2],
    [4, 2],
    [1, 1],
    [4, 1],
    [2, 0],
    [3, 0],
  ],
  { staggerInterval: 1, stagger: 'grouped' }
);

const pencil = buildCells(
  [
    [0, 6],
    [1, 6],
    [2, 6],
    [0, 5],
    [1, 5],
    [3, 5],
    [0, 4],
    [4, 4],
    [1, 3],
    [5, 3],
    [2, 2],
    [4, 2],
    [6, 2],
    [3, 1],
    [6, 1],
    [4, 0],
    [5, 0],
  ],
  { staggerInterval: 2, stagger: 'grouped' }
);

const potion = buildCells(
  [
    [1, 6],
    [2, 6],
    [3, 6],
    [4, 6],
    [5, 6],
    [0, 5],
    [6, 5],
    [0, 4],
    [2, 4],
    [6, 4],
    [1, 3],
    [3, 3],
    [5, 3],
    [2, 2],
    [4, 2],
    [2, 1],
    [4, 1],
    [1, 0],
    [2, 0],
    [3, 0],
    [4, 0],
    [5, 0],
  ],
  { staggerInterval: 1, stagger: 'grouped' }
);

const slider = buildCells(
  [
    [4, 5],
    [0, 4],
    [1, 4],
    [2, 4],
    [3, 4],
    [5, 4],
    [6, 4],
    [4, 3],
    [2, 2],
    [0, 1],
    [1, 1],
    [3, 1],
    [4, 1],
    [5, 1],
    [6, 1],
    [2, 0],
  ],
  { staggerInterval: 1, stagger: 'grouped', rowOffset: 1 }
);

const timeline = buildCells(
  [
    [3, 6],
    [0, 5],
    [1, 5],
    [3, 5],
    [4, 5],
    [5, 5],
    [6, 5],
    [0, 4],
    [1, 4],
    [3, 4],
    [4, 4],
    [5, 4],
    [6, 4],
    [3, 3],
    [2, 2],
    [4, 2],
    [1, 1],
    [5, 1],
    [1, 0],
    [2, 0],
    [3, 0],
    [4, 0],
    [5, 0],
  ],
  { staggerInterval: 1, stagger: 'grouped' }
);

const eyedrop = buildCells(
  [
    [0, 6],
    [1, 6],
    [0, 5],
    [2, 5],
    [1, 4],
    [3, 4],
    [2, 3],
    [4, 3],
    [6, 3],
    [3, 2],
    [4, 2],
    [5, 2],
    [4, 1],
    [5, 1],
    [6, 1],
    [3, 0],
    [5, 0],
    [6, 0],
  ],
  { staggerInterval: 1, stagger: 'grouped' }
);

const adobeA = buildCells(
  [
    [0, 6],
    [1, 6],
    [2, 6],
    [3, 6],
    [5, 6],
    [6, 6],
    [1, 5],
    [2, 5],
    [5, 5],
    [1, 4],
    [2, 4],
    [4, 4],
    [5, 4],
    [1, 3],
    [2, 3],
    [4, 3],
    [5, 3],
    [2, 2],
    [3, 2],
    [4, 2],
    [2, 1],
    [3, 1],
    [4, 1],
  ],
  { staggerInterval: 2, stagger: 'grouped' }
);

const adobeD = buildCells(
  [
    [2, 6],
    [3, 6],
    [4, 6],
    [5, 6],
    [1, 5],
    [2, 5],
    [4, 5],
    [5, 5],
    [1, 4],
    [2, 4],
    [4, 4],
    [5, 4],
    [1, 3],
    [2, 3],
    [4, 3],
    [5, 3],
    [2, 2],
    [3, 2],
    [4, 2],
    [5, 2],
    [4, 1],
    [5, 1],
  ],
  { staggerInterval: 2, stagger: 'grouped' }
);

const adobeO = buildCells(
  [
    [2, 6],
    [3, 6],
    [4, 6],
    [1, 5],
    [2, 5],
    [4, 5],
    [5, 5],
    [1, 4],
    [2, 4],
    [4, 4],
    [5, 4],
    [1, 3],
    [2, 3],
    [4, 3],
    [5, 3],
    [2, 2],
    [3, 2],
    [4, 2],
  ],
  { staggerInterval: 2, stagger: 'grouped', rowOffset: -1 }
);

const adobeB = buildCells(
  [
    [1, 6],
    [2, 6],
    [3, 6],
    [4, 6],
    [1, 5],
    [2, 5],
    [4, 5],
    [5, 5],
    [1, 4],
    [2, 4],
    [4, 4],
    [5, 4],
    [1, 3],
    [2, 3],
    [4, 3],
    [5, 3],
    [1, 2],
    [2, 2],
    [3, 2],
    [4, 2],
    [1, 1],
    [2, 1],
  ],
  { staggerInterval: 2, stagger: 'grouped' }
);

const adobeE = buildCells(
  [
    [2, 6],
    [3, 6],
    [4, 6],
    [1, 5],
    [2, 5],
    [1, 4],
    [2, 4],
    [3, 4],
    [4, 4],
    [5, 4],
    [1, 3],
    [2, 3],
    [4, 3],
    [5, 3],
    [2, 2],
    [3, 2],
    [4, 2],
  ],
  { staggerInterval: 2, stagger: 'grouped', rowOffset: -1 }
);

export const PIXEL_LOADER_ICON_NAMES = [
  'aiLogo',
  'brush',
  'eye',
  'hourglass',
  'mag',
  'crop',
  'flower',
  'image',
  'lasso',
  'page',
  'wand',
  'bargraph',
  'trefoil',
  'dial',
  'folder',
  'arrow',
  'cloud',
  'comment',
  'filter',
  'microphone',
  'pencil',
  'potion',
  'slider',
  'timeline',
  'eyedrop',
  'adobeA',
  'adobeD',
  'adobeO',
  'adobeB',
  'adobeE',
] as const;

export type PixelLoaderIconName = (typeof PIXEL_LOADER_ICON_NAMES)[number];

export const ICONS: Record<PixelLoaderIconName, Cell[]> = {
  aiLogo,
  brush,
  eye,
  hourglass,
  mag,
  crop,
  flower,
  image,
  lasso,
  page,
  wand,
  bargraph,
  trefoil,
  dial,
  folder,
  arrow,
  cloud,
  comment,
  filter,
  microphone,
  pencil,
  potion,
  slider,
  timeline,
  eyedrop,
  adobeA,
  adobeD,
  adobeO,
  adobeB,
  adobeE,
};

export const PIXEL_LOADER_PRESET_NAMES = [
  'cc',
  'dc',
  'exp',
  'analyze',
  'mega',
] as const;

export type PixelLoaderPresetName = (typeof PIXEL_LOADER_PRESET_NAMES)[number];

export const PRESETS: Record<PixelLoaderPresetName, PixelLoaderIconName[]> = {
  cc: [
    'aiLogo',
    'brush',
    'wand',
    'crop',
    'eye',
    'hourglass',
    'adobeA',
    'adobeD',
    'adobeO',
    'adobeB',
    'adobeE',
    'eyedrop',
  ],
  dc: [
    'aiLogo',
    'page',
    'trefoil',
    'image',
    'cloud',
    'mag',
    'adobeA',
    'adobeD',
    'adobeO',
    'adobeB',
    'adobeE',
    'pencil',
  ],
  exp: [
    'aiLogo',
    'bargraph',
    'dial',
    'filter',
    'slider',
    'folder',
    'adobeA',
    'adobeD',
    'adobeO',
    'adobeB',
    'adobeE',
    'arrow',
  ],
  analyze: [
    'flower',
    'image',
    'brush',
    'eye',
    'eyedrop',
    'wand',
    'lasso',
    'crop',
  ],
  mega: [
    'aiLogo',
    'brush',
    'wand',
    'crop',
    'eye',
    'hourglass',
    'page',
    'trefoil',
    'image',
    'eyedrop',
    'mag',
    'bargraph',
    'dial',
    'folder',
    'flower',
    'lasso',
    'adobeA',
    'adobeD',
    'adobeO',
    'adobeB',
    'adobeE',
    'arrow',
    'cloud',
    'comment',
    'filter',
    'microphone',
    'pencil',
    'potion',
    'slider',
    'timeline',
  ],
};
