printWidth: 80
tabWidth: 4
semi: true
singleQuote: true
trailingComma: es5
bracketSpacing: true
arrowParens: always
htmlWhitespaceSensitivity: ignore

overrides:
    - files: '*.css'
      options:
          printWidth: 500
          singleQuote: false
