printWidth: 80
tabWidth: 4
semi: true
singleQuote: true
trailingComma: es5
bracketSpacing: true
arrowParens: always
htmlWhitespaceSensitivity: ignore
overrides:
    - files:
          - 'packages/*/src/*.css'
          - 'tools/*/src/*.css'
          - 'tools/styles/*.css'
          - 'tools/styles/*/*.css'
      options:
          printWidth: 500
