cacheFolder: ~/.cache/yarn

# @todo: Remove enableScripts once pre/post install commands are migrated to the new Yarn 4 recommended pattern.
enableScripts: true

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.18.1.cjs
