yarnPath: .yarn/releases/yarn-3.2.1.cjs

changesetBaseRefs:
    - main
    - origin/main
    - upstream/main

changesetIgnorePatterns:
    - '**/*.test.{js,ts}'

nodeLinker: node-modules

npmPublishRegistry: https://registry.npmjs.org/

npmScopes:
    adobe:
        npmPublishRegistry: https://registry.npmjs.org/

# plugins:
#     - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
#       spec: '@yarnpkg/plugin-interactive-tools'
#     - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
#       spec: '@yarnpkg/plugin-typescript'
#     - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
#       spec: '@yarnpkg/plugin-workspace-tools'

pnpEnableEsmLoader: true

pnpFallbackMode: dependencies-only

preferInteractive: true
