cacheFolder: ~/.cache/yarn
nodeLinker: node-modules
yarnPath: .yarn/releases/yarn-4.10.3.cjs
# @todo: Remove enableScripts once pre/post install commands are migrated to the new Yarn 4 recommended pattern.
enableScripts: true
