/**
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */

/**
 * Shared helpers for the `.ai/` tooling: one frontmatter parser, one file inventory, and
 * one glob engine, so `sync.js` and the validators read files exactly the same way.
 */

import { execFileSync } from 'child_process';
import { existsSync, readdirSync, readFileSync } from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { parse as parseYaml } from 'yaml';

export const ROOT = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  '../..'
);
export const AI_DIR = path.join(ROOT, '.ai');
export const RULES_DIR = path.join(AI_DIR, 'rules');
export const MEMORY_DIR = path.join(AI_DIR, 'memory');
export const SKILLS_DIR = path.join(AI_DIR, 'skills');

/** Marker that identifies a file written by `sync.js`. */
export const GENERATED_MARKER = '<!-- GENERATED by .ai/scripts/sync.js';

/** Instruction frontmatter: the canonical schema for `.ai/rules/*.md` and `.ai/memory/*.md`. */
export const INSTRUCTION_KEYS = new Set([
  'description',
  'paths',
  'excludeAgent',
]);
export const REJECTED_INSTRUCTION_KEYS = {
  globs: 'use `paths` (a quoted YAML list)',
  alwaysApply: 'always-on guidance belongs in AGENTS.md',
  applyTo: 'use `paths`; `applyTo` is generated',
  name: 'the file name is the identifier',
};
export const EXCLUDE_AGENT_VALUES = new Set(['code-review', 'cloud-agent']);

/** Skill frontmatter keys documented by the Agent Skills spec or Copilot. */
export const SKILL_KEYS = new Set([
  'name',
  'description',
  'license',
  'metadata',
  'compatibility',
  'argument-hint',
  'user-invocable',
  'disable-model-invocation',
  'allowed-tools',
]);
export const REJECTED_SKILL_KEYS = {
  globs: 'move file triggers into a pointer rule in .ai/rules/',
  alwaysApply: 'skills are on demand; use a rule or AGENTS.md',
  paths: 'move file triggers into a pointer rule in .ai/rules/',
  applyTo: 'move file triggers into a pointer rule in .ai/rules/',
};

export const rel = (file) =>
  path.relative(ROOT, file).split(path.sep).join('/');

/**
 * Split a Markdown file into its YAML frontmatter text and body.
 * Returns `{ frontmatter: null, body }` when the file has no frontmatter.
 */
export function splitFrontmatter(source) {
  const match = source.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n?/);
  if (!match) {
    return { frontmatter: null, body: source };
  }
  return { frontmatter: match[1], body: source.slice(match[0].length) };
}

/**
 * Read a Markdown file and parse its frontmatter.
 * Returns `{ file, rel, source, data, body, error }`; `data` is `null` without frontmatter.
 */
export function readMarkdown(file) {
  const source = readFileSync(file, 'utf8');
  const { frontmatter, body } = splitFrontmatter(source);
  let data = null;
  let error = null;
  if (frontmatter !== null) {
    try {
      data = parseYaml(frontmatter, { uniqueKeys: true }) ?? {};
      if (typeof data !== 'object' || Array.isArray(data)) {
        error = 'frontmatter must be a YAML mapping';
        data = null;
      }
    } catch (e) {
      error = `invalid YAML frontmatter: ${e.message.split('\n')[0]}`;
    }
  }
  return { file, rel: rel(file), source, data, body, error };
}

const markdownFilesIn = (dir) =>
  existsSync(dir)
    ? readdirSync(dir)
        .filter((f) => f.endsWith('.md'))
        .sort()
        .map((f) => path.join(dir, f))
    : [];

/**
 * Every instruction source. `kind` is `rule` or `memory`; `target` is the generated file stem.
 * Memory files without frontmatter are returned with `data: null` and are not generated.
 */
export function listInstructionSources() {
  const rules = markdownFilesIn(RULES_DIR).map((file) => ({
    kind: 'rule',
    name: path.basename(file, '.md'),
    target: path.basename(file, '.md'),
    ...readMarkdown(file),
  }));
  const memory = markdownFilesIn(MEMORY_DIR).map((file) => ({
    kind: 'memory',
    name: path.basename(file, '.md'),
    target: `memory-${path.basename(file, '.md')}`,
    ...readMarkdown(file),
  }));
  return [...rules, ...memory];
}

/**
 * Every `SKILL.md` under `.ai/skills/`, at any depth.
 * `dir` is the path relative to `.ai/skills/`; `depth` is the number of path segments.
 */
export function listSkills() {
  const found = [];
  const walk = (dir) => {
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      const full = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        walk(full);
      } else if (entry.name === 'SKILL.md') {
        const dirRel = path.relative(SKILLS_DIR, dir).split(path.sep).join('/');
        found.push({
          dir: dirRel,
          dirName: path.basename(dir),
          depth: dirRel.split('/').length,
          ...readMarkdown(full),
        });
      }
    }
  };
  if (existsSync(SKILLS_DIR)) {
    walk(SKILLS_DIR);
  }
  return found.sort((a, b) => a.dir.localeCompare(b.dir));
}

let trackedCache = null;

/** Every file tracked by git, as repository-relative POSIX paths. */
export function trackedFiles() {
  if (!trackedCache) {
    trackedCache = execFileSync('git', ['ls-files', '-z'], {
      cwd: ROOT,
      encoding: 'utf8',
      maxBuffer: 256 * 1024 * 1024,
    })
      .split('\0')
      .filter(Boolean);
  }
  return trackedCache;
}

if (typeof path.matchesGlob !== 'function') {
  console.error(
    `yarn lint:ai and yarn ai:sync need Node 22.5 or later (found ${process.version}). Run \`nvm use\` to switch to the version in .nvmrc.`
  );
  process.exit(1);
}

/**
 * Glob match with the semantics GitHub documents for `applyTo`: `*` stays within one
 * directory and `**` crosses directories.
 */
export const matchesGlob = (file, pattern) => path.matchesGlob(file, pattern);

/** Fails loudly if the glob engine ever drifts from GitHub's documented `applyTo` examples. */
export function assertGlobSemantics() {
  const cases = [
    ['a.css', '*.css', true],
    ['src/a.css', '*.css', false],
    ['src/a/b.css', '**/*.css', true],
    ['src/a.css', 'src/*.css', true],
    ['src/a/b.css', 'src/*.css', false],
    ['src/a/b/c.css', 'src/**/*.css', true],
  ];
  return cases
    .filter(([file, pattern, want]) => matchesGlob(file, pattern) !== want)
    .map(
      ([file, pattern, want]) =>
        `glob engine mismatch: matchesGlob('${file}', '${pattern}') should be ${want}`
    );
}

/** Decoded length in Unicode code points, which is how Copilot counts `description`. */
export const codePointLength = (value) => [...String(value)].length;
