"use strict";var u=Object.defineProperty;var h=Object.getOwnPropertyDescriptor;var s=(l,n,e,t)=>{for(var i=t>1?void 0:t?h(n,e):n,o=l.length-1,a;o>=0;o--)(a=l[o])&&(i=(t?a(n,e,i):a(i))||i);return t&&i&&u(n,e,i),i};import{ResizeController as p}from"@lit-labs/observers/resize-controller.js";import{html as m,SizedMixin as f,SpectrumElement as v}from"@spectrum-web-components/base";import{property as r,query as b}from"@spectrum-web-components/base/src/decorators.js";import{ifDefined as g}from"@spectrum-web-components/base/src/directives.js";import S from"@spectrum-web-components/tabs/src/tabs.css.js";import{ScaledIndicator as d}from"@spectrum-web-components/tabs/src/Tabs.js";import y from"@spectrum-web-components/tabs/src/tabs-sizes.css.js";const c="transform: translateX(0px) scaleX(0) scaleY(0)";export class TopNav extends f(v){constructor(){super(...arguments);this.label="";this.ignoreURLParts="";this.selectionIndicatorStyle=c;this.shouldAnimate=!1;this.quiet=!1;this.onClick=e=>{const t=e.target;this.shouldAnimate=!0,this.selectTarget(t)};this.onKeydown=e=>{(e.key==="Enter"||e.key===" ")&&this.onClick(e)};this._items=[];this.resizeController=new p(this,{callback:()=>{this.updateSelectionIndicator()}});this.updateSelectionIndicator=async()=>{const e=this.items.find(i=>i.value===this.selected||i.value===window.location.href);if(!e){this.selectionIndicatorStyle=c;return}await Promise.all([e.updateComplete,document.fonts?document.fonts.ready:Promise.resolve()]);const{width:t}=e.getBoundingClientRect();this.selectionIndicatorStyle=d.transformX(e.offsetLeft,t)}}static get styles(){return[y,S,d.baseStyles()]}set selected(e){const t=this.selected;e!==t&&(this.updateCheckedState(e),this._selected=e,this.requestUpdate("selected",t))}get selected(){return this._selected}get items(){return this._items}set items(e){e!==this.items&&(this._items.forEach(t=>{this.resizeController.unobserve(t)}),e.forEach(t=>{this.resizeController.observe(t)}),this._items=e)}manageItems(){this.items=this.slotEl.assignedElements({flatten:!0}).filter(o=>o.localName==="sp-top-nav-item");let{href:e}=window.location;const t=this.ignoreURLParts.split(" ");t.includes("hash")&&(e=e.replace(window.location.hash,"")),t.includes("search")&&(e=e.replace(window.location.search,""));const i=this.items.find(o=>o.value===e);i?this.selectTarget(i):this.selected=""}render(){return m`
      <div @click=${this.onClick} @keydown=${this.onKeydown} id="list">
        <slot @slotchange=${this.onSlotChange}></slot>
        <div
          id="selection-indicator"
          class=${g(this.shouldAnimate?void 0:"first-position")}
          style=${this.selectionIndicatorStyle}
        ></div>
      </div>
    `}firstUpdated(e){super.firstUpdated(e),this.setAttribute("direction","horizontal"),this.setAttribute("role","navigation")}updated(e){super.updated(e),!this.shouldAnimate&&typeof e.get("shouldAnimate")!="undefined"&&(this.shouldAnimate=!0),e.has("label")&&(this.label||typeof e.get("label")!="undefined")&&(this.label.length?this.setAttribute("aria-label",this.label):this.removeAttribute("aria-label"))}selectTarget(e){const{value:t}=e;t&&(this.selected=t)}onSlotChange(){this.manageItems()}updateCheckedState(e){this.items.forEach(t=>{t.selected=!1}),requestAnimationFrame(()=>{if(e&&e.length){const t=this.items.find(i=>i.value===e||i.value===window.location.href);t?t.selected=!0:this.selected=""}this.updateSelectionIndicator()})}connectedCallback(){super.connectedCallback(),window.addEventListener("resize",this.updateSelectionIndicator),"fonts"in document&&document.fonts.addEventListener("loadingdone",this.updateSelectionIndicator)}disconnectedCallback(){window.removeEventListener("resize",this.updateSelectionIndicator),"fonts"in document&&document.fonts.removeEventListener("loadingdone",this.updateSelectionIndicator),super.disconnectedCallback()}}s([r({type:String})],TopNav.prototype,"label",2),s([r({attribute:"ignore-url-parts"})],TopNav.prototype,"ignoreURLParts",2),s([r()],TopNav.prototype,"selectionIndicatorStyle",2),s([r({attribute:!1})],TopNav.prototype,"shouldAnimate",2),s([r({type:Boolean,reflect:!0})],TopNav.prototype,"quiet",2),s([r({reflect:!0})],TopNav.prototype,"selected",1),s([b("slot")],TopNav.prototype,"slotEl",2);
//# sourceMappingURL=TopNav.js.map
