/**
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
/* Generated by `yarn generate:workflow-icons` from icon-source/workflow/. Do not edit by hand. */

/**
 * The Bug workflow icon as a framework-agnostic SVG string. Usable via `innerHTML`,
 * React `dangerouslySetInnerHTML`, Vue `v-html`, or Lit `unsafeSVG`. Color follows
 * `var(--swc-icon-color, currentColor)`.
 */
export function Icon_Bug(): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path fill="var(--swc-icon-color, currentColor)" d="M18.25 10h-1.5a9.1 9.1 0 0 0-.763-3.68 10.4 10.4 0 0 0 1.784-1.375.75.75 0 1 0-1.042-1.078c-.444.43-.936.81-1.463 1.14C14.027 3.178 12.129 2 10 2S5.973 3.177 4.734 5.008a9 9 0 0 1-1.463-1.14.75.75 0 1 0-1.042 1.077c.538.522 1.14.978 1.784 1.375A9.1 9.1 0 0 0 3.25 10h-1.5a.75.75 0 0 0 0 1.5h1.623a8.8 8.8 0 0 0 1.049 2.997c-.955.643-1.751 1.443-2.312 2.362a.748.748 0 1 0 1.28.782c.455-.745 1.11-1.396 1.9-1.921C6.508 17.128 8.17 18 10 18s3.492-.872 4.71-2.28c.79.525 1.445 1.176 1.9 1.92a.748.748 0 1 0 1.28-.78c-.56-.92-1.357-1.72-2.312-2.363a8.8 8.8 0 0 0 1.052-3.021c.04.007.078.024.12.024h1.5a.75.75 0 0 0 0-1.5M10 3.5c1.562 0 2.962.853 3.925 2.198-1.217.516-2.555.802-3.925.802s-2.708-.286-3.925-.802C7.038 4.353 8.438 3.5 10 3.5M6.15 14.404c-.007-.014-.006-.03-.013-.043-.037-.067-.09-.118-.143-.169C5.22 13.06 4.75 11.597 4.75 10a7.7 7.7 0 0 1 .593-2.989 11.5 11.5 0 0 0 3.907.954v8.46c-1.219-.217-2.302-.952-3.1-2.021m4.6 2.022V7.965a11.5 11.5 0 0 0 3.907-.954A7.7 7.7 0 0 1 15.25 10c0 1.598-.47 3.061-1.246 4.195a.7.7 0 0 0-.14.166c-.008.014-.007.029-.014.043-.798 1.07-1.881 1.804-3.1 2.022"/></svg>`;
}
