/**
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
/* Generated by `yarn generate:workflow-icons` from icon-source/workflow/. Do not edit by hand. */

/**
 * The CCLibrary workflow icon as a framework-agnostic SVG string. Usable via `innerHTML`,
 * React `dangerouslySetInnerHTML`, Vue `v-html`, or Lit `unsafeSVG`. Color follows
 * `var(--swc-icon-color, currentColor)`.
 */
export function Icon_CCLibrary(): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path fill="var(--swc-icon-color, currentColor)" d="M2.75 15a.75.75 0 0 1-.75-.75v-10C2 3.01 3.01 2 4.25 2h10a.75.75 0 0 1 0 1.5h-10a.75.75 0 0 0-.75.75v10a.75.75 0 0 1-.75.75"/><path fill="var(--swc-icon-color, currentColor)" d="M15.63 5H7.37A2.373 2.373 0 0 0 5 7.37v8.26A2.373 2.373 0 0 0 7.37 18h8.26A2.373 2.373 0 0 0 18 15.63V7.37A2.373 2.373 0 0 0 15.63 5m.87 10.63c0 .48-.39.87-.87.87H7.37a.87.87 0 0 1-.87-.87V7.37c0-.48.39-.87.87-.87H11v4.134a.4.4 0 0 0 .683.283l1.034-1.034a.4.4 0 0 1 .566 0l1.034 1.034a.4.4 0 0 0 .683-.283V6.5h.63c.48 0 .87.39.87.87z"/></svg>`;
}
