/**
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
/* Generated by `yarn generate:workflow-icons` from icon-source/workflow/. Do not edit by hand. */

/**
 * The Channel workflow icon as a framework-agnostic SVG string. Usable via `innerHTML`,
 * React `dangerouslySetInnerHTML`, Vue `v-html`, or Lit `unsafeSVG`. Color follows
 * `var(--swc-icon-color, currentColor)`.
 */
export function Icon_Channel(): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path fill="var(--swc-icon-color, currentColor)" d="M18.18 8.664a1.496 1.496 0 0 0-1.972.586h-2.534a3.74 3.74 0 0 0-1.196-2.042l1.273-2.206a1.5 1.5 0 1 0-.818-2.755 1.496 1.496 0 0 0-.478 2.002l-1.276 2.21A3.7 3.7 0 0 0 10 6.25a3.7 3.7 0 0 0-1.179.208L7.548 4.252a1.5 1.5 0 1 0-2.795-.669c.041.8.703 1.414 1.494 1.416l1.275 2.209A3.74 3.74 0 0 0 6.326 9.25h-2.53a1.5 1.5 0 1 0-1.977 2.086 1.496 1.496 0 0 0 1.973-.586h2.534c.165.81.6 1.514 1.196 2.042l-1.273 2.206a1.5 1.5 0 1 0 .818 2.755 1.496 1.496 0 0 0 .478-2.002l1.276-2.21c.373.125.765.209 1.179.209a3.7 3.7 0 0 0 1.179-.208l1.273 2.206a1.5 1.5 0 1 0 2.795.669A1.496 1.496 0 0 0 13.754 15l-1.275-2.209a3.74 3.74 0 0 0 1.196-2.042h2.53a1.5 1.5 0 1 0 1.977-2.086m-6.476 2.788A2.24 2.24 0 0 1 10 12.25a2.24 2.24 0 0 1-1.704-.798 2.2 2.2 0 0 1-.408-.702c-.084-.236-.138-.486-.138-.75s.054-.514.138-.75a2.2 2.2 0 0 1 .408-.702A2.24 2.24 0 0 1 10 7.75a2.24 2.24 0 0 1 1.704.798c.176.206.315.442.408.702.084.236.138.486.138.75s-.054.514-.138.75a2.2 2.2 0 0 1-.408.702"/></svg>`;
}
