/**
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
/* Generated by `yarn generate:workflow-icons` from icon-source/workflow/. Do not edit by hand. */

/**
 * The Chat workflow icon as a framework-agnostic SVG string. Usable via `innerHTML`,
 * React `dangerouslySetInnerHTML`, Vue `v-html`, or Lit `unsafeSVG`. Color follows
 * `var(--swc-icon-color, currentColor)`.
 */
export function Icon_Chat(): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path fill="var(--swc-icon-color, currentColor)" d="M16.75 2h-8A2.25 2.25 0 0 0 6.5 4.25v.5a.75.75 0 0 0 1.5 0v-.5c0-.413.337-.75.75-.75h8c.413 0 .75.338.75.75v4.5c0 .413-.337.75-.75.75H16a.75.75 0 0 0-.75.75v1.651L13.5 10.36V9.25A2.25 2.25 0 0 0 11.25 7h-8A2.25 2.25 0 0 0 1 9.25v4.5C1 14.99 2.01 16 3.25 16v2.137a.936.936 0 0 0 .945.941.87.87 0 0 0 .618-.245L8.033 16h3.217a2.25 2.25 0 0 0 2.25-2.25v-1.393l1.64 1.444a.94.94 0 0 0 1.029.203.94.94 0 0 0 .581-.867V11C17.99 11 19 9.99 19 8.75v-4.5A2.25 2.25 0 0 0 16.75 2M12 13.75c0 .413-.337.75-.75.75H7.467L4.75 16.894V15.25A.75.75 0 0 0 4 14.5h-.75a.75.75 0 0 1-.75-.75v-4.5c0-.412.338-.75.75-.75h8c.413 0 .75.338.75.75z"/></svg>`;
}
