/**
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
/* Generated by `yarn generate:workflow-icons` from icon-source/workflow/. Do not edit by hand. */

/**
 * The CloudStatePending workflow icon as a framework-agnostic SVG string. Usable via `innerHTML`,
 * React `dangerouslySetInnerHTML`, Vue `v-html`, or Lit `unsafeSVG`. Color follows
 * `var(--swc-icon-color, currentColor)`.
 */
export function Icon_CloudStatePending(): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path fill="var(--swc-icon-color, currentColor)" d="M16.235 14.646a.64.64 0 0 1-.279-.066l-1.235-.616a.63.63 0 0 1-.346-.56V11.49a.626.626 0 0 1 1.25 0v1.529l.89.443a.626.626 0 0 1-.28 1.185m2.745-.064a.75.75 0 0 1-.747-.827q.01-.105.015-.211c.02-.413.36-.754.784-.714a.75.75 0 0 1 .714.784 5 5 0 0 1-.021.295.75.75 0 0 1-.746.673"/><path fill="var(--swc-icon-color, currentColor)" d="M15 18.158c-2.62 0-4.75-2.13-4.75-4.75a4.74 4.74 0 0 1 2.901-4.376.749.749 0 1 1 .584 1.381 3.25 3.25 0 0 0-1.985 2.995 3.25 3.25 0 0 0 5.707 2.129.75.75 0 0 1 1.133.983A4.75 4.75 0 0 1 15 18.158"/><path fill="var(--swc-icon-color, currentColor)" d="M9 16.998H3.718a3.455 3.455 0 0 1-3.452-3.451 3.45 3.45 0 0 1 2.324-3.25 4 4 0 0 1-.065-.703c0-2.18 1.81-3.952 4.034-3.952q.42 0 .83.087c.638-1.958 2.477-3.347 4.59-3.347a4.826 4.826 0 0 1 4.818 4.35.75.75 0 0 1-.671.822.746.746 0 0 1-.821-.671 3.33 3.33 0 0 0-3.326-3.001c-1.664 0-3.08 1.252-3.297 2.912a.752.752 0 0 1-1.054.586 2.6 2.6 0 0 0-1.07-.238c-1.396 0-2.533 1.1-2.533 2.452q.001.5.206.965a.75.75 0 0 1-.637 1.051 1.95 1.95 0 0 0-1.828 1.937c0 1.076.876 1.951 1.952 1.951H9a.75.75 0 0 1 0 1.5"/><path fill="var(--swc-icon-color, currentColor)" d="M16.117 10.318q-.105 0-.21-.03a3 3 0 0 0-.199-.05c-.4-.09-.676-.49-.59-.893a.73.73 0 0 1 .923-.57q.142.03.287.074a.75.75 0 0 1-.21 1.47m2.205 1.611a.75.75 0 0 1-.625-.333 3 3 0 0 0-.118-.165.75.75 0 0 1 1.19-.914q.093.12.176.247a.75.75 0 0 1-.623 1.166"/></svg>`;
}
