/**
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
/* Generated by `yarn generate:workflow-icons` from icon-source/workflow/. Do not edit by hand. */

/**
 * The Compare workflow icon as a framework-agnostic SVG string. Usable via `innerHTML`,
 * React `dangerouslySetInnerHTML`, Vue `v-html`, or Lit `unsafeSVG`. Color follows
 * `var(--swc-icon-color, currentColor)`.
 */
export function Icon_Compare(): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path fill="var(--swc-icon-color, currentColor)" d="M8.25 18.021h-1c-1.24 0-2.25-1.01-2.25-2.25v-8.5c0-1.24 1.01-2.25 2.25-2.25h8.5c1.24 0 2.25 1.01 2.25 2.25v.979a.75.75 0 0 1-1.5 0v-.979a.75.75 0 0 0-.75-.75h-8.5a.75.75 0 0 0-.75.75v8.5c0 .414.337.75.75.75h1a.75.75 0 0 1 0 1.5"/><path fill="var(--swc-icon-color, currentColor)" d="M2.75 13.771a.75.75 0 0 1-.75-.75v-8.75c0-1.24 1.01-2.25 2.25-2.25H13a.75.75 0 0 1 0 1.5H4.25a.75.75 0 0 0-.75.75v8.75a.75.75 0 0 1-.75.75m16.68 4.599-2.59-2.591a4.16 4.16 0 0 0 .748-2.379c0-2.308-1.879-4.187-4.188-4.187S9.213 11.092 9.213 13.4s1.879 4.188 4.187 4.188c.884 0 1.702-.279 2.379-.749l2.591 2.592a.747.747 0 0 0 1.06 0 .75.75 0 0 0 0-1.06m-8.717-4.97c0-1.481 1.206-2.687 2.687-2.687s2.688 1.206 2.688 2.687-1.206 2.688-2.688 2.688-2.687-1.206-2.687-2.688"/></svg>`;
}
