/**
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
/* Generated by `yarn generate:workflow-icons` from icon-source/workflow/. Do not edit by hand. */

/**
 * The DataRefresh workflow icon as a framework-agnostic SVG string. Usable via `innerHTML`,
 * React `dangerouslySetInnerHTML`, Vue `v-html`, or Lit `unsafeSVG`. Color follows
 * `var(--swc-icon-color, currentColor)`.
 */
export function Icon_DataRefresh(): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path fill="var(--swc-icon-color, currentColor)" d="M18.592 15.186a.75.75 0 0 0-.946.479A3.3 3.3 0 0 1 14.5 17.95c-1.074 0-2.04-.52-2.648-1.342l.16.058a.624.624 0 1 0 .424-1.176l-1.819-.656a.626.626 0 0 0-.805.393l-.63 1.907a.626.626 0 0 0 1.188.39l.091-.275A4.8 4.8 0 0 0 14.5 19.45a4.8 4.8 0 0 0 4.571-3.318.75.75 0 0 0-.48-.946m.727-4.132a.625.625 0 0 0-.789.398l-.064.197a4.83 4.83 0 0 0-3.965-2.1 4.79 4.79 0 0 0-4.583 3.356.75.75 0 0 0 1.43.455 3.3 3.3 0 0 1 3.153-2.31c1.07 0 2.05.528 2.663 1.36l-.274-.1a.624.624 0 1 0-.424 1.176l1.818.657a.63.63 0 0 0 .486-.027.62.62 0 0 0 .32-.366l.628-1.907a.625.625 0 0 0-.399-.79"/><path fill="var(--swc-icon-color, currentColor)" d="M8.18 10.927C5.01 10.662 3.567 9.807 3.5 9.5V6.224C5.03 7.067 7.524 7.5 10 7.5s4.97-.433 6.5-1.276v1.5a.75.75 0 0 0 1.5 0V4.56c0-.041-.017-.076-.023-.115.008-.066.023-.129.023-.196C18 2.116 13.976 1 10 1S2 2.116 2 4.25c0 .067.015.13.023.196C2.017 4.485 2 4.52 2 4.56v9.94c0 1.776 2.928 2.491 4.673 2.759q.058.009.115.009a.75.75 0 0 0 .113-1.492C4.437 15.397 3.545 14.704 3.5 14.5v-3.144c1.484.738 3.659.99 4.555 1.065l.063.003a.75.75 0 0 0 .062-1.497M10 2.5c4.288 0 6.5 1.227 6.5 1.75S14.288 6 10 6 3.5 4.773 3.5 4.25 5.712 2.5 10 2.5"/></svg>`;
}
