/**
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
/* Generated by `yarn generate:workflow-icons` from icon-source/workflow/. Do not edit by hand. */

/**
 * The Download workflow icon as a framework-agnostic SVG string. Usable via `innerHTML`,
 * React `dangerouslySetInnerHTML`, Vue `v-html`, or Lit `unsafeSVG`. Color follows
 * `var(--swc-icon-color, currentColor)`.
 */
export function Icon_Download(): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path fill="var(--swc-icon-color, currentColor)" d="M13.53 9.427a.75.75 0 0 0-1.06 0l-1.717 1.714V2.75a.75.75 0 0 0-1.5 0v8.4L7.53 9.426a.75.75 0 1 0-1.06 1.06l2.998 2.998a.747.747 0 0 0 1.06 0l3.002-2.998a.75.75 0 0 0 0-1.06"/><path fill="var(--swc-icon-color, currentColor)" d="M15.75 18H4.25C3.01 18 2 16.99 2 15.75v-2.021a.75.75 0 0 1 1.5 0v2.021c0 .413.337.75.75.75h11.5c.413 0 .75-.337.75-.75v-2.021a.75.75 0 0 1 1.5 0v2.021c0 1.24-1.01 2.25-2.25 2.25"/></svg>`;
}
