/**
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
/* Generated by `yarn generate:workflow-icons` from icon-source/workflow/. Do not edit by hand. */

/**
 * The Emoji workflow icon as a framework-agnostic SVG string. Usable via `innerHTML`,
 * React `dangerouslySetInnerHTML`, Vue `v-html`, or Lit `unsafeSVG`. Color follows
 * `var(--swc-icon-color, currentColor)`.
 */
export function Icon_Emoji(): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path fill="var(--swc-icon-color, currentColor)" d="M10 14.5c-1.927 0-3.283-1.13-3.34-1.178a.75.75 0 1 1 .97-1.144c.007.006 1.008.822 2.37.822 1.371 0 2.417-.825 2.428-.833a.75.75 0 0 1 1.053.113c.26.32.212.79-.107 1.051-.06.048-1.455 1.169-3.374 1.169"/><circle cx="7.25" cy="8" r="1.25" fill="var(--swc-icon-color, currentColor)"/><circle cx="12.75" cy="8" r="1.25" fill="var(--swc-icon-color, currentColor)"/><path fill="var(--swc-icon-color, currentColor)" d="M10 18.75c-4.825 0-8.75-3.925-8.75-8.75S5.175 1.25 10 1.25s8.75 3.925 8.75 8.75-3.925 8.75-8.75 8.75m0-16c-3.998 0-7.25 3.252-7.25 7.25s3.252 7.25 7.25 7.25 7.25-3.252 7.25-7.25S13.998 2.75 10 2.75"/><path fill="var(--swc-icon-color, currentColor)" d="M9.978 14.5c-1.927 0-3.283-1.13-3.34-1.178a.75.75 0 1 1 .97-1.144c.007.006 1.008.822 2.37.822 1.37 0 2.417-.825 2.427-.833a.75.75 0 0 1 .946 1.164c-.059.048-1.455 1.169-3.373 1.169"/><circle cx="7.25" cy="8.023" r="1.25" fill="var(--swc-icon-color, currentColor)"/><circle cx="12.75" cy="8.023" r="1.25" fill="var(--swc-icon-color, currentColor)"/><path fill="var(--swc-icon-color, currentColor)" d="M10 18.75c-4.825 0-8.75-3.925-8.75-8.75S5.175 1.25 10 1.25s8.75 3.925 8.75 8.75-3.925 8.75-8.75 8.75m0-16c-3.998 0-7.25 3.252-7.25 7.25s3.252 7.25 7.25 7.25 7.25-3.252 7.25-7.25S13.998 2.75 10 2.75"/></svg>`;
}
