/**
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
/* Generated by `yarn generate:workflow-icons` from icon-source/workflow/. Do not edit by hand. */

/**
 * The Files workflow icon as a framework-agnostic SVG string. Usable via `innerHTML`,
 * React `dangerouslySetInnerHTML`, Vue `v-html`, or Lit `unsafeSVG`. Color follows
 * `var(--swc-icon-color, currentColor)`.
 */
export function Icon_Files(): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path fill="var(--swc-icon-color, currentColor)" d="M3.75 14a.75.75 0 0 1-.75-.75v-10C3 2.01 4.01 1 5.25 1h6a.75.75 0 0 1 0 1.5h-6a.75.75 0 0 0-.75.75v10a.75.75 0 0 1-.75.75"/><path fill="var(--swc-icon-color, currentColor)" d="m17.363 8.213-2.687-3.224A2.74 2.74 0 0 0 12.563 4H8.25C7.01 4 6 5.01 6 6.25v9.5C6 16.99 7.01 18 8.25 18h7.5c1.24 0 2.25-1.01 2.25-2.25V9.974c0-.642-.226-1.267-.637-1.761m-1.714.287H14.25a.75.75 0 0 1-.75-.75V5.928l.023.022zm.101 8h-7.5a.75.75 0 0 1-.75-.75v-9.5a.75.75 0 0 1 .75-.75H12v2.25C12 8.99 13.01 10 14.25 10h2.25v5.75a.75.75 0 0 1-.75.75"/></svg>`;
}
