/**
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
/* Generated by `yarn generate:workflow-icons` from icon-source/workflow/. Do not edit by hand. */

/**
 * The Hand workflow icon as a framework-agnostic SVG string. Usable via `innerHTML`,
 * React `dangerouslySetInnerHTML`, Vue `v-html`, or Lit `unsafeSVG`. Color follows
 * `var(--swc-icon-color, currentColor)`.
 */
export function Icon_Hand(): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path fill="var(--swc-icon-color, currentColor)" d="M16.4 5.126a2.1 2.1 0 0 0-1.027.09v-.871a2.127 2.127 0 0 0-2.125-2.125c-.39 0-.703.109-.954.288a2.12 2.12 0 0 0-1.796-1.002A2.12 2.12 0 0 0 8.467 3.04a2.1 2.1 0 0 0-.719-.134 2.127 2.127 0 0 0-2.125 2.125V8.73a2.1 2.1 0 0 0-1.296-.787 2.1 2.1 0 0 0-1.588.352 2.1 2.1 0 0 0-.874 1.371c-.098.56.027 1.123.352 1.589l2.75 3.916c1.842 2.38 3.562 3.323 6.092 3.323h.165c3.224-.03 5.518-2.406 6.133-6.347l.78-4.568A2.13 2.13 0 0 0 16.4 5.126m-.523 6.778c-.501 3.212-2.202 5.067-4.672 5.088-2.125.024-3.462-.683-5.03-2.712l-2.73-3.886a.62.62 0 0 1 .153-.871.626.626 0 0 1 .873.155l1.289 1.83a.75.75 0 0 0 1.045.181.74.74 0 0 0 .306-.546c.007-.004.012-.02.012-.067V5.032a.626.626 0 0 1 1.25 0V8.79a.75.75 0 0 0 1.5 0V3.63a.626.626 0 0 1 1.25 0v5.031a.75.75 0 0 0 1.5 0V4.345a.626.626 0 0 1 1.25 0v2.964l-.284 1.659a.75.75 0 0 0 1.478.252l.36-2.105a.62.62 0 0 1 .721-.51.627.627 0 0 1 .511.721z"/></svg>`;
}
