/**
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
/* Generated by `yarn generate:workflow-icons` from icon-source/workflow/. Do not edit by hand. */

/**
 * The History workflow icon as a framework-agnostic SVG string. Usable via `innerHTML`,
 * React `dangerouslySetInnerHTML`, Vue `v-html`, or Lit `unsafeSVG`. Color follows
 * `var(--swc-icon-color, currentColor)`.
 */
export function Icon_History(): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path fill="var(--swc-icon-color, currentColor)" d="M13.22 12.657a.74.74 0 0 1-.38-.104l-3.22-1.895a.75.75 0 0 1-.37-.646v-5a.75.75 0 0 1 1.5 0v4.571l2.85 1.677a.75.75 0 0 1-.38 1.397"/><path fill="var(--swc-icon-color, currentColor)" d="M10 1.25c-2.79 0-5.39 1.367-7.023 3.566L2.732 3.33a.756.756 0 0 0-.862-.618.75.75 0 0 0-.618.862l.554 3.363a.75.75 0 0 0 .861.618l3.366-.551a.75.75 0 0 0-.242-1.48L4.106 5.8C5.454 3.92 7.648 2.75 10 2.75c3.998 0 7.25 3.252 7.25 7.25s-3.252 7.25-7.25 7.25a7.22 7.22 0 0 1-6.731-4.552.75.75 0 1 0-1.393.558A8.71 8.71 0 0 0 10 18.75c4.825 0 8.75-3.925 8.75-8.75S14.825 1.25 10 1.25"/></svg>`;
}
