/**
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
/* Generated by `yarn generate:workflow-icons` from icon-source/workflow/. Do not edit by hand. */

/**
 * The Images workflow icon as a framework-agnostic SVG string. Usable via `innerHTML`,
 * React `dangerouslySetInnerHTML`, Vue `v-html`, or Lit `unsafeSVG`. Color follows
 * `var(--swc-icon-color, currentColor)`.
 */
export function Icon_Images(): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" data-name="outline / production" viewBox="0 0 20 20"><path fill="var(--swc-icon-color, currentColor)" d="M17.022 6H5.978C4.887 6 4 6.848 4 7.89v7.22C4 16.152 4.887 17 5.978 17h11.044C18.113 17 19 16.152 19 15.11V7.89C19 6.848 18.113 6 17.022 6M5.978 7.5h11.044c.26 0 .478.179.478.39v5.734l-1.333-1.346c-.757-.763-2.076-.762-2.831 0l-1.024 1.036h-.11l-2.69-2.716c-.755-.764-2.075-.762-2.83 0L5.5 11.792V7.89c0-.211.219-.39.478-.39m0 8c-.26 0-.478-.179-.478-.39v-1.185l2.247-2.271a.5.5 0 0 1 .7 0l2.689 2.715c.596.604 1.642.607 2.242 0l1.024-1.035a.5.5 0 0 1 .699 0l2.11 2.132a.6.6 0 0 1-.189.034z"/><path fill="var(--swc-icon-color, currentColor)" d="M1.75 14a.75.75 0 0 1-.75-.75V4.89C1 3.848 1.866 3 2.932 3H14.75a.75.75 0 0 1 0 1.5H2.932c-.239 0-.432.175-.432.39v8.36a.75.75 0 0 1-.75.75"/><circle cx="14.29" cy="9.75" r="1.1" fill="var(--swc-icon-color, currentColor)"/></svg>`;
}
