/**
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
/* Generated by `yarn generate:workflow-icons` from icon-source/workflow/. Do not edit by hand. */

/**
 * The Invite workflow icon as a framework-agnostic SVG string. Usable via `innerHTML`,
 * React `dangerouslySetInnerHTML`, Vue `v-html`, or Lit `unsafeSVG`. Color follows
 * `var(--swc-icon-color, currentColor)`.
 */
export function Icon_Invite(): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path fill="var(--swc-icon-color, currentColor)" d="M15 10.5a4.5 4.5 0 1 0 0 9 4.5 4.5 0 0 0 0-9m2.5 5.125h-1.875V17.5a.625.625 0 1 1-1.25 0v-1.875H12.5a.625.625 0 1 1 0-1.25h1.875V12.5a.625.625 0 1 1 1.25 0v1.875H17.5a.625.625 0 1 1 0 1.25m-7.442-4.203a3.37 3.37 0 0 1-1.86-.525 3.6 3.6 0 0 1-1.25-1.366 4 4 0 0 1-.452-1.9 3.71 3.71 0 0 1 1.697-3.183 3.37 3.37 0 0 1 3.6-.005c.527.342.96.81 1.254 1.359a3.8 3.8 0 0 1 .457 1.85c.01.64-.146 1.3-.452 1.888a3.63 3.63 0 0 1-1.25 1.371 3.24 3.24 0 0 1-1.744.51M10.01 9.92h.01c.347-.005.68-.087.972-.273.305-.197.56-.475.73-.801.191-.368.289-.78.282-1.192a2.3 2.3 0 0 0-.277-1.14 2.2 2.2 0 0 0-.744-.809 1.86 1.86 0 0 0-1.977.003 2.23 2.23 0 0 0-1.01 1.919c-.006.436.09.846.281 1.208.17.325.421.6.729.797.295.188.639.288.992.288z"/><path fill="var(--swc-icon-color, currentColor)" d="M10 1.271c-4.825 0-8.75 3.925-8.75 8.75 0 4.341 3.237 8.066 7.53 8.666q.052.006.104.006a.75.75 0 0 0 .102-1.493 7.2 7.2 0 0 1-3.75-1.732c.784-.682 1.915-1.203 3.23-1.437a.75.75 0 1 0-.263-1.476c-1.59.282-3.007.928-4 1.8a7.22 7.22 0 0 1-1.453-4.333A7.257 7.257 0 0 1 10 2.772c3.603 0 6.69 2.686 7.182 6.249a.75.75 0 0 0 1.486-.205C18.074 4.514 14.348 1.27 10 1.27"/></svg>`;
}
