/**
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
/* Generated by `yarn generate:workflow-icons` from icon-source/workflow/. Do not edit by hand. */

/**
 * The Lighten workflow icon as a framework-agnostic SVG string. Usable via `innerHTML`,
 * React `dangerouslySetInnerHTML`, Vue `v-html`, or Lit `unsafeSVG`. Color follows
 * `var(--swc-icon-color, currentColor)`.
 */
export function Icon_Lighten(): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path fill="var(--swc-icon-color, currentColor)" d="M10 6.35c2.012 0 3.65 1.638 3.65 3.65s-1.638 3.65-3.65 3.65S6.35 12.012 6.35 10 7.988 6.35 10 6.35m0-1.5c-2.84 0-5.15 2.31-5.15 5.15s2.31 5.15 5.15 5.15 5.15-2.31 5.15-5.15S12.84 4.85 10 4.85m0-1.6a.75.75 0 0 1-.75-.75V1.25a.75.75 0 0 1 1.5 0V2.5a.75.75 0 0 1-.75.75m0 16.25a.75.75 0 0 1-.75-.75V17.5a.75.75 0 0 1 1.5 0v1.25a.75.75 0 0 1-.75.75m-7.5-8.75H1.25a.75.75 0 0 1 0-1.5H2.5a.75.75 0 0 1 0 1.5m16.25 0H17.5a.75.75 0 0 1 0-1.5h1.25a.75.75 0 0 1 0 1.5m-3.446-5.304a.75.75 0 0 1-.53-1.28l.883-.884a.75.75 0 1 1 1.06 1.06l-.883.885a.75.75 0 0 1-.53.22M3.813 16.938a.75.75 0 0 1-.53-1.28l.883-.885a.75.75 0 1 1 1.06 1.061l-.883.884a.75.75 0 0 1-.53.22m.883-11.492a.75.75 0 0 1-.53-.22l-.884-.883a.75.75 0 1 1 1.06-1.06l.885.883a.75.75 0 0 1-.53 1.28m11.491 11.492a.75.75 0 0 1-.53-.22l-.885-.884a.75.75 0 1 1 1.061-1.06l.884.883a.75.75 0 0 1-.53 1.28"/></svg>`;
}
