/**
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
/* Generated by `yarn generate:workflow-icons` from icon-source/workflow/. Do not edit by hand. */

/**
 * The ListMultiSelect workflow icon as a framework-agnostic SVG string. Usable via `innerHTML`,
 * React `dangerouslySetInnerHTML`, Vue `v-html`, or Lit `unsafeSVG`. Color follows
 * `var(--swc-icon-color, currentColor)`.
 */
export function Icon_ListMultiSelect(): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path fill="var(--swc-icon-color, currentColor)" d="M4.5 18h-2c-.69 0-1.25-.56-1.25-1.25v-2c0-.69.56-1.25 1.25-1.25h2c.69 0 1.25.56 1.25 1.25v2c0 .69-.56 1.25-1.25 1.25m-1.75-1.5h1.5V15h-1.5zM4.5 15h.01zM5.808 1.602a.75.75 0 0 0-1.045.178l-1.48 2.087-.62-.638a.75.75 0 1 0-1.076 1.045L2.835 5.56c.017.016.039.023.056.037.018.016.029.038.049.052.032.023.068.034.102.051q.036.02.072.036a.8.8 0 0 0 .259.051.75.75 0 0 0 .31-.074c.031-.014.056-.036.084-.054.044-.028.091-.047.13-.084.02-.02.028-.046.046-.068.012-.015.031-.02.042-.036l2.001-2.823a.75.75 0 0 0-.178-1.045m0 5.999a.75.75 0 0 0-1.045.178l-1.48 2.087-.62-.638a.75.75 0 1 0-1.076 1.045l1.248 1.285c.017.016.039.023.056.037.018.016.029.038.049.052.032.023.068.034.102.051q.036.02.072.036a.8.8 0 0 0 .259.051.75.75 0 0 0 .31-.074c.031-.014.056-.036.084-.054.044-.028.091-.047.13-.084.02-.02.028-.046.046-.068.012-.015.031-.02.042-.036l2.001-2.823a.75.75 0 0 0-.178-1.045m11.442 8.919H8a.75.75 0 0 1 0-1.5h9.25a.75.75 0 0 1 0 1.5m0-6H8a.75.75 0 0 1 0-1.5h9.25a.75.75 0 0 1 0 1.5m0-6H8a.75.75 0 0 1 0-1.5h9.25a.75.75 0 0 1 0 1.5"/></svg>`;
}
