/**
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
/* Generated by `yarn generate:workflow-icons` from icon-source/workflow/. Do not edit by hand. */

/**
 * The MovieCamera workflow icon as a framework-agnostic SVG string. Usable via `innerHTML`,
 * React `dangerouslySetInnerHTML`, Vue `v-html`, or Lit `unsafeSVG`. Color follows
 * `var(--swc-icon-color, currentColor)`.
 */
export function Icon_MovieCamera(): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path fill="var(--swc-icon-color, currentColor)" d="M11.75 16h-8.5C2.01 16 1 14.99 1 13.75v-7.5C1 5.01 2.01 4 3.25 4h8.5C12.99 4 14 5.01 14 6.25v1.046l2.368-1.684a1 1 0 0 1 .1-.06 1.74 1.74 0 0 1 1.702.077c.52.322.83.878.83 1.49v5.763c0 .61-.31 1.167-.83 1.489a1.74 1.74 0 0 1-1.703.076 1 1 0 0 1-.099-.06L14 12.705v1.046c0 1.24-1.01 2.25-2.25 2.25M3.25 5.5a.75.75 0 0 0-.75.75v7.5c0 .414.336.75.75.75h8.5a.75.75 0 0 0 .75-.75v-2.5a.75.75 0 0 1 1.185-.611l3.49 2.482a.24.24 0 0 0 .206-.026.24.24 0 0 0 .119-.213V7.118a.24.24 0 0 0-.119-.213.24.24 0 0 0-.206-.026l-3.49 2.482A.751.751 0 0 1 12.5 8.75v-2.5a.75.75 0 0 0-.75-.75z"/></svg>`;
}
