/**
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
/* Generated by `yarn generate:workflow-icons` from icon-source/workflow/. Do not edit by hand. */

/**
 * The SelectRectangle workflow icon as a framework-agnostic SVG string. Usable via `innerHTML`,
 * React `dangerouslySetInnerHTML`, Vue `v-html`, or Lit `unsafeSVG`. Color follows
 * `var(--swc-icon-color, currentColor)`.
 */
export function Icon_SelectRectangle(): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path fill="var(--swc-icon-color, currentColor)" d="M4.25 2C3.01 2 2 3.01 2 4.25a.75.75 0 0 0 1.5 0 .75.75 0 0 1 .75-.75.75.75 0 0 0 0-1.5M8.5 16.5H7.25a.75.75 0 0 0 0 1.5H8.5a.75.75 0 0 0 0-1.5m7.25-13a.75.75 0 0 1 .75.75.75.75 0 0 0 1.5 0C18 3.01 16.99 2 15.75 2a.75.75 0 0 0 0 1.5m-13 10a.75.75 0 0 0 .75-.75V11.5a.75.75 0 0 0-1.5 0v1.25c0 .414.336.75.75.75m0-4.25a.75.75 0 0 0 .75-.75V7.25a.75.75 0 0 0-1.5 0V8.5c0 .414.336.75.75.75m1.5 7.25a.75.75 0 0 1-.75-.75.75.75 0 0 0-1.5 0C2 16.99 3.01 18 4.25 18a.75.75 0 0 0 0-1.5M8.5 2H7.25a.75.75 0 0 0 0 1.5H8.5a.75.75 0 0 0 0-1.5m8.75 13a.75.75 0 0 0-.75.75.75.75 0 0 1-.75.75.75.75 0 0 0 0 1.5c1.24 0 2.25-1.01 2.25-2.25a.75.75 0 0 0-.75-.75m0-8.5a.75.75 0 0 0-.75.75V8.5a.75.75 0 0 0 1.5 0V7.25a.75.75 0 0 0-.75-.75m0 4.25a.75.75 0 0 0-.75.75v1.25a.75.75 0 0 0 1.5 0V11.5a.75.75 0 0 0-.75-.75M12.75 2H11.5a.75.75 0 0 0 0 1.5h1.25a.75.75 0 0 0 0-1.5m0 14.5H11.5a.75.75 0 0 0 0 1.5h1.25a.75.75 0 0 0 0-1.5"/></svg>`;
}
