/**
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
/* Generated by `yarn generate:workflow-icons` from icon-source/workflow/. Do not edit by hand. */

/**
 * The SelectAndMove workflow icon as a framework-agnostic SVG string. Usable via `innerHTML`,
 * React `dangerouslySetInnerHTML`, Vue `v-html`, or Lit `unsafeSVG`. Color follows
 * `var(--swc-icon-color, currentColor)`.
 */
export function Icon_SelectAndMove(): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path fill="var(--swc-icon-color, currentColor)" d="M2.457 9.896A1.46 1.46 0 0 1 1 8.439V2.354c0-.591.353-1.119.898-1.345a1.45 1.45 0 0 1 1.585.313l4.16 4.149c.422.42.545 1.055.313 1.618A1.45 1.45 0 0 1 6.616 8H4.964q-.017.003-.023-.002L3.49 9.465c-.28.281-.652.43-1.032.43M1.75 8.439l.75.001zm.673-6.054L2.5 8.37l1.432-1.484c.383-.387.873-.387 1.034-.387h1.65zM19.21 11.53l-2.002-1.75a.625.625 0 1 0-.822.94l.606.53H12.75V6.959l.53.605a.623.623 0 0 0 .881.06.625.625 0 0 0 .06-.882L12.47 4.74a.646.646 0 0 0-.942 0L9.78 6.742a.625.625 0 1 0 .942.822l.529-.605v4.291H7.408l.606-.53a.625.625 0 1 0-.822-.94l-2.003 1.75a.626.626 0 0 0 0 .94l2.003 1.75a.623.623 0 0 0 .882-.059.625.625 0 0 0-.06-.882l-.606-.529h3.842v3.791l-.53-.605a.625.625 0 1 0-.94.822l1.75 2.003a.626.626 0 0 0 .94 0l1.75-2.003a.625.625 0 1 0-.94-.822l-.53.605V12.75h4.242l-.606.53a.625.625 0 1 0 .822.94l2.003-1.75a.626.626 0 0 0 0-.94"/></svg>`;
}
