/**
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
/* Generated by `yarn generate:workflow-icons` from icon-source/workflow/. Do not edit by hand. */

/**
 * The Shapes workflow icon as a framework-agnostic SVG string. Usable via `innerHTML`,
 * React `dangerouslySetInnerHTML`, Vue `v-html`, or Lit `unsafeSVG`. Color follows
 * `var(--swc-icon-color, currentColor)`.
 */
export function Icon_Shapes(): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path fill="var(--swc-icon-color, currentColor)" d="M11.83 13H3.17c-.814 0-1.542-.42-1.949-1.125a2.23 2.23 0 0 1 0-2.25l4.33-7.5A2.23 2.23 0 0 1 7.5 1c.813 0 1.542.42 1.949 1.125l4.33 7.5c.407.705.407 1.546 0 2.25S12.644 13 11.83 13M7.5 2.5a.74.74 0 0 0-.65.375l-4.33 7.5a.74.74 0 0 0 0 .75.74.74 0 0 0 .65.375h8.66a.74.74 0 0 0 .65-.375.74.74 0 0 0 0-.75l-4.33-7.5A.74.74 0 0 0 7.5 2.5m-1.299 0h.01z"/><path fill="var(--swc-icon-color, currentColor)" d="m12.294 18.93-.133-.001a6.68 6.68 0 0 1-5.68-3.408.75.75 0 0 1 1.31-.733 5.17 5.17 0 0 0 4.4 2.64 5.08 5.08 0 0 0 3.67-1.437 5.12 5.12 0 0 0 1.58-3.614 5.14 5.14 0 0 0-3.093-4.824.75.75 0 1 1 .6-1.375 6.64 6.64 0 0 1 3.993 6.228 6.6 6.6 0 0 1-2.04 4.666 6.6 6.6 0 0 1-4.607 1.858"/></svg>`;
}
