/**
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
/* Generated by `yarn generate:workflow-icons` from icon-source/workflow/. Do not edit by hand. */

/**
 * The Shuffle workflow icon as a framework-agnostic SVG string. Usable via `innerHTML`,
 * React `dangerouslySetInnerHTML`, Vue `v-html`, or Lit `unsafeSVG`. Color follows
 * `var(--swc-icon-color, currentColor)`.
 */
export function Icon_Shuffle(): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path fill="var(--swc-icon-color, currentColor)" d="m18.744 4.188-2.25-2.25a.75.75 0 1 0-1.06 1.06L16.436 4h-2.224c-2.108 0-4.001 1.299-4.797 3.252l-2.47 4.873C6.356 13.567 5.01 14.5 3.512 14.5H1.714a.75.75 0 0 0 0 1.5h1.798c2.11 0 4.003-1.299 4.797-3.252l2.47-4.873c.59-1.442 1.937-2.375 3.433-2.375h2.16l-.938.937a.75.75 0 1 0 1.06 1.061l2.25-2.25a.75.75 0 0 0 0-1.06M7.103 7.389a.75.75 0 0 1-.612-.314C5.787 6.09 4.673 5.5 3.511 5.5H1.715a.75.75 0 0 1 0-1.5h1.798c1.644 0 3.215.823 4.2 2.202a.751.751 0 0 1-.61 1.187m11.641 7.347-2.25-2.25a.75.75 0 1 0-1.06 1.06l.953.954h-2.174c-1.155 0-2.266-.584-2.97-1.562a.75.75 0 0 0-1.217.877C11.01 15.182 12.575 16 14.212 16h2.207l-.986.986a.75.75 0 1 0 1.06 1.06l2.25-2.25a.75.75 0 0 0 0-1.06"/></svg>`;
}
