/**
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
/* Generated by `yarn generate:workflow-icons` from icon-source/workflow/. Do not edit by hand. */
import { CSSResultArray, html, TemplateResult } from 'lit';
import { unsafeSVG } from 'lit/directives/unsafe-svg.js';

import { IconBase } from '@adobe/spectrum-wc-core/components/icon';
import { defineElement } from '@adobe/spectrum-wc-core/element/index.js';

import { Icon_StrokeSolid } from './StrokeSolid.js';

import styles from './stylesheets/icon-base.css';

/**
 * The StrokeSolid workflow icon as a custom element.
 *
 * @element swc-icon-stroke-solid
 * @since 2.0.0-beta.2
 *
 * @cssprop --swc-icon-color - Color of the icon.
 * @cssprop --swc-icon-inline-size - Inline size of the icon box.
 * @cssprop --swc-icon-block-size - Block size of the icon box.
 */
export class IconStrokeSolid extends IconBase {
  public static override get styles(): CSSResultArray {
    return [styles];
  }

  protected override render(): TemplateResult {
    return html`
      <span class="swc-Icon">${unsafeSVG(Icon_StrokeSolid())}</span>
    `;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'swc-icon-stroke-solid': IconStrokeSolid;
  }
}

defineElement('swc-icon-stroke-solid', IconStrokeSolid);
