/**
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
/* Generated by `yarn generate:workflow-icons` from icon-source/workflow/. Do not edit by hand. */

/**
 * The TextSuperscript workflow icon as a framework-agnostic SVG string. Usable via `innerHTML`,
 * React `dangerouslySetInnerHTML`, Vue `v-html`, or Lit `unsafeSVG`. Color follows
 * `var(--swc-icon-color, currentColor)`.
 */
export function Icon_TextSuperscript(): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path fill="var(--swc-icon-color, currentColor)" d="M18 7.204a.75.75 0 0 1-.75-.75V2.828l-.494.21a.751.751 0 0 1-.582-1.383l1.535-.648a.75.75 0 0 1 1.041.691v4.756a.75.75 0 0 1-.75.75M12.5 2h-9C2.26 2 1.25 3.01 1.25 4.25v1.11a.75.75 0 0 0 1.5 0V4.25c0-.413.337-.75.75-.75h3.75v13H5.63a.75.75 0 0 0 0 1.5h4.64a.75.75 0 0 0 0-1.5H8.75v-13h3.75c.413 0 .75.337.75.75v1.11a.75.75 0 0 0 1.5 0V4.25C14.75 3.01 13.74 2 12.5 2"/></svg>`;
}
