/**
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
/* Generated by `yarn generate:workflow-icons` from icon-source/workflow/. Do not edit by hand. */

/**
 * The ThumbUp workflow icon as a framework-agnostic SVG string. Usable via `innerHTML`,
 * React `dangerouslySetInnerHTML`, Vue `v-html`, or Lit `unsafeSVG`. Color follows
 * `var(--swc-icon-color, currentColor)`.
 */
export function Icon_ThumbUp(): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path fill="var(--swc-icon-color, currentColor)" d="M18.53 8.225A2.75 2.75 0 0 0 16.242 7h-3.045a.754.754 0 0 1-.747-.688l-.2-2.38a1 1 0 0 0-.01-.189c-.112-.653-.373-2.183-2.175-2.183-1.482 0-1.79 1.669-2.087 3.284C7.638 6.69 7.32 7.997 6.318 8H4.25C3.01 8 2 9.01 2 10.25v5.5C2 16.99 3.01 18 4.25 18h7.5a1 1 0 0 0 .1-.007h1.44a3.74 3.74 0 0 0 3.46-2.31l2.03-4.876a2.74 2.74 0 0 0-.25-2.582M3.5 15.75v-5.5a.75.75 0 0 1 .75-.75h1v7h-1a.75.75 0 0 1-.75-.75m13.896-5.52-2.03 4.877a2.25 2.25 0 0 1-2.076 1.386h-1.54a1 1 0 0 0-.1.007h-4.9V9.467c1.956-.3 2.385-2.624 2.704-4.352.122-.667.351-1.909.611-2.055.36 0 .53 0 .686.877l.001.042.203 2.456A2.26 2.26 0 0 0 13.197 8.5h3.045c.425 0 .804.203 1.04.557s.278.78.114 1.173"/></svg>`;
}
