/**
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
/* Generated by `yarn generate:workflow-icons` from icon-source/workflow/. Do not edit by hand. */

/**
 * The TransformDistort workflow icon as a framework-agnostic SVG string. Usable via `innerHTML`,
 * React `dangerouslySetInnerHTML`, Vue `v-html`, or Lit `unsafeSVG`. Color follows
 * `var(--swc-icon-color, currentColor)`.
 */
export function Icon_TransformDistort(): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path fill="var(--swc-icon-color, currentColor)" d="m17.116 12.15-1.064-4.215a2.122 2.122 0 0 0-1.212-3.867c-.667 0-1.256.315-1.646.798L7.866 3.104A2.123 2.123 0 0 0 5.75 1.068a2.12 2.12 0 0 0-1.126 3.92L2.782 14.16A2.12 2.12 0 0 0 1 16.25c0 1.172.953 2.125 2.125 2.125a2.126 2.126 0 0 0 2.07-1.662l9.834-1.43a2.12 2.12 0 0 0 1.846 1.092A2.127 2.127 0 0 0 19 14.25a2.12 2.12 0 0 0-1.884-2.1M14.8 13.8l-9.823 1.43a2.1 2.1 0 0 0-.725-.773l1.843-9.173a2.1 2.1 0 0 0 1.297-.757l5.333 1.765a2.115 2.115 0 0 0 1.87 2.002l1.065 4.218a2.13 2.13 0 0 0-.86 1.29m.04-8.483a.876.876 0 0 1 0 1.75.876.876 0 0 1 0-1.75m-9.09-3a.876.876 0 0 1 0 1.75.876.876 0 0 1 0-1.75M3.125 17.125a.876.876 0 0 1 0-1.75.876.876 0 0 1 0 1.75m13.75-2a.876.876 0 0 1 0-1.75.876.876 0 0 1 0 1.75"/></svg>`;
}
