/**
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
/* Generated by `yarn generate:workflow-icons` from icon-source/workflow/. Do not edit by hand. */

/**
 * The UsersLock workflow icon as a framework-agnostic SVG string. Usable via `innerHTML`,
 * React `dangerouslySetInnerHTML`, Vue `v-html`, or Lit `unsafeSVG`. Color follows
 * `var(--swc-icon-color, currentColor)`.
 */
export function Icon_UsersLock(): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path fill="var(--swc-icon-color, currentColor)" d="M11.75 10.748c-2.276 0-4.128-1.946-4.128-4.339S9.474 2.07 11.75 2.07s4.128 1.947 4.128 4.34-1.852 4.338-4.128 4.338m0-7.178c-1.45 0-2.628 1.274-2.628 2.84s1.179 2.838 2.628 2.838 2.628-1.273 2.628-2.839S13.199 3.57 11.75 3.57M5.577 16.998a.75.75 0 0 1-.747-.831c.303-2.788 3.255-4.89 6.868-4.89a.75.75 0 0 1 0 1.5c-2.799 0-5.16 1.56-5.376 3.552a.75.75 0 0 1-.745.669m.301-8a.75.75 0 0 1-.308-.066c-1.521-.684-2.505-2.25-2.505-3.99 0-2.393 1.852-4.34 4.128-4.34q.367.001.716.065a.75.75 0 0 1-.265 1.477 2.5 2.5 0 0 0-.45-.041c-1.45 0-2.629 1.273-2.629 2.838 0 1.15.636 2.18 1.62 2.623a.749.749 0 0 1-.307 1.434m-4.807 6.5a.75.75 0 0 1-.747-.831c.291-2.675 3.007-4.729 6.46-4.882.375-.048.763.302.781.716s-.301.764-.715.782c-2.663.12-4.828 1.644-5.034 3.546a.75.75 0 0 1-.745.669m17.929-.5a1 1 0 0 0-.995-.999v-.991c0-1.109-.901-2.01-2.01-2.01a2.01 2.01 0 0 0-2.009 2.01V14a1 1 0 0 0-.986.997v3c0 .22.086.414.207.58a1 1 0 0 0 .276.255.97.97 0 0 0 .517.165h4c.194 0 .364-.07.517-.165q.163-.101.276-.256a.98.98 0 0 0 .207-.579zm-3.005-2.75c.42 0 .76.34.76.76v.99h-1.519v-.99c0-.42.341-.76.76-.76"/></svg>`;
}
