/**
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
/* Generated by `yarn generate:workflow-icons` from icon-source/workflow/. Do not edit by hand. */

/**
 * The VectorDraw workflow icon as a framework-agnostic SVG string. Usable via `innerHTML`,
 * React `dangerouslySetInnerHTML`, Vue `v-html`, or Lit `unsafeSVG`. Color follows
 * `var(--swc-icon-color, currentColor)`.
 */
export function Icon_VectorDraw(): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path fill="var(--swc-icon-color, currentColor)" d="m17.678 5.251-2.96-2.959c-.849-.85-2.332-.85-3.182 0L10.29 3.539l-.016.024L5.79 6.01a2.76 2.76 0 0 0-1.253 1.435L1.22 16.162a2 2 0 0 0 .454 2.118 1.99 1.99 0 0 0 2.153.44l9.248-3.719a2.75 2.75 0 0 0 1.435-1.322l2.078-4.157 1.09-1.09a2.253 2.253 0 0 0 0-3.181m-4.51 7.757a1.24 1.24 0 0 1-.652.6L4.08 17.001l4.262-4.262c.053.008.101.032.157.032a1.25 1.25 0 1 0-1.25-1.25c0 .056.025.104.032.158l-4.44 4.44 3.097-8.14c.106-.279.309-.511.57-.654l4.357-2.377 4.222 4.222zm3.45-5.636-.604.603-4.02-4.02.603-.602a.77.77 0 0 1 1.06 0l2.96 2.959a.75.75 0 0 1 0 1.06"/></svg>`;
}
