/**
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
/* Generated by `yarn generate:workflow-icons` from icon-source/workflow/. Do not edit by hand. */

/**
 * The VolumeTwo workflow icon as a framework-agnostic SVG string. Usable via `innerHTML`,
 * React `dangerouslySetInnerHTML`, Vue `v-html`, or Lit `unsafeSVG`. Color follows
 * `var(--swc-icon-color, currentColor)`.
 */
export function Icon_VolumeTwo(): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path fill="var(--swc-icon-color, currentColor)" d="M13.001 12.747a.75.75 0 0 1-.417-1.374c.411-.274.666-.802.666-1.376s-.255-1.101-.666-1.376a.75.75 0 0 1 .832-1.248c.835.558 1.334 1.538 1.334 2.624s-.499 2.066-1.334 2.624a.75.75 0 0 1-.415.126m3.25 1.5a.751.751 0 0 1-.418-1.374c.874-.583 1.417-1.686 1.417-2.876 0-1.191-.543-2.293-1.416-2.876a.75.75 0 0 1 .832-1.248c1.285.857 2.084 2.438 2.084 4.124s-.798 3.266-2.083 4.124a.75.75 0 0 1-.416.126m-7.003 4.09c-.454 0-.9-.178-1.235-.514L5.409 15.22a.76.76 0 0 0-.53-.22H3.25C2.01 15 1 13.99 1 12.75v-5.5C1 6.01 2.01 5 3.25 5h1.629c.197 0 .39-.08.53-.22l2.604-2.603a1.74 1.74 0 0 1 1.907-.38c.656.272 1.08.907 1.08 1.617v13.172c0 .71-.424 1.345-1.08 1.616a1.8 1.8 0 0 1-.672.135M3.25 6.5a.75.75 0 0 0-.75.75v5.5c0 .413.337.75.75.75h1.629c.592 0 1.172.24 1.59.66l2.604 2.603a.24.24 0 0 0 .273.053.24.24 0 0 0 .154-.23V3.414a.24.24 0 0 0-.154-.23.24.24 0 0 0-.273.053L6.47 5.841c-.42.419-1 .659-1.591.659z"/></svg>`;
}
