name: Setup Job
description: Common setup for all jobs
inputs:
    node-version:
        description: 'The Node.js version to use'
        required: false
        default: '20'
runs:
    using: 'composite'
    steps:
        - name: Enable Corepack
          shell: bash
          run: corepack enable

        - name: Setup Node LTS version
          uses: actions/setup-node@v4
          with:
              node-version: ${{ inputs.node-version }}
              cache: 'yarn'
              registry-url: 'https://registry.npmjs.org'

        ## --- YARN CACHE --- ##
        - name: Check for cached dependencies
          continue-on-error: true
          id: cache-dependencies
          uses: actions/cache@v4
          with:
              path: |
                  .cache/yarn
                  node_modules
              key: ${{ runner.os }}-node${{ inputs.node-version }}-${{ hashFiles('yarn.lock') }}

        ## --- INSTALL --- ##
        - name: Install dependencies
          shell: bash
          run: yarn install --immutable

        - name: Build the project
          shell: bash
          run: yarn build
