blank_issues_enabled: true
contact_links:
    - name: Questions or discussion
      url: https://github.com/adobe/spectrum-web-components/discussions
      about: Please post general questions or discussion topics here.
