name: Spectrum 2 Bug Report
description: Report an issue with the Spectrum 2 system
title: '[S2 Bug]: '
labels: [bug, triage, needs jira ticket, Spectrum 2]
# assignees:
body:
    - type: markdown
      attributes:
          value: |
              Thanks for taking the time to fill out this bug report! Your issue will be triaged within a week of filing the issue.
    - type: checkboxes
      id: terms
      attributes:
          label: Code of conduct
          description: By submitting this issue, you agree to follow our [code of conduct](https://github.com/adobe/spectrum-web-components/blob/main/CODE_OF_CONDUCT.md#adobe-code-of-conduct).
          options:
              - label: I agree to follow this project's code of conduct.
                required: true
    - type: dropdown
      id: reviewed-issues
      attributes:
          label: Have you reviewed existing [existing Spectrum 2 issues](https://github.com/adobe/spectrum-web-components/labels/Spectrum%202)?
          description: Please confirm if you've reviewed existing issues to avoid duplicates.
          options:
              - Yes, I’ve reviewed existing issues.
              - Oops, I’ll check now.
    - type: input
      id: components
      attributes:
          label: Impacted component(s)
          description: Please list the component(s) impacted by this issue.
      validations:
          required: true
    - type: textarea
      id: expected-behavior
      attributes:
          label: Expected behavior
          description: A brief description of what you expected to happen.
    - type: textarea
      id: actual-behavior
      attributes:
          label: Actual behavior
      validations:
          required: true
    - type: textarea
      id: screenshot
      attributes:
          label: Screenshots
          description: You can attach images by clicking this area to highlight it and then dragging files in.
    - type: dropdown
      id: browsers
      attributes:
          label: What browsers are you seeing the problem in?
          multiple: true
          options:
              - Firefox
              - Chrome
              - Safari
              - Microsoft Edge
    - type: textarea
      id: code
      attributes:
          label: Sample code or abstract reproduction which illustrates the problem
          description: Please use [webcomponents.dev](https://studio.webcomponents.dev/workspace/adobe) to abstract the issue in an isolated environment. In most cases, a video or code block is not sufficient enough for us to diagnose the problem.
    - type: textarea
      id: reproduce
      attributes:
          label: How can we reproduce this issue?
          value: |
              1. Go to '...'
              2. Click on '....'
              3. Scroll to '....'
              4. Check console
              5. See error
    - type: dropdown
      id: severity
      attributes:
          label: Severity
          description: Please select the severity level of this issue. For descriptions of each level, refer to our [documentation](https://github.com/adobe/spectrum-web-components/blob/main/CONTRIBUTING.md#issue-severity-classification)
          options:
              - SEV 1
              - SEV 2
              - SEV 3
              - SEV 4
              - SEV 5
    - type: textarea
      id: logs
      attributes:
          label: Logs taken while reproducing problem
          description: You can attach log files by clicking this area to highlight it and then dragging files in.
    - type: checkboxes
      id: jira-number
      attributes:
          label: Jira ticket
          description: If you would like to track this issue in Jira, check this box and we will comment the Jira ticket ID once the issue has been triaged.
          options:
              - label: Yes, please tell me the ticket number!
