/**
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */

/** Shared license header prepended to every generated module. */
export const LICENSE = `/**
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */`;

/** "Do not edit" banner for a generated file, naming the command and its source folder. */
export function generatedBanner(command, sourceDir) {
  return `/* Generated by \`${command}\` from ${sourceDir}. Do not edit by hand. */`;
}

/**
 * PascalCase logical name to the kebab-case value used by the `icon` attribute (UI
 * icons) or the element tag suffix (workflow icons, `swc-icon-<kebab>`).
 *
 * Splits on two boundaries so digit-led acronyms kebab cleanly: an acronym-to-word
 * boundary (`3DAsset` -> `3D-Asset`, `HTMLParser` -> `HTML-Parser`) and a
 * lowercase-to-uppercase boundary (`AddCircle` -> `Add-Circle`). A digit immediately
 * before an uppercase letter is not a boundary, so `3D` stays `3d` rather than `3-d`.
 */
export function toKebab(name) {
  return name
    .replace(/([A-Z])([A-Z][a-z])/g, '$1-$2')
    .replace(/([a-z])([A-Z])/g, '$1-$2')
    .toLowerCase();
}
