"use strict";var l=Object.defineProperty;var p=Object.getOwnPropertyDescriptor;var i=(o,s,e,t)=>{for(var r=t>1?void 0:t?p(s,e):s,a=o.length-1,n;a>=0;a--)(n=o[a])&&(r=(t?n(s,e,r):n(r))||r);return t&&r&&l(s,e,r),r};import{html as d,nothing as u,SpectrumElement as h}from"@spectrum-web-components/base";import{property as c}from"@spectrum-web-components/base/src/decorators.js";import"@spectrum-web-components/icons-ui/icons/sp-icon-arrow100.js";import y from"./table-head-cell.css.js";import v from"@spectrum-web-components/icon/src/spectrum-icon-arrow.css.js";const b=o=>({asc:"ascending",desc:"descending"})[o]||"none";export class TableHeadCell extends h{constructor(){super(...arguments);this.active=!1;this.role="columnheader";this.sortable=!1;this.sortKey=""}static get styles(){return[y,v]}handleKeydown(e){const{code:t}=e;switch(t){case"Space":e.preventDefault(),this.addEventListener("keyup",this.handleKeyup),this.active=!0;break;default:break}}handleKeypress(e){const{code:t}=e;switch(t){case"Enter":case"NumpadEnter":this.click();break;default:break}}handleKeyup(e){const{code:t}=e;switch(t){case"Space":this.active=!1,this.removeEventListener("keyup",this.handleKeyup),this.click();break;default:break}}handleClick(){this.sortable&&(this.sortDirection?this.sortDirection=this.sortDirection==="asc"?"desc":"asc":this.sortDirection="asc",this.dispatchEvent(new CustomEvent("sorted",{bubbles:!0,detail:{sortDirection:this.sortDirection,sortKey:this.sortKey}})))}render(){const e=this.sortable&&!!this.sortDirection;return d`
            ${e?d`
                      <sp-icon-arrow100
                          class="sortedIcon spectrum-UIIcon-ArrowDown100"
                      ></sp-icon-arrow100>
                  `:u}
            <slot></slot>
        `}firstUpdated(e){super.firstUpdated(e),this.addEventListener("click",this.handleClick),this.addEventListener("keydown",this.handleKeydown),this.addEventListener("keypress",this.handleKeypress)}update(e){e.has("sortDirection")&&this.setAttribute("aria-sort",b(this.sortDirection)),e.has("sortable")&&(this.tabIndex=this.sortable?0:-1),super.update(e)}}i([c({type:Boolean,reflect:!0})],TableHeadCell.prototype,"active",2),i([c({reflect:!0})],TableHeadCell.prototype,"role",2),i([c({type:Boolean,reflect:!0})],TableHeadCell.prototype,"sortable",2),i([c({reflect:!0,attribute:"sort-direction"})],TableHeadCell.prototype,"sortDirection",2),i([c({attribute:"sort-key"})],TableHeadCell.prototype,"sortKey",2);
//# sourceMappingURL=TableHeadCell.js.map
