/**
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
/* Generated by `yarn generate:ui-icons` from svg-source/ui/. Do not edit by hand. */
import { html } from 'lit';

import { UiIconArt } from '../ui-icons.types.js';

export const Chevron = {
  50: html`
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 8 8">
      <path
        fill="var(--swc-icon-color, currentColor)"
        d="M2.625 6.875a.628.628 0 0 1-.442-1.067L3.99 4 2.183 2.192a.626.626 0 0 1 .885-.885l2.25 2.25a.63.63 0 0 1 0 .885l-2.25 2.25a.62.62 0 0 1-.443.183"
      />
    </svg>
  `,
  75: html`
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 10 10">
      <path
        fill="var(--swc-icon-color, currentColor)"
        d="M3.375 9.375a.628.628 0 0 1-.442-1.067L6.24 5 2.933 1.692a.626.626 0 0 1 .885-.885l3.75 3.75a.63.63 0 0 1 0 .885l-3.75 3.75a.62.62 0 0 1-.443.183"
      />
    </svg>
  `,
  100: html`
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 10 10">
      <path
        fill="var(--swc-icon-color, currentColor)"
        d="M2.838 9.825a.75.75 0 0 1-.53-1.28L5.852 5 2.308 1.455a.75.75 0 1 1 1.06-1.06L7.442 4.47a.75.75 0 0 1 0 1.06L3.368 9.605a.75.75 0 0 1-.53.22"
      />
    </svg>
  `,
  200: html`
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 12 12">
      <path
        fill="var(--swc-icon-color, currentColor)"
        d="M3.563 11.7a.824.824 0 0 1-.583-1.408L7.27 6 2.98 1.708A.824.824 0 1 1 4.145.542L9.02 5.417a.824.824 0 0 1 0 1.166l-4.875 4.875a.82.82 0 0 1-.584.242"
      />
    </svg>
  `,
  300: html`
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 14 14">
      <path
        fill="var(--swc-icon-color, currentColor)"
        d="M4.25 13.25a1 1 0 0 1-.707-1.707L8.086 7 3.543 2.457a1 1 0 1 1 1.414-1.414l5.25 5.25a1 1 0 0 1 0 1.414l-5.25 5.25a1 1 0 0 1-.707.293"
      />
    </svg>
  `,
} satisfies UiIconArt;
