/**
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
/* Generated by `yarn generate:ui-icons` from icon-source/ui/. Do not edit by hand. */
import { html } from 'lit';

import { UiIconArt } from '../ui-icons.types.js';

export const Add = {
  50: html`
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 8 8">
      <path
        fill="var(--swc-icon-color, currentColor)"
        d="M6.625 3.375h-2v-2a.626.626 0 0 0-1.25 0v2h-2a.626.626 0 0 0 0 1.25h2v2a.626.626 0 0 0 1.25 0v-2h2a.626.626 0 0 0 0-1.25"
      />
    </svg>
  `,
  75: html`
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 10 10">
      <path
        fill="var(--swc-icon-color, currentColor)"
        d="M8.125 4.375h-2.5v-2.5a.626.626 0 0 0-1.25 0v2.5h-2.5a.626.626 0 0 0 0 1.25h2.5v2.5a.626.626 0 0 0 1.25 0v-2.5h2.5a.626.626 0 0 0 0-1.25"
      />
    </svg>
  `,
  100: html`
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 10 10">
      <path
        fill="var(--swc-icon-color, currentColor)"
        d="M8.5 4.25H5.75V1.5a.75.75 0 0 0-1.5 0v2.75H1.5a.75.75 0 0 0 0 1.5h2.75V8.5a.75.75 0 0 0 1.5 0V5.75H8.5a.75.75 0 0 0 0-1.5"
      />
    </svg>
  `,
  200: html`
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 12 12">
      <path
        fill="var(--swc-icon-color, currentColor)"
        d="M10 5.175H6.825V2a.825.825 0 1 0-1.65 0v3.175H2a.825.825 0 1 0 0 1.65h3.175V10a.825.825 0 1 0 1.65 0V6.825H10a.825.825 0 1 0 0-1.65"
      />
    </svg>
  `,
  300: html`
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 14 14">
      <path
        fill="var(--swc-icon-color, currentColor)"
        d="M11.5 6H8V2.5a1 1 0 1 0-2 0V6H2.5a1 1 0 1 0 0 2H6v3.5a1 1 0 1 0 2 0V8h3.5a1 1 0 1 0 0-2"
      />
    </svg>
  `,
} satisfies UiIconArt;
