/**
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
/* Generated by `yarn generate:ui-icons` from icon-source/ui/. Do not edit by hand. */
import { html } from 'lit';

import { UiIconArt } from '../ui-icons.types.js';

export const Asterisk = {
  50: html`
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 8 8">
      <path
        fill="var(--swc-icon-color, currentColor)"
        d="M6.368 6.34c.05.052.084.12 0 .185l-1.056.68c-.084.052-.118.018-.152-.068l-1.31-2.28L2.132 6.75c-.017.033-.068.067-.119 0l-.816-.852c-.085-.05-.068-.102 0-.152l1.939-1.617-2.212-.833c-.034 0-.084-.068-.051-.153l.578-1.156a.09.09 0 0 1 .112-.061.1.1 0 0 1 .042.028l1.939 1.258.119-2.48A.09.09 0 0 1 3.737.63c.028 0 1.44.184 1.44.184.085 0 .102.034.085.12l-.664 2.43 2.246-.68c.05-.034.101-.034.135.068l.222 1.258c.016.085 0 .12-.068.12l-2.348.183z"
      />
    </svg>
  `,
  75: html`
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 10 10">
      <path
        fill="var(--swc-icon-color, currentColor)"
        d="M7.51 7.487c.053.055.089.127 0 .195l-1.12.722c-.09.054-.126.018-.162-.072L4.84 5.914 3.017 7.92c-.019.036-.072.072-.126 0l-.866-.903c-.09-.053-.072-.108 0-.161L4.081 5.14l-2.345-.883c-.036 0-.09-.072-.055-.163l.614-1.226a.097.097 0 0 1 .118-.064.1.1 0 0 1 .045.029l2.056 1.334.126-2.63a.097.097 0 0 1 .08-.108c.029 0 1.526.195 1.526.195.09 0 .108.036.09.127L5.632 4.33l2.382-.722c.053-.036.108-.036.144.072l.235 1.335c.017.09 0 .126-.072.126l-2.49.195z"
      />
    </svg>
  `,
  100: html`
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 10 10">
      <path
        fill="var(--swc-icon-color, currentColor)"
        d="M7.765 7.725c.06.06.099.14 0 .214l-1.23.794c-.1.06-.14.02-.179-.079l-1.528-2.66-2.005 2.208c-.02.038-.079.078-.138 0l-.952-.993c-.1-.06-.08-.12 0-.178l2.262-1.886-2.58-.972c-.04 0-.1-.08-.06-.179l.675-1.349a.107.107 0 0 1 .13-.07q.028.008.048.032L4.47 4.075l.14-2.894a.107.107 0 0 1 .086-.118c.033 0 1.68.214 1.68.214.1 0 .118.04.1.14L5.7 4.251l2.62-.794c.06-.04.12-.04.159.08l.258 1.468c.02.1 0 .139-.08.139l-2.738.214z"
      />
    </svg>
  `,
  200: html`
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 12 12">
      <path
        fill="var(--swc-icon-color, currentColor)"
        d="M8.968 9.063c.064.066.104.152 0 .239l-1.341.865c-.104.065-.15.022-.194-.086l-1.66-2.897-2.184 2.4c-.022.042-.086.085-.15 0L2.4 8.502c-.103-.064-.086-.13 0-.194l2.464-2.055L2.05 5.19c-.044 0-.104-.086-.066-.195l.734-1.465a.115.115 0 0 1 .14-.077.1.1 0 0 1 .055.036L5.38 5.086l.151-3.157a.114.114 0 0 1 .094-.13c.036 0 1.83.24 1.83.24.104 0 .13.043.104.15L6.714 5.28l2.853-.865c.065-.044.13-.044.174.086l.28 1.6c.022.103 0 .151-.085.151l-2.984.239z"
      />
    </svg>
  `,
  300: html`
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 14 14">
      <path
        fill="var(--swc-icon-color, currentColor)"
        d="M10.266 10.324c.07.071.116.164 0 .258l-1.454.938c-.116.071-.163.024-.21-.094l-1.8-3.141-2.367 2.6c-.024.045-.094.092-.163 0l-1.13-1.167c-.118-.07-.094-.141 0-.21l2.671-2.227L2.766 6.13c-.047 0-.116-.094-.071-.211l.8-1.593a.124.124 0 0 1 .153-.084.13.13 0 0 1 .058.038l2.669 1.738.164-3.422a.124.124 0 0 1 .1-.14c.038 0 1.983.258 1.983.258.118 0 .14.047.118.164l-.915 3.349 3.094-.938c.07-.047.14-.047.187.094l.3 1.734c.023.118 0 .164-.094.164l-3.234.258z"
      />
    </svg>
  `,
} satisfies UiIconArt;
