/**
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
/* Generated by `yarn generate:ui-icons` from icon-source/ui/. Do not edit by hand. */
import { html } from 'lit';

import { UiIconArt } from '../ui-icons.types.js';

export const CornerTriangle = {
  50: html`
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 8 8">
      <path
        fill="var(--swc-icon-color, currentColor)"
        d="M8 4.501V7.25a.75.75 0 0 1-.75.75H4.501a.5.5 0 0 1-.354-.854l3-2.999A.5.5 0 0 1 8 4.501"
      />
    </svg>
  `,
  75: html`
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 10 10">
      <path
        fill="var(--swc-icon-color, currentColor)"
        d="M10 6.001V9.25a.75.75 0 0 1-.75.75H6.001a.5.5 0 0 1-.354-.854l3.5-3.499a.5.5 0 0 1 .853.354"
      />
    </svg>
  `,
  100: html`
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 10 10">
      <path
        fill="var(--swc-icon-color, currentColor)"
        d="M10 5.501V9.25a.75.75 0 0 1-.75.75H5.501a.5.5 0 0 1-.354-.854l4-3.999a.5.5 0 0 1 .853.354"
      />
    </svg>
  `,
  200: html`
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 12 12">
      <path
        fill="var(--swc-icon-color, currentColor)"
        d="M12 7.001v4.249a.75.75 0 0 1-.75.75H7.001a.5.5 0 0 1-.354-.854l4.5-4.499a.5.5 0 0 1 .853.354"
      />
    </svg>
  `,
  300: html`
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 14 14">
      <path
        fill="var(--swc-icon-color, currentColor)"
        d="M14 8.001v5.249a.75.75 0 0 1-.75.75H8.001a.5.5 0 0 1-.354-.854l5.5-5.499a.5.5 0 0 1 .853.354"
      />
    </svg>
  `,
} satisfies UiIconArt;
