/**
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
/* Generated by `yarn generate:ui-icons` from icon-source/ui/. Do not edit by hand. */
import { html } from 'lit';

import { UiIconArt } from '../ui-icons.types.js';

export const Cross = {
  50: html`
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 8 8">
      <path
        fill="var(--swc-icon-color, currentColor)"
        d="m4.885 4 2.002-2.002a.626.626 0 0 0-.885-.885L4 3.115 1.998 1.113a.626.626 0 0 0-.885.885L3.115 4 1.113 6.002a.63.63 0 0 0 0 .885.623.623 0 0 0 .885 0L4 4.885l2.002 2.002a.623.623 0 0 0 .885 0 .63.63 0 0 0 0-.885z"
      />
    </svg>
  `,
  75: html`
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 10 10">
      <path
        fill="var(--swc-icon-color, currentColor)"
        d="m5.885 5 2.307-2.308a.626.626 0 0 0-.885-.885L5 4.116 2.692 1.808a.626.626 0 0 0-.884.884L4.115 5 1.808 7.308a.63.63 0 0 0 0 .884.623.623 0 0 0 .884 0L5 5.885l2.308 2.307a.623.623 0 0 0 .884 0 .63.63 0 0 0 0-.884z"
      />
    </svg>
  `,
  100: html`
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 10 10">
      <path
        fill="var(--swc-icon-color, currentColor)"
        d="m6.06 5 2.595-2.595a.75.75 0 1 0-1.06-1.06L5 3.939 2.405 1.345a.75.75 0 1 0-1.06 1.06L3.939 5 1.345 7.595a.75.75 0 1 0 1.06 1.06L5 6.061l2.595 2.594a.747.747 0 0 0 1.06 0 .75.75 0 0 0 0-1.06z"
      />
    </svg>
  `,
  200: html`
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 12 12">
      <path
        fill="var(--swc-icon-color, currentColor)"
        d="m7.166 6 3.542-3.542a.824.824 0 1 0-1.166-1.166L6 4.834 2.458 1.292a.824.824 0 1 0-1.166 1.166L4.834 6 1.292 9.542a.824.824 0 1 0 1.166 1.166L6 7.166l3.542 3.542a.82.82 0 0 0 1.166 0 .824.824 0 0 0 0-1.166z"
      />
    </svg>
  `,
  300: html`
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 14 14">
      <path
        fill="var(--swc-icon-color, currentColor)"
        d="m8.414 7 3.793-3.793a1 1 0 1 0-1.414-1.414L7 5.586 3.207 1.793a1 1 0 1 0-1.414 1.414L5.586 7l-3.793 3.793a1 1 0 1 0 1.414 1.414L7 8.414l3.793 3.793a.997.997 0 0 0 1.414 0 1 1 0 0 0 0-1.414z"
      />
    </svg>
  `,
} satisfies UiIconArt;
