/**
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
/* Generated by `yarn generate:ui-icons` from icon-source/ui/. Do not edit by hand. */
import { html } from 'lit';

import { UiIconArt } from '../ui-icons.types.js';

export const LinkOut = {
  50: html`
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 8 8">
      <path
        fill="var(--swc-icon-color, currentColor)"
        d="M7.375 0h-4a.626.626 0 0 0 0 1.25h2.49L1.558 5.558a.63.63 0 0 0 0 .884.623.623 0 0 0 .884 0L6.75 2.135v2.49a.626.626 0 0 0 1.25 0v-4A.626.626 0 0 0 7.375 0"
      />
    </svg>
  `,
  75: html`
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 10 10">
      <path
        fill="var(--swc-icon-color, currentColor)"
        d="M8.375 1H4.073a.626.626 0 0 0 0 1.25h2.792L1.558 7.558a.63.63 0 0 0 0 .884.623.623 0 0 0 .884 0L7.75 3.135v2.792a.626.626 0 0 0 1.25 0V1.625A.626.626 0 0 0 8.375 1"
      />
    </svg>
  `,
  100: html`
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 10 10">
      <path
        fill="var(--swc-icon-color, currentColor)"
        d="M9.25 0H4.625a.75.75 0 0 0 0 1.5h2.814L1.47 7.47a.75.75 0 1 0 1.06 1.06L8.5 2.56v2.815a.75.75 0 0 0 1.5 0V.75A.75.75 0 0 0 9.25 0"
      />
    </svg>
  `,
  200: html`
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 12 12">
      <path
        fill="var(--swc-icon-color, currentColor)"
        d="M10.175 1h-5.5a.825.825 0 1 0 0 1.65h3.509L1.417 9.417a.824.824 0 1 0 1.166 1.166L9.35 3.816v3.51a.825.825 0 1 0 1.65 0v-5.5A.825.825 0 0 0 10.175 1"
      />
    </svg>
  `,
  300: html`
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 14 14">
      <path
        fill="var(--swc-icon-color, currentColor)"
        d="M12 1H5a1 1 0 1 0 0 2h4.586l-8.293 8.293a1 1 0 1 0 1.414 1.414L11 4.414V9a1 1 0 1 0 2 0V2a1 1 0 0 0-1-1"
      />
    </svg>
  `,
} satisfies UiIconArt;
