name: 'Setup AzCopy'
description: 'Downloads and installs AzCopy for use in workflows'

runs:
    using: composite
    steps:
        - name: Install AzCopy
          shell: bash
          run: |
              # Download and install AzCopy
              wget -O azcopy.tar.gz https://github.com/Azure/azure-storage-azcopy/releases/download/v10.29.1/azcopy_linux_amd64_10.29.1.tar.gz
              tar -xf azcopy.tar.gz --strip-components=1
              sudo mv azcopy /usr/local/bin/
              azcopy --version
