"use strict";var p=Object.defineProperty;var h=Object.getOwnPropertyDescriptor;var s=(i,a,t,o)=>{for(var e=o>1?void 0:o?h(a,t):a,l=i.length-1,r;l>=0;l--)(r=i[l])&&(e=(o?r(a,t,e):r(e))||e);return o&&e&&p(a,t,e),e};import{ResizeController as u}from"@lit-labs/observers/resize-controller.js";import{html as S,SizedMixin as b,SpectrumElement as d}from"@spectrum-web-components/base";import{property as c,query as v,queryAssignedElements as f,state as m}from"@spectrum-web-components/base/src/decorators.js";import{classMap as n}from"@spectrum-web-components/base/src/directives.js";import C from"@spectrum-web-components/icon/src/spectrum-icon-chevron.css.js";import"@spectrum-web-components/action-button/sp-action-button.js";import"@spectrum-web-components/icons-ui/icons/sp-icon-chevron100.js";import g from"./tabs-overflow.css.js";import y from"./tabs-sizes.css.js";export class TabsOverflow extends b(d){constructor(){super();this.compact=!1;this.labelPrevious="Scroll to previous tabs";this.labelNext="Scroll to next tabs";this.overflowState={canScrollLeft:!1,canScrollRight:!1};this.scrollFactor=.5;this.resizeController=new u(this,{target:this,callback:()=>{this._updateScrollState()}})}static get styles(){return[g,y,C]}get scrollContent(){return this.tabs}firstUpdated(t){super.firstUpdated(t);const[o]=this.scrollContent;o&&(o.enableTabsScroll=!0),this.resizeController.observe(this.overflowContainer)}async _handleSlotChange(){const[t]=this.scrollContent;await(t==null?void 0:t.updateComplete),this._updateScrollState()}_updateScrollState(){const{scrollContent:t,overflowState:o}=this;if(t){const[e]=this.scrollContent,{canScrollLeft:l,canScrollRight:r}=(e==null?void 0:e.scrollState)||{canScrollLeft:!1,canScrollRight:!1};this.overflowState={...o,canScrollLeft:l,canScrollRight:r}}}_handleScrollClick(t){const o=t.currentTarget,[e]=this.scrollContent,l=e.clientWidth*this.scrollFactor,r=o.classList.contains("left-scroll")?-l:l;e.scrollTabs(r,"smooth"),this._updateScrollState()}render(){const{canScrollRight:t,canScrollLeft:o}=this.overflowState,e=this.labelPrevious,l=this.labelNext;return S`
      <div
        class=${n({"tabs-overflow-container":!0,"left-shadow":o,"right-shadow":t})}
      >
        <sp-action-button
          class=${n({"left-scroll":!0,show:o})}
          aria-label=${e}
          quiet
          tabindex="-1"
          @click=${this._handleScrollClick}
        >
          <sp-icon-chevron100
            slot="icon"
            class="spectrum-UIIcon-ChevronLeft300"
          ></sp-icon-chevron100>
        </sp-action-button>
        <sp-action-button
          class=${n({"right-scroll":!0,show:t})}
          aria-label=${l}
          quiet
          tabindex="-1"
          @click=${this._handleScrollClick}
        >
          <sp-icon-chevron100
            slot="icon"
            class="spectrum-UIIcon-ChevronRight300"
          ></sp-icon-chevron100>
        </sp-action-button>
        <slot
          @slotchange=${this._handleSlotChange}
          @sp-tabs-scroll=${this._updateScrollState}
        ></slot>
      </div>
    `}}s([c({type:Boolean,reflect:!0})],TabsOverflow.prototype,"compact",2),s([c({type:String,attribute:"label-previous"})],TabsOverflow.prototype,"labelPrevious",2),s([c({type:String,attribute:"label-next"})],TabsOverflow.prototype,"labelNext",2),s([m()],TabsOverflow.prototype,"overflowState",2),s([f({selector:"sp-tabs",flatten:!0})],TabsOverflow.prototype,"tabs",2),s([v(".tabs-overflow-container")],TabsOverflow.prototype,"overflowContainer",2);
//# sourceMappingURL=TabsOverflow.js.map
