/**
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
/* Generated by `yarn generate:workflow-icons` from icon-source/workflow/. Do not edit by hand. */

/**
 * The 3DAsset workflow icon as a framework-agnostic SVG string. Usable via `innerHTML`,
 * React `dangerouslySetInnerHTML`, Vue `v-html`, or Lit `unsafeSVG`. Color follows
 * `var(--swc-icon-color, currentColor)`.
 */
export function Icon_3DAsset(): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path fill="var(--swc-icon-color, currentColor)" d="m17.771 5.082-2.789-1.61a1.76 1.76 0 0 0-1.721-.017L10 5.253 6.737 3.455a1.76 1.76 0 0 0-1.72.018l-2.79 1.609A2.47 2.47 0 0 0 1 7.21v4.556c0 .875.47 1.69 1.229 2.127L8.77 17.67a2.46 2.46 0 0 0 2.458 0l6.542-3.778A2.46 2.46 0 0 0 19 11.766V7.21c0-.874-.47-1.69-1.229-2.128m-12.003-.31a.25.25 0 0 1 .245-.002l3.625 1.997a.76.76 0 0 0 .724 0l3.623-1.998.001-.001a.25.25 0 0 1 .244.002l2.561 1.478-6.79 3.746L3.205 6.25zm-2.79 7.822a.96.96 0 0 1-.478-.828v-4.19l6.75 3.718v4.921zm14.043 0-6.271 3.621v-4.922L17.5 7.57v4.196a.96.96 0 0 1-.479.828"/></svg>`;
}
