/**
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
/* Generated by `yarn generate:workflow-icons` from icon-source/workflow/. Do not edit by hand. */

/**
 * The AddContent workflow icon as a framework-agnostic SVG string. Usable via `innerHTML`,
 * React `dangerouslySetInnerHTML`, Vue `v-html`, or Lit `unsafeSVG`. Color follows
 * `var(--swc-icon-color, currentColor)`.
 */
export function Icon_AddContent(): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path fill="var(--swc-icon-color, currentColor)" d="M9.352 17.25a.75.75 0 0 1-.75.75H2.25C1.01 18 0 16.99 0 15.75v-5.5C0 9.01 1.01 8 2.25 8h10.116a.75.75 0 0 1 0 1.5H2.25a.75.75 0 0 0-.75.75v3.837l2.157-2.156a1.97 1.97 0 0 1 2.781 0l2.423 2.546a.624.624 0 1 1-.905.861l-2.413-2.535a.716.716 0 0 0-1.002.011l-3.023 3.023c.045.371.35.663.732.663h6.352a.75.75 0 0 1 .75.75M5.422 6.795a.75.75 0 0 0 .509-.93.25.25 0 0 1 .102-.28l5-3.315a.747.747 0 0 1 1.04.211l4.292 6.483a.75.75 0 0 0 1.25-.828l-4.292-6.483a2.24 2.24 0 0 0-1.429-.964 2.24 2.24 0 0 0-1.69.33l-5 3.317a1.74 1.74 0 0 0-.713 1.95.75.75 0 0 0 .93.51m3.864 3.896a1.042 1.042 0 1 0 0 2.083 1.042 1.042 0 0 0 0-2.083"/><path fill="var(--swc-icon-color, currentColor)" d="M15 10.5a4.5 4.5 0 1 0 0 9 4.5 4.5 0 0 0 0-9m2.5 5.125h-1.875V17.5a.625.625 0 1 1-1.25 0v-1.875H12.5a.625.625 0 1 1 0-1.25h1.875V12.5a.625.625 0 1 1 1.25 0v1.875H17.5a.625.625 0 1 1 0 1.25"/></svg>`;
}
