/**
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
/* Generated by `yarn generate:workflow-icons` from icon-source/workflow/. Do not edit by hand. */

/**
 * The AnimationNo workflow icon as a framework-agnostic SVG string. Usable via `innerHTML`,
 * React `dangerouslySetInnerHTML`, Vue `v-html`, or Lit `unsafeSVG`. Color follows
 * `var(--swc-icon-color, currentColor)`.
 */
export function Icon_AnimationNo(): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path fill="var(--swc-icon-color, currentColor)" d="M6.5 19A5.507 5.507 0 0 1 1 13.5a5.49 5.49 0 0 1 3.8-5.232.75.75 0 1 1 .464 1.427A3.99 3.99 0 0 0 2.5 13.5c0 2.206 1.794 4 4 4a3.99 3.99 0 0 0 3.812-2.78.75.75 0 0 1 1.427.458A5.48 5.48 0 0 1 6.5 19m8.717-6.95a.75.75 0 0 1-.507-1.303c.51-.466.79-1.103.79-1.793 0-1.353-1.1-2.454-2.454-2.454-.687 0-1.324.281-1.796.791a.751.751 0 0 1-1.102-1.02A3.97 3.97 0 0 1 13.046 5 3.96 3.96 0 0 1 17 8.954a3.94 3.94 0 0 1-1.276 2.9.75.75 0 0 1-.507.197m2.668-6.219a.75.75 0 0 1-.621-1.169 1.388 1.388 0 0 0-1.152-2.16c-.5 0-.964.28-1.21.727a.75.75 0 0 1-1.314-.722 2.88 2.88 0 0 1 2.523-1.504A2.89 2.89 0 0 1 18.508 5.5a.75.75 0 0 1-.623.331M18.25 19a.75.75 0 0 1-.53-.22L1.22 2.28a.75.75 0 1 1 1.06-1.06l16.5 16.5a.75.75 0 0 1-.53 1.28"/></svg>`;
}
