/**
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
/* Generated by `yarn generate:workflow-icons` from icon-source/workflow/. Do not edit by hand. */

/**
 * The Brand workflow icon as a framework-agnostic SVG string. Usable via `innerHTML`,
 * React `dangerouslySetInnerHTML`, Vue `v-html`, or Lit `unsafeSVG`. Color follows
 * `var(--swc-icon-color, currentColor)`.
 */
export function Icon_Brand(): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path fill="var(--swc-icon-color, currentColor)" d="M10.007 19q-.126 0-.253-.004A8.186 8.186 0 0 1 2 10.685V3.25C2 2.01 3.01 1 4.25 1h11.5C16.99 1 18 2.01 18 3.25l-.003 7.99a7.96 7.96 0 0 1-2.516 5.587A7.95 7.95 0 0 1 10.007 19M4.25 2.5a.75.75 0 0 0-.75.75v7.445a6.69 6.69 0 0 0 6.32 6.802c1.706.052 3.367-.573 4.632-1.763s1.991-2.8 2.044-4.537L16.5 11V3.25a.75.75 0 0 0-.75-.75z"/><path fill="var(--swc-icon-color, currentColor)" d="M14.25 12h-5.5a.75.75 0 0 1-.658-1.11l2.75-5.038a.75.75 0 0 1 1.316 0l2.75 5.039A.748.748 0 0 1 14.25 12m-4.236-1.5h2.972l-1.485-2.724zM5.749 12a.75.75 0 0 1-.657-1.11l1.981-3.628a.749.749 0 1 1 1.317.718l-1.982 3.63a.75.75 0 0 1-.659.39"/></svg>`;
}
