/**
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
/* Generated by `yarn generate:workflow-icons` from icon-source/workflow/. Do not edit by hand. */

/**
 * The BrightnessContrast workflow icon as a framework-agnostic SVG string. Usable via `innerHTML`,
 * React `dangerouslySetInnerHTML`, Vue `v-html`, or Lit `unsafeSVG`. Color follows
 * `var(--swc-icon-color, currentColor)`.
 */
export function Icon_BrightnessContrast(): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path fill="var(--swc-icon-color, currentColor)" d="M10 3.013a.75.75 0 0 1-.75-.75V1.25a.75.75 0 0 1 1.5 0v1.013a.75.75 0 0 1-.75.75M10 19.5a.75.75 0 0 1-.75-.75v-1a.75.75 0 0 1 1.5 0v1a.75.75 0 0 1-.75.75m8.75-8.75h-.999a.75.75 0 0 1 0-1.5h.999a.75.75 0 0 1 0 1.5m-16.505 0H1.25a.75.75 0 0 1 0-1.5h.995a.75.75 0 0 1 0 1.5M4.52 5.27a.75.75 0 0 1-.53-.22l-.708-.707a.75.75 0 1 1 1.06-1.06l.708.706a.75.75 0 0 1-.53 1.28m11.668 11.669a.75.75 0 0 1-.53-.22l-.706-.705a.75.75 0 1 1 1.06-1.06l.706.704a.75.75 0 0 1-.53 1.28m-.711-11.668a.75.75 0 0 1-.529-1.283l.711-.706a.75.75 0 1 1 1.057 1.065l-.711.706a.75.75 0 0 1-.528.218M3.813 16.938a.75.75 0 0 1-.53-1.281l.707-.706a.75.75 0 1 1 1.059 1.063l-.707.705a.75.75 0 0 1-.53.218M10 4c-3.308 0-6 2.692-6 6s2.692 6 6 6 6-2.692 6-6-2.692-6-6-6m-4.5 6c0-2.481 2.019-4.5 4.5-4.5v9A4.505 4.505 0 0 1 5.5 10"/></svg>`;
}
