/**
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
/* Generated by `yarn generate:workflow-icons` from icon-source/workflow/. Do not edit by hand. */

/**
 * The Calendar workflow icon as a framework-agnostic SVG string. Usable via `innerHTML`,
 * React `dangerouslySetInnerHTML`, Vue `v-html`, or Lit `unsafeSVG`. Color follows
 * `var(--swc-icon-color, currentColor)`.
 */
export function Icon_Calendar(): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path fill="var(--swc-icon-color, currentColor)" d="M15.75 3h-2V2a.75.75 0 0 0-1.5 0v1h-4.5V2a.75.75 0 0 0-1.5 0v1h-2C3.01 3 2 4.01 2 5.25v10.5C2 16.99 3.01 18 4.25 18h11.5c1.24 0 2.25-1.01 2.25-2.25V5.25C18 4.01 16.99 3 15.75 3M4.25 4.5h2V5a.75.75 0 0 0 1.5 0v-.5h4.5V5a.75.75 0 0 0 1.5 0v-.5h2a.75.75 0 0 1 .75.75V7h-13V5.25a.75.75 0 0 1 .75-.75m11.5 12H4.25a.75.75 0 0 1-.75-.75V8.5h13v7.25a.75.75 0 0 1-.75.75"/><rect width="2" height="2" x="5" y="10" fill="var(--swc-icon-color, currentColor)" rx="1" ry="1"/><rect width="2" height="2" x="9" y="10" fill="var(--swc-icon-color, currentColor)" rx="1" ry="1"/><rect width="2" height="2" x="13" y="10" fill="var(--swc-icon-color, currentColor)" rx="1" ry="1"/><rect width="2" height="2" x="5" y="13" fill="var(--swc-icon-color, currentColor)" rx="1" ry="1"/><rect width="2" height="2" x="9" y="13" fill="var(--swc-icon-color, currentColor)" rx="1" ry="1"/><rect width="2" height="2" x="13" y="13" fill="var(--swc-icon-color, currentColor)" rx="1" ry="1"/></svg>`;
}
