/**
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
/* Generated by `yarn generate:workflow-icons` from icon-source/workflow/. Do not edit by hand. */

/**
 * The CalendarEdit workflow icon as a framework-agnostic SVG string. Usable via `innerHTML`,
 * React `dangerouslySetInnerHTML`, Vue `v-html`, or Lit `unsafeSVG`. Color follows
 * `var(--swc-icon-color, currentColor)`.
 */
export function Icon_CalendarEdit(): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path fill="var(--swc-icon-color, currentColor)" d="M18.562 10.068c-.966-.791-2.453-.688-3.38.24L11 14.49a2.1 2.1 0 0 0-.533.89l-.954 3.16a.75.75 0 0 0 .935.935l3.158-.953c.336-.102.644-.286.89-.533l4.253-4.253a2.475 2.475 0 0 0-.187-3.668m-5.389 7.018-1.82.549.55-1.821c.018-.058.059-.102.091-.152l1.332 1.332c-.05.033-.095.074-.153.092m4.515-4.41-3.456 3.456-1.376-1.376 3.388-3.388c.221-.221.512-.337.793-.337.21 0 .413.066.576.199.218.178.346.43.36.708a.96.96 0 0 1-.285.738"/><path fill="var(--swc-icon-color, currentColor)" d="M7.894 16.521H4.25a.75.75 0 0 1-.75-.75v-7.25h13.75a.75.75 0 0 0 .75-.75v-2.5c0-1.24-1.01-2.25-2.25-2.25h-2v-1a.75.75 0 0 0-1.5 0v1h-4.5v-1a.75.75 0 0 0-1.5 0v1h-2C3.01 3.021 2 4.031 2 5.271v10.5c0 1.24 1.01 2.25 2.25 2.25h3.644a.75.75 0 0 0 0-1.5m-3.644-12h2v.5a.75.75 0 0 0 1.5 0v-.5h4.5v.5a.75.75 0 0 0 1.5 0v-.5h2a.75.75 0 0 1 .75.75v1.75h-13v-1.75c0-.413.337-.75.75-.75"/></svg>`;
}
