/**
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
/* Generated by `yarn generate:workflow-icons` from icon-source/workflow/. Do not edit by hand. */

/**
 * The ChartTrend workflow icon as a framework-agnostic SVG string. Usable via `innerHTML`,
 * React `dangerouslySetInnerHTML`, Vue `v-html`, or Lit `unsafeSVG`. Color follows
 * `var(--swc-icon-color, currentColor)`.
 */
export function Icon_ChartTrend(): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path fill="var(--swc-icon-color, currentColor)" d="M3 17.75a.75.75 0 0 1-.603-1.195l2.297-3.114a.75.75 0 0 1 1.022-.176l2.05 1.379 1.621-6.985a.75.75 0 0 1 1.377-.21l1.932 3.276 3.62-8.034a.75.75 0 1 1 1.368.618l-4.215 9.352a.75.75 0 0 1-.643.44.73.73 0 0 1-.687-.368l-1.715-2.908-1.444 6.219a.75.75 0 0 1-1.15.452L5.476 14.91l-1.871 2.535A.75.75 0 0 1 3 17.75"/></svg>`;
}
