/**
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
/* Generated by `yarn generate:workflow-icons` from icon-source/workflow/. Do not edit by hand. */

/**
 * The ChevronDoubleLeft workflow icon as a framework-agnostic SVG string. Usable via `innerHTML`,
 * React `dangerouslySetInnerHTML`, Vue `v-html`, or Lit `unsafeSVG`. Color follows
 * `var(--swc-icon-color, currentColor)`.
 */
export function Icon_ChevronDoubleLeft(): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path fill="var(--swc-icon-color, currentColor)" d="M9.862 16.455a.75.75 0 0 1-.54-.23L3.835 10.52a.747.747 0 0 1 0-1.039l5.5-5.716a.749.749 0 1 1 1.08 1.039l-4.999 5.197 4.986 5.184a.748.748 0 0 1-.54 1.27"/><path fill="var(--swc-icon-color, currentColor)" d="M15.612 16.455a.75.75 0 0 1-.54-.23L9.585 10.52a.747.747 0 0 1 0-1.039l5.5-5.716a.749.749 0 1 1 1.08 1.039l-4.999 5.197 4.986 5.184a.748.748 0 0 1-.54 1.27"/></svg>`;
}
