/**
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
/* Generated by `yarn generate:workflow-icons` from icon-source/workflow/. Do not edit by hand. */

/**
 * The ChevronDoubleRight workflow icon as a framework-agnostic SVG string. Usable via `innerHTML`,
 * React `dangerouslySetInnerHTML`, Vue `v-html`, or Lit `unsafeSVG`. Color follows
 * `var(--swc-icon-color, currentColor)`.
 */
export function Icon_ChevronDoubleRight(): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path fill="var(--swc-icon-color, currentColor)" d="M9.618 16.245a.75.75 0 0 1-.02-1.06l4.986-5.183-5-5.197a.749.749 0 1 1 1.08-1.04l5.5 5.717c.281.29.281.75 0 1.04l-5.486 5.703a.746.746 0 0 1-1.06.02"/><path fill="var(--swc-icon-color, currentColor)" d="M3.868 16.245a.75.75 0 0 1-.02-1.06l4.986-5.183-5-5.197a.749.749 0 1 1 1.08-1.04l5.5 5.717c.281.29.281.75 0 1.04l-5.486 5.703a.746.746 0 0 1-1.06.02"/></svg>`;
}
