/**
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
/* Generated by `yarn generate:workflow-icons` from icon-source/workflow/. Do not edit by hand. */

/**
 * The ClockPending workflow icon as a framework-agnostic SVG string. Usable via `innerHTML`,
 * React `dangerouslySetInnerHTML`, Vue `v-html`, or Lit `unsafeSVG`. Color follows
 * `var(--swc-icon-color, currentColor)`.
 */
export function Icon_ClockPending(): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path fill="var(--swc-icon-color, currentColor)" d="M13.22 12.657a.75.75 0 0 1-.38-.103l-3.22-1.896a.75.75 0 0 1-.37-.646v-5a.75.75 0 0 1 1.5 0v4.571l2.852 1.678a.751.751 0 0 1-.382 1.396"/><path fill="var(--swc-icon-color, currentColor)" d="M10 18.771c-4.825 0-8.75-3.924-8.75-8.75A8.74 8.74 0 0 1 6.594 1.96a.75.75 0 1 1 .584 1.38 7.24 7.24 0 0 0-4.428 6.682 7.26 7.26 0 0 0 7.25 7.25 7.25 7.25 0 0 0 4.703-1.732.75.75 0 0 1 1.058.084.75.75 0 0 1-.084 1.057A8.75 8.75 0 0 1 10 18.77m.251-15.945h-.03L10 2.821a.8.8 0 0 1 0-1.6l.278.005a.8.8 0 0 1-.027 1.6m3.138.747a.8.8 0 0 1-.346-.079l-.198-.09a.8.8 0 1 1 .633-1.468q.13.056.258.117a.8.8 0 0 1-.347 1.52m2.587 1.931a.8.8 0 0 1-.603-.274l-.145-.159a.8.8 0 0 1 1.158-1.103q.098.103.192.21a.8.8 0 0 1-.602 1.326m1.616 2.791a.8.8 0 0 1-.759-.547l-.075-.217a.8.8 0 1 1 1.504-.545l.089.256a.8.8 0 0 1-.76 1.053m.381 3.205-.067-.003a.8.8 0 0 1-.731-.862l.015-.232c.026-.441.373-.787.846-.752a.8.8 0 0 1 .752.846l-.02.269a.8.8 0 0 1-.795.734"/><path fill="var(--swc-icon-color, currentColor)" d="m17.972 11.5-.067-.003a.8.8 0 0 1-.731-.862l.015-.232c.026-.441.373-.787.846-.752a.8.8 0 0 1 .752.846l-.02.269a.8.8 0 0 1-.795.734m-1.32 2.904-.057-.035a.8.8 0 0 1-.21-1.112l.129-.193c.24-.371.712-.5 1.106-.236a.8.8 0 0 1 .236 1.107l-.15.224a.8.8 0 0 1-1.054.245"/></svg>`;
}
