/**
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
/* Generated by `yarn generate:workflow-icons` from icon-source/workflow/. Do not edit by hand. */

/**
 * The ColorHarmony workflow icon as a framework-agnostic SVG string. Usable via `innerHTML`,
 * React `dangerouslySetInnerHTML`, Vue `v-html`, or Lit `unsafeSVG`. Color follows
 * `var(--swc-icon-color, currentColor)`.
 */
export function Icon_ColorHarmony(): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path fill="var(--swc-icon-color, currentColor)" d="M15.75 2H4.25C3.01 2 2 3.01 2 4.25v11.5C2 16.99 3.01 18 4.25 18h11.5c1.24 0 2.25-1.01 2.25-2.25V4.25C18 3.01 16.99 2 15.75 2m0 1.5a.75.75 0 0 1 .75.75v5h-5.75V3.5zM3.5 4.25a.75.75 0 0 1 .75-.75h5v5.75H3.5zm.75 12.25a.75.75 0 0 1-.75-.75v-5h5.75v5.75zm12.25-.75a.75.75 0 0 1-.75.75h-5v-5.75h5.75z"/><path fill="var(--swc-icon-color, currentColor)" d="M10.069 3.114h6.959v6.698h-6.959z" opacity=".5"/><path fill="var(--swc-icon-color, currentColor)" d="M10.069 10.114h6.959v6.698h-6.959z" opacity=".12"/><path fill="var(--swc-icon-color, currentColor)" d="M3.069 10.114h6.959v6.698H3.069z" opacity=".3"/></svg>`;
}
