/**
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
/* Generated by `yarn generate:workflow-icons` from icon-source/workflow/. Do not edit by hand. */

/**
 * The CommentHide workflow icon as a framework-agnostic SVG string. Usable via `innerHTML`,
 * React `dangerouslySetInnerHTML`, Vue `v-html`, or Lit `unsafeSVG`. Color follows
 * `var(--swc-icon-color, currentColor)`.
 */
export function Icon_CommentHide(): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" data-name="ICONS" viewBox="0 0 20 20"><path fill="var(--swc-icon-color, currentColor)" d="M14.294 16.661h-.044c-2.578-.15-5-2.459-5-3.767 0-.344.174-.705.549-1.134a.75.75 0 0 1 1.13.986 2 2 0 0 0-.162.21c.197.552 1.758 2.103 3.57 2.206a.75.75 0 0 1-.043 1.5m3.985-1.493c.74-.625 1.471-1.504 1.471-2.275 0-1.311-2.43-3.98-5.26-3.98-.692.01-1.381.17-2.013.454l-.947-.947a.75.75 0 1 0-1.06 1.06l7.299 7.3a.75.75 0 0 0 1.06 0 .75.75 0 0 0 0-1.061zM14.5 10.414c2.049 0 3.67 2.004 3.751 2.457-.028.168-.383.696-1.043 1.227l-3.56-3.56c.28-.074.567-.12.852-.124"/><path fill="var(--swc-icon-color, currentColor)" d="M6.25 19q-.151 0-.293-.06a.75.75 0 0 1-.457-.69V15h-.75A3.754 3.754 0 0 1 1 11.25v-5.5A3.754 3.754 0 0 1 4.75 2h10.5A3.754 3.754 0 0 1 19 5.75v2.042a.75.75 0 0 1-1.5 0V5.75c0-1.24-1.01-2.25-2.25-2.25H4.75C3.51 3.5 2.5 4.51 2.5 5.75v5.5c0 1.24 1.01 2.25 2.25 2.25h1.5a.75.75 0 0 1 .75.75v2.236l.895-.861a.75.75 0 1 1 1.04 1.08L6.77 18.79a.75.75 0 0 1-.52.21"/></svg>`;
}
