/**
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
/* Generated by `yarn generate:workflow-icons` from icon-source/workflow/. Do not edit by hand. */

/**
 * The Community workflow icon as a framework-agnostic SVG string. Usable via `innerHTML`,
 * React `dangerouslySetInnerHTML`, Vue `v-html`, or Lit `unsafeSVG`. Color follows
 * `var(--swc-icon-color, currentColor)`.
 */
export function Icon_Community(): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" data-name="ICONS" viewBox="0 0 20 20"><path fill="var(--swc-icon-color, currentColor)" d="M10.059 11.998c-2.09 0-3.788-1.784-3.788-3.977s1.699-3.979 3.788-3.979 3.788 1.785 3.788 3.979-1.7 3.977-3.788 3.977m0-6.456c-1.262 0-2.288 1.112-2.288 2.479s1.026 2.477 2.288 2.477 2.288-1.111 2.288-2.477-1.027-2.479-2.288-2.479M4.553 17.998a.75.75 0 0 1-.747-.831C4.084 14.621 6.77 12.7 10.06 12.7c3.264 0 6.011 1.966 6.253 4.476a.75.75 0 1 1-1.494.144c-.165-1.72-2.3-3.12-4.76-3.12-2.479 0-4.57 1.374-4.76 3.13a.75.75 0 0 1-.745.668M.75 15a.75.75 0 0 1-.634-1.15c.856-1.358 2.44-2.312 4.345-2.615a.744.744 0 0 1 .859.622.75.75 0 0 1-.623.859c-1.457.232-2.695.955-3.313 1.934A.75.75 0 0 1 .75 15m3.437-5a1 1 0 0 1-.16-.018c-1.748-.378-3.016-2.017-3.016-3.894 0-2.193 1.7-3.978 3.787-3.978a3.65 3.65 0 0 1 1.94.56.75.75 0 0 1-.795 1.271 2.15 2.15 0 0 0-1.145-.33c-1.26 0-2.287 1.11-2.287 2.477 0 1.177.771 2.198 1.834 2.43A.75.75 0 0 1 4.187 10m15.063 5a.75.75 0 0 1-.634-.35c-.618-.98-1.856-1.702-3.313-1.934a.75.75 0 1 1 .236-1.48c1.905.302 3.49 1.256 4.345 2.614A.75.75 0 0 1 19.25 15m-3.437-5a.75.75 0 0 1-.158-1.482c1.063-.232 1.834-1.253 1.834-2.43 0-1.366-1.026-2.478-2.287-2.478-.403 0-.799.115-1.145.331a.75.75 0 0 1-.796-1.271 3.65 3.65 0 0 1 1.94-.56c2.089 0 3.788 1.785 3.788 3.978 0 1.877-1.268 3.516-3.016 3.894a1 1 0 0 1-.16.018"/></svg>`;
}
