/**
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
/* Generated by `yarn generate:workflow-icons` from icon-source/workflow/. Do not edit by hand. */

/**
 * The CornerRadiusBottomLeft workflow icon as a framework-agnostic SVG string. Usable via `innerHTML`,
 * React `dangerouslySetInnerHTML`, Vue `v-html`, or Lit `unsafeSVG`. Color follows
 * `var(--swc-icon-color, currentColor)`.
 */
export function Icon_CornerRadiusBottomLeft(): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path fill="var(--swc-icon-color, currentColor)" d="M18.25 14.25V12a.75.75 0 0 0-1.5 0v2.25c0 1.24-1.01 2.25-2.25 2.25h-2.25a.75.75 0 0 0 0 1.5h2.25a3.754 3.754 0 0 0 3.75-3.75m0-6.25V5.75A3.754 3.754 0 0 0 14.5 2h-2.25a.75.75 0 0 0 0 1.5h2.25c1.24 0 2.25 1.01 2.25 2.25V8a.75.75 0 0 0 1.5 0M3.75 8V5.75C3.75 4.51 4.76 3.5 6 3.5h2.25a.75.75 0 0 0 0-1.5H6a3.754 3.754 0 0 0-3.75 3.75V8a.75.75 0 0 0 1.5 0" opacity=".35"/><path fill="var(--swc-icon-color, currentColor)" d="M8.25 18H6a3.754 3.754 0 0 1-3.75-3.75V12a.75.75 0 0 1 1.5 0v2.25c0 1.24 1.01 2.25 2.25 2.25h2.25a.75.75 0 0 1 0 1.5"/></svg>`;
}
