/**
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
/* Generated by `yarn generate:workflow-icons` from icon-source/workflow/. Do not edit by hand. */

/**
 * The CropRotate workflow icon as a framework-agnostic SVG string. Usable via `innerHTML`,
 * React `dangerouslySetInnerHTML`, Vue `v-html`, or Lit `unsafeSVG`. Color follows
 * `var(--swc-icon-color, currentColor)`.
 */
export function Icon_CropRotate(): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path fill="var(--swc-icon-color, currentColor)" d="M13.25 11.191a.75.75 0 0 1-.75-.75V8.25a.75.75 0 0 0-.75-.75H9.513a.75.75 0 0 1 0-1.5h2.237C12.99 6 14 7.01 14 8.25v2.191a.75.75 0 0 1-.75.75"/><path fill="var(--swc-icon-color, currentColor)" d="M15.602 12.5H8.25a.75.75 0 0 1-.75-.75V4.398a.75.75 0 0 0-1.5 0V6H4.398a.75.75 0 0 0 0 1.5H6v4.25C6 12.99 7.01 14 8.25 14h4.25v1.623a.75.75 0 0 0 1.5 0V14h1.602a.75.75 0 0 0 0-1.5m-.937-10.25h-.032l.557-.558a.626.626 0 0 0-.883-.884l-1.75 1.75a.626.626 0 0 0 0 .884l1.75 1.75a.62.62 0 0 0 .883 0 .626.626 0 0 0 0-.884l-.557-.558h.032a2.587 2.587 0 0 1 2.584 2.583.75.75 0 0 0 1.5 0 4.09 4.09 0 0 0-4.084-4.083M7.44 16.558l-1.75-1.75a.625.625 0 1 0-.884.884l.557.558h-.032a2.587 2.587 0 0 1-2.583-2.583.75.75 0 0 0-1.5 0A4.09 4.09 0 0 0 5.33 17.75h.032l-.557.558a.626.626 0 0 0 .883.884l1.75-1.75a.626.626 0 0 0 0-.884"/></svg>`;
}
