/**
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
/* Generated by `yarn generate:workflow-icons` from icon-source/workflow/. Do not edit by hand. */

/**
 * The CursorClick workflow icon as a framework-agnostic SVG string. Usable via `innerHTML`,
 * React `dangerouslySetInnerHTML`, Vue `v-html`, or Lit `unsafeSVG`. Color follows
 * `var(--swc-icon-color, currentColor)`.
 */
export function Icon_CursorClick(): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path fill="var(--swc-icon-color, currentColor)" d="M10.476 18.967A1.48 1.48 0 0 1 9 17.48V9.378c0-.6.358-1.14.913-1.372a1.48 1.48 0 0 1 1.616.31l5.524 5.42a1.48 1.48 0 0 1 .335 1.624c-.23.562-.77.925-1.377.925h-2.28a.72.72 0 0 0-.56.265l-1.584 1.929c-.322.324-.717.487-1.111.487m.003-9.58.021 8.098 1.513-1.886a2.22 2.22 0 0 1 1.718-.813h2.28zm.021-4.69V1.75a.75.75 0 0 0-1.5 0v2.946a.75.75 0 0 0 1.5 0m7 4.053a.75.75 0 0 0-.75-.75h-2a.75.75 0 0 0 0 1.5h2a.75.75 0 0 0 .75-.75m-10.91 0A.75.75 0 0 0 5.84 8H2.75a.75.75 0 0 0 0 1.5h3.09a.75.75 0 0 0 .75-.75m6.598-2.378L15.23 4.33a.75.75 0 1 0-1.06-1.06l-2.042 2.042a.75.75 0 1 0 1.06 1.06M5.33 14.23l2.08-2.079a.75.75 0 1 0-1.061-1.06l-2.08 2.079a.75.75 0 1 0 1.061 1.06m2.155-7.745a.75.75 0 0 0 0-1.06L5.33 3.27a.75.75 0 1 0-1.06 1.06l2.155 2.155a.747.747 0 0 0 1.06 0"/></svg>`;
}
