/**
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
/* Generated by `yarn generate:workflow-icons` from icon-source/workflow/. Do not edit by hand. */

/**
 * The Cut workflow icon as a framework-agnostic SVG string. Usable via `innerHTML`,
 * React `dangerouslySetInnerHTML`, Vue `v-html`, or Lit `unsafeSVG`. Color follows
 * `var(--swc-icon-color, currentColor)`.
 */
export function Icon_Cut(): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path fill="var(--swc-icon-color, currentColor)" d="M11.477 7.606a.75.75 0 0 1-.71-.991L12.5 1.52a.749.749 0 1 1 1.42.48l-1.733 5.097a.75.75 0 0 1-.71.508"/><path fill="var(--swc-icon-color, currentColor)" d="M19.12 6.718a.75.75 0 0 0-.952-.469l-7.29 2.48c-.332.112-.692.168-1.132.232-.652.095-1.463.406-2.31.863a3.13 3.13 0 0 0-.907-2.095 3.15 3.15 0 0 0-4.448 0 3.15 3.15 0 0 0 0 4.449 3.136 3.136 0 0 0 4.383.053c.017-.011.037-.016.055-.029 1.135-.872 2.228-1.415 2.98-1.644l-.271.907a3.5 3.5 0 0 1-.306.745c-.274.485-.605.983-.955 1.441-.011.015-.013.032-.023.046a3.145 3.145 0 0 0 .047 4.39c.613.614 1.42.92 2.225.92s1.61-.306 2.223-.92a3.15 3.15 0 0 0 0-4.447 3.13 3.13 0 0 0-2.106-.91c.125-.251.238-.52.332-.834l.51-1.7c.062-.018.123-.027.185-.048l7.29-2.48a.75.75 0 0 0 .47-.95m-15.978 4.4a1.647 1.647 0 0 1 1.164-2.81c.42 0 .841.16 1.163.482a1.647 1.647 0 0 1-2.327 2.327m8.237 5.91a1.65 1.65 0 0 1-2.327 0 1.647 1.647 0 0 1 0-2.328 1.65 1.65 0 0 1 2.327 0 1.647 1.647 0 0 1 0 2.327"/></svg>`;
}
