/**
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
/* Generated by `yarn generate:workflow-icons` from icon-source/workflow/. Do not edit by hand. */

/**
 * The Delete workflow icon as a framework-agnostic SVG string. Usable via `innerHTML`,
 * React `dangerouslySetInnerHTML`, Vue `v-html`, or Lit `unsafeSVG`. Color follows
 * `var(--swc-icon-color, currentColor)`.
 */
export function Icon_Delete(): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path fill="var(--swc-icon-color, currentColor)" d="M8.249 15.021a.75.75 0 0 1-.748-.72l-.25-6.5a.75.75 0 0 1 .72-.779H8c.4 0 .733.317.748.72l.25 6.5a.75.75 0 0 1-.72.778zm3.502 0h-.03a.75.75 0 0 1-.72-.779l.25-6.5a.75.75 0 0 1 .748-.72h.03a.75.75 0 0 1 .72.779l-.25 6.5a.75.75 0 0 1-.748.72"/><path fill="var(--swc-icon-color, currentColor)" d="M17 4h-3.5v-.75C13.5 2.01 12.49 1 11.25 1h-2.5C7.51 1 6.5 2.01 6.5 3.25V4H3a.75.75 0 0 0 0 1.5h.52l.422 10.342A2.243 2.243 0 0 0 6.19 18h7.62c1.211 0 2.2-.948 2.248-2.158L16.48 5.5H17A.75.75 0 0 0 17 4m-9-.75c0-.413.337-.75.75-.75h2.5c.413 0 .75.337.75.75V4H8zm6.56 12.531a.75.75 0 0 1-.75.719H6.19a.75.75 0 0 1-.75-.719L5.02 5.5h9.96z"/></svg>`;
}
