/**
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
/* Generated by `yarn generate:workflow-icons` from icon-source/workflow/. Do not edit by hand. */

/**
 * The DirectSelect workflow icon as a framework-agnostic SVG string. Usable via `innerHTML`,
 * React `dangerouslySetInnerHTML`, Vue `v-html`, or Lit `unsafeSVG`. Color follows
 * `var(--swc-icon-color, currentColor)`.
 */
export function Icon_DirectSelect(): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path fill="var(--swc-icon-color, currentColor)" d="M8.75 9.49c0-1.317.895-2.417 2.106-2.758a2.9 2.9 0 0 0-.256-1.115l3.038-2.569c.014.005.026.014.04.018a1.5 1.5 0 1 0-.96-1.891c-.08.243-.087.49-.045.725l-3.04 2.57a2.8 2.8 0 0 0-.731-.377 2.85 2.85 0 0 0-3.594 1.825 2.83 2.83 0 0 0 .137 2.094l-3.236 2.737-.013-.006a1.5 1.5 0 1 0 .96 1.892 1.5 1.5 0 0 0 .04-.756l3.228-2.73c.216.147.448.277.71.362a2.83 2.83 0 0 0 1.616.041zm2.876 9.465A1.62 1.62 0 0 1 10 17.33V9.65a1.62 1.62 0 0 1 1.001-1.5 1.62 1.62 0 0 1 1.77.35l5.25 5.234c.467.466.606 1.161.354 1.771s-.84 1.004-1.501 1.004h-2.098l-1.998 1.964a1.62 1.62 0 0 1-1.152.482m.003-9.431a.14.14 0 0 0-.052.011c-.077.032-.077.093-.077.115v7.68c0 .023 0 .083.077.115.078.033.12-.011.135-.027l1.91-1.928c.303-.306.724-.49 1.154-.49h2.098c.023 0 .083.009.115-.068s-.01-.119-.027-.135l-5.25-5.235a.11.11 0 0 0-.083-.038"/></svg>`;
}
