/**
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
/* Generated by `yarn generate:workflow-icons` from icon-source/workflow/. Do not edit by hand. */

/**
 * The Edit workflow icon as a framework-agnostic SVG string. Usable via `innerHTML`,
 * React `dangerouslySetInnerHTML`, Vue `v-html`, or Lit `unsafeSVG`. Color follows
 * `var(--swc-icon-color, currentColor)`.
 */
export function Icon_Edit(): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path fill="var(--swc-icon-color, currentColor)" d="M17.78 1.757c-1.27-1.041-3.225-.899-4.45.323L3.079 12.334c-.32.32-.559.717-.69 1.15l-1.384 4.584a.75.75 0 0 0 .935.935l4.582-1.384a2.74 2.74 0 0 0 1.151-.688L18.028 6.575a3.26 3.26 0 0 0 .948-2.46 3.27 3.27 0 0 0-1.195-2.358M2.846 17.163l.98-3.246a1.2 1.2 0 0 1 .113-.257l2.41 2.409a1.3 1.3 0 0 1-.259.114zm14.12-11.647-9.525 9.526-2.475-2.476 9.425-9.425a1.98 1.98 0 0 1 1.39-.586c.38 0 .752.119 1.05.362a1.754 1.754 0 0 1 .135 2.599"/></svg>`;
}
