/**
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
/* Generated by `yarn generate:workflow-icons` from icon-source/workflow/. Do not edit by hand. */

/**
 * The EditNo workflow icon as a framework-agnostic SVG string. Usable via `innerHTML`,
 * React `dangerouslySetInnerHTML`, Vue `v-html`, or Lit `unsafeSVG`. Color follows
 * `var(--swc-icon-color, currentColor)`.
 */
export function Icon_EditNo(): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path fill="var(--swc-icon-color, currentColor)" d="M18.25 19.023a.75.75 0 0 1-.53-.22l-16.5-16.5a.75.75 0 1 1 1.06-1.06l16.5 16.5a.75.75 0 0 1-.53 1.28m-3.852-8.816-1.06-1.06 3.652-3.654a1.753 1.753 0 0 0-.136-2.597c-.684-.56-1.754-.461-2.439.223l-3.552 3.552a.75.75 0 1 1-1.06-1.06l3.551-3.552c1.223-1.224 3.18-1.366 4.45-.324a3.27 3.27 0 0 1 1.195 2.36 3.25 3.25 0 0 1-.948 2.459zm-4.059 2.999a.75.75 0 0 0-1.06 0L7.44 15.043l-2.475-2.475 1.794-1.794a.75.75 0 1 0-1.06-1.06l-2.624 2.623a2.74 2.74 0 0 0-.687 1.15L1.004 18.07a.75.75 0 0 0 .934.935l4.584-1.384a2.75 2.75 0 0 0 1.15-.688l2.667-2.666a.75.75 0 0 0 0-1.061m-7.494 3.959.98-3.245q.042-.135.113-.258l2.41 2.409a1.2 1.2 0 0 1-.258.114z"/></svg>`;
}
