/**
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
/* Generated by `yarn generate:workflow-icons` from icon-source/workflow/. Do not edit by hand. */

/**
 * The Education workflow icon as a framework-agnostic SVG string. Usable via `innerHTML`,
 * React `dangerouslySetInnerHTML`, Vue `v-html`, or Lit `unsafeSVG`. Color follows
 * `var(--swc-icon-color, currentColor)`.
 */
export function Icon_Education(): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path fill="var(--swc-icon-color, currentColor)" d="M10 11.622c-.287 0-.574-.055-.847-.165l-.956-.386a.75.75 0 1 1 .56-1.39l.957.385a.76.76 0 0 0 .57 0l7.058-2.844a.24.24 0 0 0 .158-.233.234.234 0 0 0-.158-.23l-7.057-2.846a.77.77 0 0 0-.572.001L2.658 6.76c-.13.053-.158.155-.158.231s.027.179.158.232l.3.12a.75.75 0 1 1-.561 1.391l-.3-.12A1.74 1.74 0 0 1 1 6.988a1.74 1.74 0 0 1 1.097-1.62l7.057-2.847a2.26 2.26 0 0 1 1.69 0l7.059 2.846A1.74 1.74 0 0 1 19 6.99c0 .717-.43 1.354-1.097 1.623l-7.057 2.845a2.3 2.3 0 0 1-.846.165m-.038 4.31a9.7 9.7 0 0 1-1.71-.15.75.75 0 0 1 .267-1.477c.465.084.95.127 1.443.127 3.967 0 5.25-1.762 5.25-2.616a.75.75 0 0 1 1.5 0c0 1.145-1.212 4.116-6.75 4.116"/><path fill="var(--swc-icon-color, currentColor)" d="M10.695 6.423a.753.753 0 0 0-.98-.406L6.102 7.514a2.24 2.24 0 0 0-1.39 2.079v5.964l-.482.964c-.213.426-.191.924.06 1.33s.686.649 1.164.649.912-.242 1.163-.648a1.36 1.36 0 0 0 .06-1.331l-.465-.931V9.593c0-.305.182-.576.463-.693l3.614-1.497a.75.75 0 0 0 .406-.98"/></svg>`;
}
