/**
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
/* Generated by `yarn generate:workflow-icons` from icon-source/workflow/. Do not edit by hand. */

/**
 * The Erase workflow icon as a framework-agnostic SVG string. Usable via `innerHTML`,
 * React `dangerouslySetInnerHTML`, Vue `v-html`, or Lit `unsafeSVG`. Color follows
 * `var(--swc-icon-color, currentColor)`.
 */
export function Icon_Erase(): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path fill="var(--swc-icon-color, currentColor)" d="m18.184 5.868-3.688-3.687c-.85-.85-2.333-.85-3.182 0l-9.498 9.497a2.25 2.25 0 0 0-.002 3.178l2.482 2.492c.42.42 1.001.662 1.594.662h2.405a2.26 2.26 0 0 0 1.591-.66l8.299-8.3a2.253 2.253 0 0 0-.001-3.182M8.826 16.29a.76.76 0 0 1-.53.22H5.89a.76.76 0 0 1-.531-.22l-2.483-2.492a.75.75 0 0 1 .001-1.06l2.636-2.636 4.59 4.59a.7.7 0 0 0 .193.128zm8.298-8.3-5.833 5.834a.7.7 0 0 0-.128-.193l-4.59-4.59 5.802-5.8a.77.77 0 0 1 1.06 0l3.688 3.688a.75.75 0 0 1 0 1.06m.814 10.032H17.5a.75.75 0 0 1 0-1.5h.437a.75.75 0 0 1 0 1.5m-2.931 0H12.5a.75.75 0 0 1 0-1.5h2.506a.75.75 0 0 1 0 1.5"/></svg>`;
}
