/**
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
/* Generated by `yarn generate:workflow-icons` from icon-source/workflow/. Do not edit by hand. */

/**
 * The Eyedropper workflow icon as a framework-agnostic SVG string. Usable via `innerHTML`,
 * React `dangerouslySetInnerHTML`, Vue `v-html`, or Lit `unsafeSVG`. Color follows
 * `var(--swc-icon-color, currentColor)`.
 */
export function Icon_Eyedropper(): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path fill="var(--swc-icon-color, currentColor)" d="M18.27 2.162c-.561-.669-1.332-1.058-2.168-1.095a3.48 3.48 0 0 0-2.504 1.026l-1.3 1.29a2.53 2.53 0 0 0-2.963.45l-.385.385a2.52 2.52 0 0 0-.174 3.36L4.914 11.44l-3.16 3.16a2.58 2.58 0 0 0 0 3.645A2.57 2.57 0 0 0 3.578 19c.66 0 1.32-.25 1.823-.754l7.02-7.02a2.52 2.52 0 0 0 1.598.585 2.52 2.52 0 0 0 1.786-.739l.384-.384a2.53 2.53 0 0 0 .454-2.957l1.208-1.187.004-.005c1.29-1.289 1.464-3.13.416-4.376M4.34 17.185a1.08 1.08 0 0 1-1.525 0 1.08 1.08 0 0 1 .004-1.528l3.156-3.156 3.842-3.844 1.526 1.526zm12.457-11.71-1.664 1.634a.753.753 0 0 0-.005 1.066c.4.4.4 1.05 0 1.451l-.385.385c-.4.4-1.05.4-1.451 0L10.011 6.73c-.4-.4-.4-1.051 0-1.452l.385-.384a1.024 1.024 0 0 1 1.451 0 .75.75 0 0 0 1.058.002l1.751-1.74c.395-.396.889-.611 1.38-.59.418.019.793.212 1.086.561.634.754.275 1.744-.325 2.348"/></svg>`;
}
