/**
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
/* Generated by `yarn generate:workflow-icons` from icon-source/workflow/. Do not edit by hand. */

/**
 * The Feedback workflow icon as a framework-agnostic SVG string. Usable via `innerHTML`,
 * React `dangerouslySetInnerHTML`, Vue `v-html`, or Lit `unsafeSVG`. Color follows
 * `var(--swc-icon-color, currentColor)`.
 */
export function Icon_Feedback(): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path fill="var(--swc-icon-color, currentColor)" d="M6.25 19q-.151 0-.294-.06a.75.75 0 0 1-.456-.69V15h-.75A3.755 3.755 0 0 1 1 11.25v-5.5A3.755 3.755 0 0 1 4.75 2h10.5A3.755 3.755 0 0 1 19 5.75v5.5A3.755 3.755 0 0 1 15.25 15h-4.543l-3.936 3.79a.75.75 0 0 1-.521.21M4.75 3.5C3.51 3.5 2.5 4.51 2.5 5.75v5.5c0 1.24 1.01 2.25 2.25 2.25h1.5a.75.75 0 0 1 .75.75v2.236l2.884-2.776a.75.75 0 0 1 .52-.21h4.846c1.24 0 2.25-1.01 2.25-2.25v-5.5c0-1.24-1.01-2.25-2.25-2.25z"/><circle cx="5.5" cy="8.5" r="1.5" fill="var(--swc-icon-color, currentColor)"/><circle cx="10" cy="8.5" r="1.5" fill="var(--swc-icon-color, currentColor)"/><circle cx="14.5" cy="8.5" r="1.5" fill="var(--swc-icon-color, currentColor)"/></svg>`;
}
