/**
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
/* Generated by `yarn generate:workflow-icons` from icon-source/workflow/. Do not edit by hand. */

/**
 * The FileConvert workflow icon as a framework-agnostic SVG string. Usable via `innerHTML`,
 * React `dangerouslySetInnerHTML`, Vue `v-html`, or Lit `unsafeSVG`. Color follows
 * `var(--swc-icon-color, currentColor)`.
 */
export function Icon_FileConvert(): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path fill="var(--swc-icon-color, currentColor)" d="m12.28 12.53-1.75 1.75a.75.75 0 0 1-1.06 0l-1.75-1.75a.75.75 0 1 1 1.06-1.06l.421.42a3.5 3.5 0 0 0-1.328-2.642 3.503 3.503 0 0 0-5.566 1.937.75.75 0 0 1-1.459-.35A5.005 5.005 0 0 1 8.8 8.068a5.02 5.02 0 0 1 1.907 3.916l.513-.513a.75.75 0 1 1 1.06 1.06M17 6.871v8.879c0 1.24-1.01 2.25-2.25 2.25h-9.5C4.01 18 3 16.99 3 15.75v-2a.75.75 0 0 1 1.5 0v2c0 .414.336.75.75.75h9.5a.75.75 0 0 0 .75-.75V8h-3.25C11.01 8 10 6.99 10 5.75V2.5H5.25a.75.75 0 0 0-.75.75v1.5a.75.75 0 0 1-1.5 0v-1.5C3 2.01 4.01 1 5.25 1h5.879c.6 0 1.164.234 1.59.658l3.622 3.623c.425.425.659.99.659 1.59M12.25 6.5h3.136c-.032-.055-.06-.113-.106-.16l-3.62-3.62c-.046-.046-.104-.074-.159-.106V5.75c0 .414.336.75.75.75"/></svg>`;
}
