/**
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
/* Generated by `yarn generate:workflow-icons` from icon-source/workflow/. Do not edit by hand. */

/**
 * The Filmstrip workflow icon as a framework-agnostic SVG string. Usable via `innerHTML`,
 * React `dangerouslySetInnerHTML`, Vue `v-html`, or Lit `unsafeSVG`. Color follows
 * `var(--swc-icon-color, currentColor)`.
 */
export function Icon_Filmstrip(): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path fill="var(--swc-icon-color, currentColor)" d="M15.25 7h-.5a.75.75 0 0 1 0-1.5h.5a.75.75 0 0 1 0 1.5m-3.333 0h-.5a.75.75 0 0 1 0-1.5h.5a.75.75 0 0 1 0 1.5M8.584 7h-.5a.75.75 0 0 1 0-1.5h.5a.75.75 0 0 1 0 1.5M5.25 7h-.5a.75.75 0 0 1 0-1.5h.5a.75.75 0 0 1 0 1.5m10 7.5h-.5a.75.75 0 0 1 0-1.5h.5a.75.75 0 0 1 0 1.5m-3.333 0h-.5a.75.75 0 0 1 0-1.5h.5a.75.75 0 0 1 0 1.5m-3.333 0h-.5a.75.75 0 0 1 0-1.5h.5a.75.75 0 0 1 0 1.5m-3.334 0h-.5a.75.75 0 0 1 0-1.5h.5a.75.75 0 0 1 0 1.5"/><path fill="var(--swc-icon-color, currentColor)" d="M16.75 17H3.25C2.01 17 1 15.99 1 14.75v-9.5C1 4.01 2.01 3 3.25 3h13.5C17.99 3 19 4.01 19 5.25v9.5c0 1.24-1.01 2.25-2.25 2.25M3.25 4.5a.75.75 0 0 0-.75.75v9.5c0 .413.336.75.75.75h13.5a.75.75 0 0 0 .75-.75v-9.5a.75.75 0 0 0-.75-.75z"/></svg>`;
}
