/**
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
/* Generated by `yarn generate:workflow-icons` from icon-source/workflow/. Do not edit by hand. */

/**
 * The Filters workflow icon as a framework-agnostic SVG string. Usable via `innerHTML`,
 * React `dangerouslySetInnerHTML`, Vue `v-html`, or Lit `unsafeSVG`. Color follows
 * `var(--swc-icon-color, currentColor)`.
 */
export function Icon_Filters(): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path fill="var(--swc-icon-color, currentColor)" d="M15.99 6.806C15.886 3.587 13.243 1 10 1S4.114 3.587 4.01 6.806A6 6 0 0 0 1 12c0 3.309 2.691 6 6 6a5.96 5.96 0 0 0 3-.812A5.96 5.96 0 0 0 13 18c3.309 0 6-2.691 6-6a6 6 0 0 0-3.01-5.194m-3.189 3.688a6 6 0 0 0-1.49-2.659A4.5 4.5 0 0 1 13 7.5c.5 0 .974.101 1.424.253a4.48 4.48 0 0 1-1.623 2.74M10 15.33a4.48 4.48 0 0 1-1.417-2.506c.455.11.928.176 1.417.176s.962-.065 1.417-.176A4.48 4.48 0 0 1 10 15.33M5.576 7.753C6.026 7.6 6.5 7.5 7 7.5c.598 0 1.167.123 1.69.335a6 6 0 0 0-1.491 2.659 4.48 4.48 0 0 1-1.623-2.741M10 11.5c-.5 0-.974-.101-1.424-.253A4.47 4.47 0 0 1 10 8.67a4.47 4.47 0 0 1 1.424 2.577A4.4 4.4 0 0 1 10 11.5m0-9c2.2 0 4.028 1.588 4.417 3.676A6 6 0 0 0 13 6a5.96 5.96 0 0 0-3 .812A5.96 5.96 0 0 0 7 6c-.489 0-.962.065-1.417.176A4.5 4.5 0 0 1 10 2.5M2.5 12c0-1.417.672-2.668 1.699-3.494a6.02 6.02 0 0 0 2.81 3.688 5.98 5.98 0 0 0 1.68 3.97A4.5 4.5 0 0 1 7 16.5 4.505 4.505 0 0 1 2.5 12M13 16.5a4.5 4.5 0 0 1-1.69-.335 5.98 5.98 0 0 0 1.68-3.97 6.02 6.02 0 0 0 2.811-3.689C16.828 9.332 17.5 10.583 17.5 12c0 2.481-2.019 4.5-4.5 4.5"/></svg>`;
}
