/**
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
/* Generated by `yarn generate:workflow-icons` from icon-source/workflow/. Do not edit by hand. */

/**
 * The FindAndReplace workflow icon as a framework-agnostic SVG string. Usable via `innerHTML`,
 * React `dangerouslySetInnerHTML`, Vue `v-html`, or Lit `unsafeSVG`. Color follows
 * `var(--swc-icon-color, currentColor)`.
 */
export function Icon_FindAndReplace(): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path fill="var(--swc-icon-color, currentColor)" d="M9.818 2.62a.75.75 0 0 1-1.032.242 4 4 0 0 0-.444-.235 4 4 0 0 0-1.083-.309 3.94 3.94 0 0 0-3.834 1.748l.544-.16a.75.75 0 0 1 .424 1.44l-2.325.684a.75.75 0 0 1-.932-.508L.452 3.198a.75.75 0 1 1 1.44-.424l.18.61a5.464 5.464 0 0 1 7.504-1.797.75.75 0 0 1 .243 1.032m1.905 5.93a.75.75 0 0 0-.529-.225l-2.786-.03H8.4a.75.75 0 0 0-.007 1.5l.908.01a3.91 3.91 0 0 1-4.229 1.344 3.9 3.9 0 0 1-2.456-2.211.755.755 0 0 0-.984-.397.75.75 0 0 0-.397.984 5.4 5.4 0 0 0 3.398 3.058 5.4 5.4 0 0 0 5.785-1.76l-.012 1.03a.75.75 0 0 0 .742.757h.008a.75.75 0 0 0 .75-.742l.03-2.785a.75.75 0 0 0-.213-.532m7.338 9.471-4.306-4.305a5.8 5.8 0 0 0 1.032-2.044 5.867 5.867 0 0 0-4.137-7.177 5.82 5.82 0 0 0-4.444.582 5.82 5.82 0 0 0-2.73 3.548l-.033.126c-.1.401.157.762.559.862.403.1.821-.191.922-.592a4.33 4.33 0 0 1 2.031-2.644 4.33 4.33 0 0 1 3.307-.433 4.363 4.363 0 0 1 3.076 5.34 4.33 4.33 0 0 1-2.032 2.643 4.32 4.32 0 0 1-3.308.431 4.4 4.4 0 0 1-.748-.276.75.75 0 0 0-.645 1.355 5.9 5.9 0 0 0 2.524.571 5.87 5.87 0 0 0 3.574-1.223L18 19.082a.747.747 0 0 0 1.06 0 .75.75 0 0 0 0-1.06"/></svg>`;
}
