/**
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
/* Generated by `yarn generate:workflow-icons` from icon-source/workflow/. Do not edit by hand. */

/**
 * The Flag workflow icon as a framework-agnostic SVG string. Usable via `innerHTML`,
 * React `dangerouslySetInnerHTML`, Vue `v-html`, or Lit `unsafeSVG`. Color follows
 * `var(--swc-icon-color, currentColor)`.
 */
export function Icon_Flag(): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path fill="var(--swc-icon-color, currentColor)" d="M17.69 2.678a.75.75 0 0 0-.675-.105l-.587.195A5.77 5.77 0 0 1 13.09 2.7l-2.727-.88a7.3 7.3 0 0 0-3.741-.195l-2.123.45V1.75a.75.75 0 0 0-1.5 0v16.5a.75.75 0 0 0 1.5 0v-4.617l2.433-.516a5.8 5.8 0 0 1 2.97.156l2.728.881a7.27 7.27 0 0 0 4.234.072l.62-.205A.75.75 0 0 0 18 13.31V3.285a.75.75 0 0 0-.31-.607m-1.19 10.09-.073.024a5.75 5.75 0 0 1-3.336-.065l-2.727-.881a7.3 7.3 0 0 0-3.741-.196L4.5 12.1V3.608l2.434-.515a5.8 5.8 0 0 1 2.969.156l2.727.88a7.26 7.26 0 0 0 3.87.166z"/></svg>`;
}
