/**
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
/* Generated by `yarn generate:workflow-icons` from icon-source/workflow/. Do not edit by hand. */

/**
 * The FlipVertical workflow icon as a framework-agnostic SVG string. Usable via `innerHTML`,
 * React `dangerouslySetInnerHTML`, Vue `v-html`, or Lit `unsafeSVG`. Color follows
 * `var(--swc-icon-color, currentColor)`.
 */
export function Icon_FlipVertical(): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path fill="var(--swc-icon-color, currentColor)" d="M17.5 10.75a.75.75 0 1 1 0-1.5.75.75 0 0 1 0 1.5" data-name="Path 1029747"/><path fill="var(--swc-icon-color, currentColor)" d="M14.5 10.75a.75.75 0 1 1 0-1.5.75.75 0 0 1 0 1.5" data-name="Path 1029749"/><path fill="var(--swc-icon-color, currentColor)" d="M11.5 10.75a.75.75 0 1 1 0-1.5.75.75 0 0 1 0 1.5" data-name="Path 1029751"/><path fill="var(--swc-icon-color, currentColor)" d="M8.5 10.75a.75.75 0 1 1 0-1.5.75.75 0 0 1 0 1.5" data-name="Path 1029753"/><path fill="var(--swc-icon-color, currentColor)" d="M5.5 10.75a.75.75 0 1 1 0-1.5.75.75 0 0 1 0 1.5" data-name="Path 1029755"/><path fill="var(--swc-icon-color, currentColor)" d="M2.5 10.75a.75.75 0 1 1 0-1.5.75.75 0 0 1 0 1.5" data-name="Path 1029756"/><path fill="var(--swc-icon-color, currentColor)" d="M10 8.438c-.482 0-.964-.153-1.366-.46l-3.846-2.94a2.22 2.22 0 0 1-.765-2.51A2.22 2.22 0 0 1 6.155 1h7.69c.98 0 1.817.6 2.132 1.528a2.22 2.22 0 0 1-.766 2.51l-3.844 2.94a2.25 2.25 0 0 1-1.367.46M6.155 2.5a.73.73 0 0 0-.71.51.73.73 0 0 0 .254.836l3.846 2.94a.75.75 0 0 0 .911 0l3.844-2.94a.73.73 0 0 0 .256-.836.73.73 0 0 0-.711-.51z" opacity=".5"/><path fill="var(--swc-icon-color, currentColor)" d="M13.845 19h-7.69c-.98 0-1.817-.6-2.132-1.528a2.22 2.22 0 0 1 .766-2.51l3.844-2.94a2.255 2.255 0 0 1 2.733 0l3.846 2.94a2.22 2.22 0 0 1 .765 2.51A2.22 2.22 0 0 1 13.845 19M10 13.06a.75.75 0 0 0-.456.154L5.7 16.154a.73.73 0 0 0-.256.836.73.73 0 0 0 .711.51h7.69a.73.73 0 0 0 .71-.51.73.73 0 0 0-.254-.836l-3.846-2.94A.75.75 0 0 0 10 13.06"/></svg>`;
}
