/**
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
/* Generated by `yarn generate:workflow-icons` from icon-source/workflow/. Do not edit by hand. */

/**
 * The FlipHorizontal workflow icon as a framework-agnostic SVG string. Usable via `innerHTML`,
 * React `dangerouslySetInnerHTML`, Vue `v-html`, or Lit `unsafeSVG`. Color follows
 * `var(--swc-icon-color, currentColor)`.
 */
export function Icon_FlipHorizontal(): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path fill="var(--swc-icon-color, currentColor)" d="M10.75 2.5a.75.75 0 1 1-1.5 0 .75.75 0 0 1 1.5 0" data-name="Path 1029747"/><path fill="var(--swc-icon-color, currentColor)" d="M10.75 5.5a.75.75 0 1 1-1.5 0 .75.75 0 0 1 1.5 0" data-name="Path 1029749"/><path fill="var(--swc-icon-color, currentColor)" d="M10.75 8.5a.75.75 0 1 1-1.5 0 .75.75 0 0 1 1.5 0" data-name="Path 1029751"/><path fill="var(--swc-icon-color, currentColor)" d="M10.75 11.5a.75.75 0 1 1-1.5 0 .75.75 0 0 1 1.5 0" data-name="Path 1029753"/><path fill="var(--swc-icon-color, currentColor)" d="M10.75 14.5a.75.75 0 1 1-1.5 0 .75.75 0 0 1 1.5 0" data-name="Path 1029755"/><path fill="var(--swc-icon-color, currentColor)" d="M10.75 17.5a.75.75 0 1 1-1.5 0 .75.75 0 0 1 1.5 0" data-name="Path 1029756"/><path fill="var(--swc-icon-color, currentColor)" d="M3.266 16.099a2.3 2.3 0 0 1-.738-.122A2.22 2.22 0 0 1 1 13.845v-7.69c0-.98.6-1.817 1.528-2.132a2.22 2.22 0 0 1 2.51.766l2.94 3.844a2.255 2.255 0 0 1 0 2.733l-2.94 3.846a2.22 2.22 0 0 1-1.772.887m.002-10.697a.8.8 0 0 0-.258.042.73.73 0 0 0-.51.711v7.69c0 .499.39.67.51.71a.73.73 0 0 0 .836-.254l2.94-3.846a.75.75 0 0 0 0-.911L3.846 5.7a.7.7 0 0 0-.578-.298" opacity=".5"/><path fill="var(--swc-icon-color, currentColor)" d="M16.734 16.099a2.22 2.22 0 0 1-1.771-.888l-2.94-3.844a2.255 2.255 0 0 1 0-2.733l2.94-3.846a2.22 2.22 0 0 1 2.509-.765A2.22 2.22 0 0 1 19 6.155v7.69c0 .98-.6 1.817-1.528 2.132a2.3 2.3 0 0 1-.738.122m-.002-10.697a.7.7 0 0 0-.578.297l-2.94 3.846a.75.75 0 0 0 0 .911l2.94 3.844c.305.4.717.295.836.256a.73.73 0 0 0 .51-.711v-7.69a.73.73 0 0 0-.51-.71.8.8 0 0 0-.258-.043"/></svg>`;
}
