/**
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
/* Generated by `yarn generate:workflow-icons` from icon-source/workflow/. Do not edit by hand. */

/**
 * The FolderMoveTo workflow icon as a framework-agnostic SVG string. Usable via `innerHTML`,
 * React `dangerouslySetInnerHTML`, Vue `v-html`, or Lit `unsafeSVG`. Color follows
 * `var(--swc-icon-color, currentColor)`.
 */
export function Icon_FolderMoveTo(): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path fill="var(--swc-icon-color, currentColor)" d="M16.75 5h-5.964a.75.75 0 0 1-.566-.259L8.516 2.777A2.24 2.24 0 0 0 6.816 2H3.25C2.01 2 1 3.01 1 4.25v9.417a.75.75 0 0 0 1.5 0V6.5h14.25c.413 0 .75.337.75.75v7.5c0 .413-.337.75-.75.75H11.5a.75.75 0 0 0 0 1.5h5.25c1.24 0 2.25-1.01 2.25-2.25v-7.5C19 6.01 17.99 5 16.75 5M2.5 4.25c0-.413.337-.75.75-.75h3.565c.218 0 .424.094.567.259L8.459 5H2.5z"/><path fill="var(--swc-icon-color, currentColor)" d="M9.25 10.021h-3.5a.75.75 0 0 0 0 1.5h1.668L2.72 16.22a.75.75 0 1 0 1.06 1.06l4.72-4.72v1.711a.75.75 0 0 0 1.5 0v-3.5a.75.75 0 0 0-.75-.75"/></svg>`;
}
