/**
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
/* Generated by `yarn generate:workflow-icons` from icon-source/workflow/. Do not edit by hand. */

/**
 * The FolderOpen workflow icon as a framework-agnostic SVG string. Usable via `innerHTML`,
 * React `dangerouslySetInnerHTML`, Vue `v-html`, or Lit `unsafeSVG`. Color follows
 * `var(--swc-icon-color, currentColor)`.
 */
export function Icon_FolderOpen(): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path fill="var(--swc-icon-color, currentColor)" d="M19.211 8.896A2.23 2.23 0 0 0 17.414 8H6.66a2.26 2.26 0 0 0-2.162 1.629l-1.65 5.737a.74.74 0 0 1-.347-.616V4.25a.75.75 0 0 1 .75-.75h3.565c.218 0 .425.095.567.257l1.701 1.969a2.25 2.25 0 0 0 1.7.774h6.189a.75.75 0 0 0 0-1.5h-6.19a.75.75 0 0 1-.566-.257l-1.7-1.969A2.25 2.25 0 0 0 6.814 2H3.25C2.01 2 1 3.01 1 4.25v10.5C1 15.99 2.01 17 3.25 17c.023 0 .043-.011.066-.013.02.001.037.013.057.013h12.748c.998 0 1.887-.67 2.162-1.629l1.294-4.5a2.23 2.23 0 0 0-.366-1.975m-1.076 1.561-1.294 4.5a.75.75 0 0 1-.72.543H4.369l1.569-5.457a.755.755 0 0 1 .721-.543h10.755a.75.75 0 0 1 .721.957"/></svg>`;
}
