/**
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
/* Generated by `yarn generate:workflow-icons` from icon-source/workflow/. Do not edit by hand. */

/**
 * The FontPicker workflow icon as a framework-agnostic SVG string. Usable via `innerHTML`,
 * React `dangerouslySetInnerHTML`, Vue `v-html`, or Lit `unsafeSVG`. Color follows
 * `var(--swc-icon-color, currentColor)`.
 */
export function Icon_FontPicker(): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path fill="var(--swc-icon-color, currentColor)" d="M10.735 12.21 6.718 2.729a.75.75 0 0 0-.689-.458h-.002a.75.75 0 0 0-.69.455l-4.07 9.5a.75.75 0 0 0 1.379.59l1.185-2.765h4.36l1.163 2.744a.75.75 0 0 0 1.381-.585M4.473 8.551l1.55-3.617 1.533 3.617z"/><path fill="var(--swc-icon-color, currentColor)" d="M18.576 14.757c-.536-2.076-2.846-2.036-4.086-2.018-.657.017-1.16-.125-1.321-.363-.101-.149-.105-.41-.037-.733.323.117.664.186 1.016.186h.051a2.993 2.993 0 0 0 2.94-3.04 3 3 0 0 0-.167-.893h.578a.75.75 0 0 0 0-1.5h-1.7a3.07 3.07 0 0 0-1.75-.547 2.97 2.97 0 0 0-2.1.91 2.97 2.97 0 0 0-.84 2.128 2.95 2.95 0 0 0 .688 1.838c-.35.993-.349 1.82.047 2.442-.666.438-1.36 1.194-1.382 2.274a2.46 2.46 0 0 0 .733 1.824c.68.682 1.752 1.055 3.026 1.055h.11c1.624-.028 2.98-.602 3.723-1.575.466-.613.638-1.338.471-1.988M13.08 7.803a1.48 1.48 0 0 1 1.046-.454h.024c.811 0 1.476.652 1.49 1.465.013.821-.644 1.5-1.465 1.514h-.026a1.48 1.48 0 0 1-1.035-.419 1.48 1.48 0 0 1-.453-1.046 1.48 1.48 0 0 1 .42-1.06m3.832 8.032c-.455.598-1.41.965-2.555.984-.875.024-1.65-.214-2.047-.613a.96.96 0 0 1-.296-.734c.016-.826 1.085-1.25 1.091-1.253a.8.8 0 0 0 .195-.108 4.5 4.5 0 0 0 1.217.128c1.98-.03 2.452.288 2.607.892.053.202-.025.46-.212.704"/></svg>`;
}
