/**
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
/* Generated by `yarn generate:workflow-icons` from icon-source/workflow/. Do not edit by hand. */

/**
 * The FullScreenExit workflow icon as a framework-agnostic SVG string. Usable via `innerHTML`,
 * React `dangerouslySetInnerHTML`, Vue `v-html`, or Lit `unsafeSVG`. Color follows
 * `var(--swc-icon-color, currentColor)`.
 */
export function Icon_FullScreenExit(): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path fill="var(--swc-icon-color, currentColor)" d="M12.75 15h-5.5C6.01 15 5 13.99 5 12.75v-5.5C5 6.01 6.01 5 7.25 5h5.5C13.99 5 15 6.01 15 7.25v5.5c0 1.24-1.01 2.25-2.25 2.25m-5.5-8.5a.75.75 0 0 0-.75.75v5.5c0 .414.336.75.75.75h5.5a.75.75 0 0 0 .75-.75v-5.5a.75.75 0 0 0-.75-.75zM19 4.5h-2.25c-.69 0-1.25-.56-1.25-1.25V1A.75.75 0 0 1 17 1v2h2a.75.75 0 0 1 0 1.5m-15.75 0H1A.75.75 0 0 1 1 3h2V1a.75.75 0 0 1 1.5 0v2.25c0 .69-.56 1.25-1.25 1.25m.5 15.25A.75.75 0 0 1 3 19v-2H1a.75.75 0 0 1 0-1.5h2.25c.69 0 1.25.56 1.25 1.25V19a.75.75 0 0 1-.75.75M3.25 17h.01zm13 2.75a.75.75 0 0 1-.75-.75v-2.25c0-.69.56-1.25 1.25-1.25H19a.75.75 0 0 1 0 1.5h-2v2a.75.75 0 0 1-.75.75"/></svg>`;
}
