/**
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
/* Generated by `yarn generate:workflow-icons` from icon-source/workflow/. Do not edit by hand. */

/**
 * The Gift workflow icon as a framework-agnostic SVG string. Usable via `innerHTML`,
 * React `dangerouslySetInnerHTML`, Vue `v-html`, or Lit `unsafeSVG`. Color follows
 * `var(--swc-icon-color, currentColor)`.
 */
export function Icon_Gift(): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path fill="var(--swc-icon-color, currentColor)" d="M15.75 6h-1.314c.194-.376.314-.797.314-1.249A2.753 2.753 0 0 0 12 2.001c-.79 0-1.498.34-2 .874a2.74 2.74 0 0 0-2-.874 2.753 2.753 0 0 0-2.75 2.75c0 .452.12.873.314 1.249H4.25C3.01 6 2 7.01 2 8.25v1.5a2.25 2.25 0 0 0 1 1.869v4.131C3 16.99 4.01 18 5.25 18h9.5c1.24 0 2.25-1.01 2.25-2.25v-4.131a2.25 2.25 0 0 0 1-1.869v-1.5C18 7.01 16.99 6 15.75 6m.75 2.25v1.5c0 .413-.337.75-.75.75h-5V7.501H12l.01-.001h3.74c.413 0 .75.337.75.75M12 3.501A1.25 1.25 0 0 1 12.005 6H10.75V4.751c0-.69.56-1.25 1.25-1.25m-5.25 1.25a1.251 1.251 0 0 1 2.5 0V6H7.995A1.25 1.25 0 0 1 6.75 4.751M3.5 8.25c0-.413.337-.75.75-.75h3.74l.01.001h1.25V10.5h-5a.75.75 0 0 1-.75-.75zm1 7.5V12h4.75v4.5h-4a.75.75 0 0 1-.75-.75m10.25.75h-4V12h4.75v3.75c0 .413-.337.75-.75.75"/></svg>`;
}
