/**
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
/* Generated by `yarn generate:workflow-icons` from icon-source/workflow/. Do not edit by hand. */

/**
 * The GradientHorizontal workflow icon as a framework-agnostic SVG string. Usable via `innerHTML`,
 * React `dangerouslySetInnerHTML`, Vue `v-html`, or Lit `unsafeSVG`. Color follows
 * `var(--swc-icon-color, currentColor)`.
 */
export function Icon_GradientHorizontal(): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><defs><linearGradient id="a" x1="-239.333" x2="-223.067" y1="250" y2="250" gradientTransform="translate(240 -240)" gradientUnits="userSpaceOnUse"><stop offset="0" stop-color="var(--swc-icon-color, currentColor)"/><stop offset=".024" stop-color="var(--swc-icon-color, currentColor)" stop-opacity=".968"/><stop offset=".627" stop-color="var(--swc-icon-color, currentColor)" stop-opacity=".261"/><stop offset="1" stop-color="var(--swc-icon-color, currentColor)" stop-opacity="0"/></linearGradient></defs><path fill="url(#a)" d="M3 3h14v14H3z" transform="rotate(-90 10 10)"/><path fill="var(--swc-icon-color, currentColor)" d="M18 4.25v11.5c0 1.24-1.01 2.25-2.25 2.25H4.25C3.01 18 2 16.99 2 15.75V4.25C2 3.01 3.01 2 4.25 2h11.5C16.99 2 18 3.01 18 4.25M3.5 15.75c0 .413.337.75.75.75h11.5c.413 0 .75-.337.75-.75V4.25a.75.75 0 0 0-.75-.75H4.25a.75.75 0 0 0-.75.75z"/></svg>`;
}
