/**
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
/* Generated by `yarn generate:workflow-icons` from icon-source/workflow/. Do not edit by hand. */

/**
 * The GridsAndRulers workflow icon as a framework-agnostic SVG string. Usable via `innerHTML`,
 * React `dangerouslySetInnerHTML`, Vue `v-html`, or Lit `unsafeSVG`. Color follows
 * `var(--swc-icon-color, currentColor)`.
 */
export function Icon_GridsAndRulers(): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path fill="var(--swc-icon-color, currentColor)" d="M2.75 12.059a.75.75 0 0 1-.75-.75V4.25C2 3.01 3.01 2 4.25 2h8.5C13.99 2 15 3.01 15 4.25v3.148a.75.75 0 0 1-1.5 0V4.25a.75.75 0 0 0-.75-.75h-8.5a.75.75 0 0 0-.75.75v7.059a.75.75 0 0 1-.75.75"/><path fill="var(--swc-icon-color, currentColor)" d="m6 11.27 5-1.692V7.25h3V6h-3V3H9.75v3h-2.5V3H6v3H3v1.25h3v2.5H3V11h3zm1.25-4.02h2.5v2.5h-2.5z" opacity=".3"/><path fill="var(--swc-icon-color, currentColor)" d="m18.92 12.692-.88-2.594a1.5 1.5 0 0 0-1.9-.939L3.352 13.484a1.5 1.5 0 0 0-.866.755c-.177.36-.205.767-.076 1.148l.88 2.593a1.5 1.5 0 0 0 1.901.94l12.788-4.324.001-.001a1.503 1.503 0 0 0 .94-1.903M4.712 17.5l-.88-2.593 1.577-.533.407 1.206A.625.625 0 0 0 7 15.18l-.408-1.206 1.657-.561.211.623a.625.625 0 0 0 1.185-.4l-.211-.624 1.657-.56.408 1.205a.625.625 0 0 0 1.184-.4l-.408-1.206 1.658-.561.212.623a.624.624 0 1 0 1.183-.4l-.211-.624 1.503-.508.879 2.595z"/></svg>`;
}
