/**
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
/* Generated by `yarn generate:workflow-icons` from icon-source/workflow/. Do not edit by hand. */

/**
 * The GroupNo workflow icon as a framework-agnostic SVG string. Usable via `innerHTML`,
 * React `dangerouslySetInnerHTML`, Vue `v-html`, or Lit `unsafeSVG`. Color follows
 * `var(--swc-icon-color, currentColor)`.
 */
export function Icon_GroupNo(): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path fill="var(--swc-icon-color, currentColor)" d="M8.5 15h-2c-.827 0-1.5-.673-1.5-1.5S5.673 12 6.5 12h2c.827 0 1.5.673 1.5 1.5S9.327 15 8.5 15m8.75-.603a.75.75 0 0 1-.75-.75V4.25a.75.75 0 0 0-.75-.75H6.32a.75.75 0 0 1 0-1.5h9.43C16.99 2 18 3.01 18 4.25v9.397a.75.75 0 0 1-.75.75"/><path fill="var(--swc-icon-color, currentColor)" d="M13.25 18h-9C3.01 18 2 16.99 2 15.75v-9a.75.75 0 0 1 1.5 0v9c0 .413.336.75.75.75h9a.75.75 0 0 1 0 1.5m0-8h-.334a.75.75 0 0 1 0-1.5h.334a.25.25 0 0 0 .25-.25v-1.5a.25.25 0 0 0-.25-.25H9.417a.75.75 0 0 1 0-1.5h3.833c.965 0 1.75.785 1.75 1.75v1.5c0 .965-.785 1.75-1.75 1.75m5 9.02a.75.75 0 0 1-.53-.22L1.22 2.3a.75.75 0 1 1 1.06-1.06l16.5 16.5a.75.75 0 0 1-.53 1.28"/></svg>`;
}
