/**
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
/* Generated by `yarn generate:workflow-icons` from icon-source/workflow/. Do not edit by hand. */

/**
 * The ImageAdd workflow icon as a framework-agnostic SVG string. Usable via `innerHTML`,
 * React `dangerouslySetInnerHTML`, Vue `v-html`, or Lit `unsafeSVG`. Color follows
 * `var(--swc-icon-color, currentColor)`.
 */
export function Icon_ImageAdd(): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" data-name="ICONS" viewBox="0 0 20 20"><path fill="var(--swc-icon-color, currentColor)" d="M14.5 7.521a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0M15 10.5a4.5 4.5 0 1 0 0 9 4.5 4.5 0 0 0 0-9m2.5 5.125h-1.875V17.5a.626.626 0 0 1-1.25 0v-1.875H12.5a.626.626 0 0 1 0-1.25h1.875V12.5a.626.626 0 0 1 1.25 0v1.875H17.5a.626.626 0 0 1 0 1.25"/><path fill="var(--swc-icon-color, currentColor)" d="M16.75 3H3.25C2.01 3 1 4.01 1 5.25v9.5C1 15.99 2.01 17 3.25 17h5.09a.75.75 0 0 0 0-1.5H3.25a.75.75 0 0 1-.75-.75v-1.169l2.97-2.969a.75.75 0 0 1 1.06 0l1.915 1.915a.75.75 0 1 0 1.06-1.06L7.592 9.552a2.253 2.253 0 0 0-3.182 0L2.5 11.46V5.25c0-.413.337-.75.75-.75h13.5c.413 0 .75.337.75.75v3.847a.75.75 0 0 0 1.5 0V5.25C19 4.01 17.99 3 16.75 3"/></svg>`;
}
