/**
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
/* Generated by `yarn generate:workflow-icons` from icon-source/workflow/. Do not edit by hand. */

/**
 * The ImageBackgroundRemove workflow icon as a framework-agnostic SVG string. Usable via `innerHTML`,
 * React `dangerouslySetInnerHTML`, Vue `v-html`, or Lit `unsafeSVG`. Color follows
 * `var(--swc-icon-color, currentColor)`.
 */
export function Icon_ImageBackgroundRemove(): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path fill="var(--swc-icon-color, currentColor)" d="M2 4h4v4H2zm8 8h-.693L6 9V8h4zm0-8h4v4h-4zm4 4h4v4h-4zm0 4.285-4 1.175V12h4z" opacity=".35"/><path fill="var(--swc-icon-color, currentColor)" d="M14.5 7.521a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0"/><path fill="var(--swc-icon-color, currentColor)" d="M16.75 3H3.25C2.01 3 1 4.01 1 5.25v9.5C1 15.99 2.01 17 3.25 17h13.5c1.24 0 2.25-1.01 2.25-2.25v-9.5C19 4.01 17.99 3 16.75 3M3.25 4.5h13.5a.75.75 0 0 1 .75.75v8.21l-1.909-1.908c-.85-.85-2.333-.85-3.182 0l-1.232 1.231a.25.25 0 0 1-.354.001L7.591 9.552c-.85-.85-2.333-.85-3.182 0L2.5 11.46V5.25a.75.75 0 0 1 .75-.75m0 11a.75.75 0 0 1-.75-.75v-1.168l2.97-2.97a.77.77 0 0 1 1.06 0l3.233 3.234c.682.68 1.792.682 2.474-.001l1.233-1.233a.77.77 0 0 1 1.06 0l2.701 2.701a.74.74 0 0 1-.481.187z"/></svg>`;
}
