/**
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
/* Generated by `yarn generate:workflow-icons` from icon-source/workflow/. Do not edit by hand. */

/**
 * The LassoSelect workflow icon as a framework-agnostic SVG string. Usable via `innerHTML`,
 * React `dangerouslySetInnerHTML`, Vue `v-html`, or Lit `unsafeSVG`. Color follows
 * `var(--swc-icon-color, currentColor)`.
 */
export function Icon_LassoSelect(): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path fill="var(--swc-icon-color, currentColor)" d="M12.999 11.65c-.611.3-1.257.523-1.918.663a10 10 0 0 1-3.667.067A2.88 2.88 0 0 0 4.59 8.925c-.734 0-1.398.284-1.907.738-.03-.089-.07-.174-.092-.266C2.05 7.2 3.989 4.665 7.199 3.37a.75.75 0 1 0-.561-1.39C2.666 3.582.402 6.78 1.134 9.757c.13.518.35 1 .642 1.444a3 3 0 0 0-.067.605 2.884 2.884 0 0 0 2.881 2.88c.149 0 .29-.021.433-.043.173.286.368.54.544.764.263.336.512.653.521.908.02.284-.07.558-.255.773a1.05 1.05 0 0 1-.986.352c-.41-.064-.796.203-.868.61s.203.798.61.869a2.6 2.6 0 0 0 .625.03 2.55 2.55 0 0 0 1.753-.88 2.53 2.53 0 0 0 .619-1.835c-.025-.715-.458-1.266-.84-1.753a9 9 0 0 1-.339-.458c.096-.079.19-.158.276-.249a11.5 11.5 0 0 0 4.708.007 10 10 0 0 0 2.268-.783.75.75 0 0 0-.66-1.348m-9.79.156a1.382 1.382 0 0 1 2.763 0q-.002.116-.023.227c-.102-.032-.207-.05-.308-.086a.75.75 0 0 0-.978.521 2.7 2.7 0 0 0-.08.718 1.38 1.38 0 0 1-1.374-1.38m13.326-2.392c-.269.33-.62.589-1.014.75a.75.75 0 0 0 .563 1.39 4.05 4.05 0 0 0 1.614-1.193.75.75 0 1 0-1.163-.947M18.478 4.7a.75.75 0 0 0-1.236.85c.226.329.309.743.226 1.134a.75.75 0 0 0 1.468.31c.167-.792 0-1.628-.458-2.295m-2.54-1.244a.75.75 0 0 0 .406-1.38 5.2 5.2 0 0 0-1.828-.735.75.75 0 0 0-.286 1.473 3.7 3.7 0 0 1 1.303.523c.125.081.266.12.405.12m-6.253-.763a1 1 0 0 0 .108-.007 15 15 0 0 1 1.54-.143.75.75 0 0 0 .719-.78c-.018-.414-.357-.775-.781-.718a17 17 0 0 0-1.692.156.75.75 0 0 0 .106 1.492"/></svg>`;
}
