/**
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
/* Generated by `yarn generate:workflow-icons` from icon-source/workflow/. Do not edit by hand. */

/**
 * The Layers workflow icon as a framework-agnostic SVG string. Usable via `innerHTML`,
 * React `dangerouslySetInnerHTML`, Vue `v-html`, or Lit `unsafeSVG`. Color follows
 * `var(--swc-icon-color, currentColor)`.
 */
export function Icon_Layers(): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path fill="var(--swc-icon-color, currentColor)" d="M10 13.5c-.43 0-.86-.123-1.235-.37L2.729 9.166a2.24 2.24 0 0 1-1.015-1.879c0-.76.38-1.464 1.015-1.882l6.036-3.966a2.25 2.25 0 0 1 2.47 0l6.036 3.966a2.24 2.24 0 0 1 1.015 1.882c0 .76-.38 1.462-1.015 1.879l-6.036 3.966A2.25 2.25 0 0 1 10 13.5m-.412-1.623c.25.164.574.164.824 0l6.036-3.966c.215-.14.338-.369.338-.626s-.123-.485-.339-.627l-6.035-3.966a.75.75 0 0 0-.824 0L3.552 6.658c-.215.142-.338.37-.338.627s.123.486.338.626z"/><path fill="var(--swc-icon-color, currentColor)" d="M10 19c-.43 0-.86-.123-1.235-.37l-6.036-3.965a2.22 2.22 0 0 1-1.001-1.675 2.24 2.24 0 0 1 .703-1.839.751.751 0 0 1 1.026 1.096.746.746 0 0 0 .095 1.164l6.036 3.966c.25.164.574.164.824 0l6.036-3.966a.72.72 0 0 0 .33-.55.75.75 0 0 0-.235-.614.75.75 0 0 1 1.026-1.096 2.24 2.24 0 0 1 .703 1.84 2.22 2.22 0 0 1-1.001 1.674l-6.036 3.966A2.25 2.25 0 0 1 10 19"/></svg>`;
}
