/**
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
/* Generated by `yarn generate:workflow-icons` from icon-source/workflow/. Do not edit by hand. */

/**
 * The Leave workflow icon as a framework-agnostic SVG string. Usable via `innerHTML`,
 * React `dangerouslySetInnerHTML`, Vue `v-html`, or Lit `unsafeSVG`. Color follows
 * `var(--swc-icon-color, currentColor)`.
 */
export function Icon_Leave(): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path fill="var(--swc-icon-color, currentColor)" d="m19.077 9.533-2.25-2.25a.75.75 0 1 0-1.06 1.061l.97.97H10.75a.75.75 0 0 0 0 1.5h5.986l-.97.97a.75.75 0 1 0 1.061 1.06l2.25-2.25a.75.75 0 0 0 0-1.06"/><path fill="var(--swc-icon-color, currentColor)" d="M11.75 17h-7.5C3.01 17 2 15.99 2 14.75v-9.5C2 4.01 3.01 3 4.25 3h7.5C12.99 3 14 4.01 14 5.25V7a.75.75 0 0 1-1.5 0V5.25a.75.75 0 0 0-.75-.75h-7.5a.75.75 0 0 0-.75.75v9.5c0 .413.337.75.75.75h7.5c.413 0 .75-.337.75-.75V13a.75.75 0 0 1 1.5 0v1.75c0 1.24-1.01 2.25-2.25 2.25"/></svg>`;
}
