/**
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
/* Generated by `yarn generate:workflow-icons` from icon-source/workflow/. Do not edit by hand. */

/**
 * The Link workflow icon as a framework-agnostic SVG string. Usable via `innerHTML`,
 * React `dangerouslySetInnerHTML`, Vue `v-html`, or Lit `unsafeSVG`. Color follows
 * `var(--swc-icon-color, currentColor)`.
 */
export function Icon_Link(): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path fill="var(--swc-icon-color, currentColor)" d="M5.313 18.748A4.05 4.05 0 0 1 2.44 17.56a4.07 4.07 0 0 1 0-5.747l3.906-3.906a4.07 4.07 0 0 1 6.313.71.75.75 0 1 1-1.27.799q-.151-.241-.359-.45a2.566 2.566 0 0 0-3.624.002l-3.905 3.905a2.57 2.57 0 0 0 0 3.626 2.57 2.57 0 0 0 3.626 0l1.952-1.952a.75.75 0 1 1 1.06 1.06l-1.95 1.953a4.06 4.06 0 0 1-2.875 1.188m8.341-6.655 3.906-3.905c1.584-1.585 1.584-4.164 0-5.748s-4.164-1.584-5.747 0L9.86 4.393a.75.75 0 1 0 1.06 1.06l1.953-1.952c1-.998 2.625-1 3.626 0a2.57 2.57 0 0 1 0 3.626l-3.905 3.905a2.566 2.566 0 0 1-3.984-.448.75.75 0 1 0-1.27.799q.24.381.567.71a4.05 4.05 0 0 0 2.874 1.188c1.04 0 2.081-.396 2.873-1.188"/></svg>`;
}
