/**
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
/* Generated by `yarn generate:workflow-icons` from icon-source/workflow/. Do not edit by hand. */

/**
 * The LinkVertical workflow icon as a framework-agnostic SVG string. Usable via `innerHTML`,
 * React `dangerouslySetInnerHTML`, Vue `v-html`, or Lit `unsafeSVG`. Color follows
 * `var(--swc-icon-color, currentColor)`.
 */
export function Icon_LinkVertical(): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path fill="var(--swc-icon-color, currentColor)" d="M10 19a3.754 3.754 0 0 1-3.75-3.75v-4.209a3.754 3.754 0 0 1 4.582-3.657.75.75 0 1 1-.33 1.463A2.252 2.252 0 0 0 7.75 11.04v4.209c-.001 1.24 1.008 2.25 2.249 2.25s2.25-1.01 2.25-2.25V13.54a.75.75 0 0 1 1.5 0v1.709A3.754 3.754 0 0 1 10 19m3.75-9.959V4.883c0-2.068-1.682-3.75-3.75-3.75s-3.75 1.682-3.75 3.75V6.54a.75.75 0 0 0 1.5 0V4.883c0-1.24 1.01-2.25 2.25-2.25s2.25 1.01 2.25 2.25V9.04a2.252 2.252 0 0 1-2.751 2.194.75.75 0 1 0-.33 1.463 3.754 3.754 0 0 0 4.582-3.657"/></svg>`;
}
