/**
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
/* Generated by `yarn generate:workflow-icons` from icon-source/workflow/. Do not edit by hand. */

/**
 * The Logo workflow icon as a framework-agnostic SVG string. Usable via `innerHTML`,
 * React `dangerouslySetInnerHTML`, Vue `v-html`, or Lit `unsafeSVG`. Color follows
 * `var(--swc-icon-color, currentColor)`.
 */
export function Icon_Logo(): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path fill="var(--swc-icon-color, currentColor)" d="M14.25 12.75h-5.5a.75.75 0 0 1-.658-1.11l2.75-5.038a.75.75 0 0 1 1.316 0l2.75 5.039a.75.75 0 0 1-.658 1.109m-4.236-1.5h2.972l-1.485-2.724zm-4.264 1.5a.75.75 0 0 1-.658-1.11l1.981-3.628a.75.75 0 1 1 1.317.718l-1.982 3.63a.75.75 0 0 1-.658.39"/><path fill="var(--swc-icon-color, currentColor)" d="M10 18.75a.75.75 0 0 1-.336-.08l-7.73-3.874a.75.75 0 0 1-.415-.671v-8.25a.75.75 0 0 1 .414-.67l7.731-3.876a.75.75 0 0 1 .672 0l7.73 3.875a.75.75 0 0 1 .415.671v8.25a.75.75 0 0 1-.414.67l-7.731 3.876a.75.75 0 0 1-.336.079m-6.981-5.088 6.981 3.5 6.981-3.5V6.338L10 2.838l-6.981 3.5z"/></svg>`;
}
