/**
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
/* Generated by `yarn generate:workflow-icons` from icon-source/workflow/. Do not edit by hand. */

/**
 * The MagicWand workflow icon as a framework-agnostic SVG string. Usable via `innerHTML`,
 * React `dangerouslySetInnerHTML`, Vue `v-html`, or Lit `unsafeSVG`. Color follows
 * `var(--swc-icon-color, currentColor)`.
 */
export function Icon_MagicWand(): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path fill="var(--swc-icon-color, currentColor)" d="M15.05 7.2c0-.601-.235-1.167-.658-1.59-.849-.85-2.333-.852-3.183 0L9.388 7.43a1 1 0 0 0-.06.069 1 1 0 0 0-.07.062l-7.599 7.598c-.425.425-.659.99-.659 1.591s.234 1.166.66 1.59a2.24 2.24 0 0 0 3.18 0l9.55-9.549c.425-.425.66-.99.66-1.59M3.78 17.28a.77.77 0 0 1-1.06 0 .746.746 0 0 1 0-1.06l7.2-7.2 1.065 1.055zm9.55-9.55-1.284 1.285-1.066-1.056 1.29-1.29a.766.766 0 0 1 1.06.002c.142.14.22.329.22.53s-.078.388-.22.53m5.376 3.101-1.261-.499-.203-1.342c-.065-.428-.758-.505-.916-.104l-.499 1.262-1.342.202a.478.478 0 0 0-.104.916l1.262.5.202 1.34a.477.477 0 0 0 .916.105l.5-1.261 1.34-.203a.477.477 0 0 0 .105-.916m-4.37-7.19 1.262.5.202 1.341a.478.478 0 0 0 .916.104l.5-1.26 1.341-.204a.478.478 0 0 0 .104-.916l-1.26-.498-.204-1.342c-.065-.428-.758-.505-.916-.105l-.498 1.263-1.342.201a.478.478 0 0 0-.105.916M5.78 4.69l1.023.406.164 1.088a.388.388 0 0 0 .744.084l.405-1.023 1.088-.165a.388.388 0 0 0 .085-.743l-1.023-.404-.165-1.09c-.053-.347-.615-.41-.743-.084l-.405 1.024-1.089.164a.388.388 0 0 0-.085.743"/></svg>`;
}
