/**
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
/* Generated by `yarn generate:workflow-icons` from icon-source/workflow/. Do not edit by hand. */

/**
 * The Market workflow icon as a framework-agnostic SVG string. Usable via `innerHTML`,
 * React `dangerouslySetInnerHTML`, Vue `v-html`, or Lit `unsafeSVG`. Color follows
 * `var(--swc-icon-color, currentColor)`.
 */
export function Icon_Market(): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path fill="var(--swc-icon-color, currentColor)" d="M16.39 9.813a2.88 2.88 0 0 1-2.13-.943 2.875 2.875 0 0 1-4.26 0 2.875 2.875 0 0 1-4.26 0 2.88 2.88 0 0 1-2.13.943c-1.17 0-2.225-.683-2.627-1.7a3.4 3.4 0 0 1 .106-2.706l1.448-2.973C2.87 1.583 3.727 1 4.697 1h10.606c.971 0 1.829.584 2.184 1.487l1.41 2.948c.266.463.57 1.507.123 2.673-.393 1.02-1.45 1.705-2.63 1.705m-1.38-2.88c0 .761.62 1.38 1.38 1.38.555 0 1.061-.305 1.23-.744.304-.793-.022-1.385-.025-1.391l-.037-.068-1.446-3.025c-.15-.374-.459-.585-.81-.585H4.698c-.35 0-.66.21-.789.537L2.423 6.091a1.9 1.9 0 0 0-.045 1.47c.178.45.673.752 1.232.752.761 0 1.38-.619 1.38-1.38a.75.75 0 0 1 1.5 0c0 .761.62 1.38 1.38 1.38s1.38-.619 1.38-1.38a.75.75 0 0 1 1.5 0 1.382 1.382 0 0 0 2.76 0 .75.75 0 0 1 1.5 0m1.74 3.817a.75.75 0 0 0-.75.75V13H9.521l-.015.003.003-1.502a.75.75 0 1 0-1.5-.002l-.009 5v.001H4.75a.75.75 0 0 1-.75-.75V11.5a.75.75 0 0 0-1.5 0v4.25C2.5 16.99 3.51 18 4.75 18h10.5c1.24 0 2.25-1.01 2.25-2.25V11.5a.75.75 0 0 0-.75-.75m-1.5 5.75H9.5l.003-2.004.018.004H16v1.25c0 .413-.337.75-.75.75"/></svg>`;
}
