/**
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
/* Generated by `yarn generate:workflow-icons` from icon-source/workflow/. Do not edit by hand. */

/**
 * The MediaOffline workflow icon as a framework-agnostic SVG string. Usable via `innerHTML`,
 * React `dangerouslySetInnerHTML`, Vue `v-html`, or Lit `unsafeSVG`. Color follows
 * `var(--swc-icon-color, currentColor)`.
 */
export function Icon_MediaOffline(): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path fill="var(--swc-icon-color, currentColor)" d="M18.583 15.073a.75.75 0 0 1-.664-1.096 2.824 2.824 0 0 0-2.362-4.122.75.75 0 0 1-.625-1.096 3.3 3.3 0 0 0 .39-1.53c0-1.845-1.5-3.345-3.343-3.345-.984 0-1.91.433-2.541 1.188a.75.75 0 1 1-1.15-.963 4.8 4.8 0 0 1 3.69-1.725 4.85 4.85 0 0 1 4.844 4.845q0 .659-.186 1.298a4.32 4.32 0 0 1 2.613 6.143.75.75 0 0 1-.666.403M11.95 17H3.717a3.455 3.455 0 0 1-3.452-3.451 3.45 3.45 0 0 1 2.324-3.25 3.9 3.9 0 0 1 .472-2.673.75.75 0 1 1 1.293.76c-.215.366-.33.785-.33 1.21q.001.5.206.964a.75.75 0 0 1-.637 1.052 1.95 1.95 0 0 0-1.828 1.937c0 1.076.876 1.951 1.952 1.951h8.231a.75.75 0 0 1 0 1.5m6.302 2.021a.75.75 0 0 1-.53-.22l-16.5-16.5a.75.75 0 1 1 1.06-1.06l16.5 16.5a.75.75 0 0 1-.53 1.28"/></svg>`;
}
