/**
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
/* Generated by `yarn generate:workflow-icons` from icon-source/workflow/. Do not edit by hand. */

/**
 * The MicrophoneOff workflow icon as a framework-agnostic SVG string. Usable via `innerHTML`,
 * React `dangerouslySetInnerHTML`, Vue `v-html`, or Lit `unsafeSVG`. Color follows
 * `var(--swc-icon-color, currentColor)`.
 */
export function Icon_MicrophoneOff(): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path fill="var(--swc-icon-color, currentColor)" d="M13.25 9.5a.75.75 0 0 1-.75-.75V5c0-1.379-1.122-2.5-2.5-2.5-.806 0-1.568.397-2.038 1.062a.75.75 0 1 1-1.225-.866A4 4 0 0 1 10 1c2.206 0 4 1.794 4 4v3.75a.75.75 0 0 1-.75.75m2.393 2.673a.75.75 0 0 1-.677-1.071A5.45 5.45 0 0 0 15.5 8.75v-.684a.75.75 0 0 1 1.5 0v.684a6.94 6.94 0 0 1-.679 2.994.75.75 0 0 1-.678.429M14 17.5h-3.266v-1.668c0-.044-.017-.082-.025-.124l.07-.004a.75.75 0 0 0 .662-.828.74.74 0 0 0-.829-.662 6 6 0 0 1-.612.036 5.507 5.507 0 0 1-5.5-5.5v-.684a.75.75 0 0 0-1.5 0v.684c0 3.61 2.746 6.588 6.26 6.96-.008.041-.026.079-.026.122V17.5H6A.75.75 0 0 0 6 19h8a.75.75 0 0 0 0-1.5m4.78.241-16.5-16.5a.75.75 0 1 0-1.06 1.06l16.5 16.5a.75.75 0 0 0 1.06 0 .75.75 0 0 0 0-1.06"/></svg>`;
}
