/**
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
/* Generated by `yarn generate:workflow-icons` from icon-source/workflow/. Do not edit by hand. */

/**
 * The Minimize workflow icon as a framework-agnostic SVG string. Usable via `innerHTML`,
 * React `dangerouslySetInnerHTML`, Vue `v-html`, or Lit `unsafeSVG`. Color follows
 * `var(--swc-icon-color, currentColor)`.
 */
export function Icon_Minimize(): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path fill="var(--swc-icon-color, currentColor)" d="M9 11.75v4.243a.75.75 0 0 1-1.5 0V13.56l-4.47 4.47a.75.75 0 0 1-1.06 0 .75.75 0 0 1 0-1.061l4.47-4.47H4.006a.75.75 0 0 1 0-1.5H8.25a.75.75 0 0 1 .75.75m9.03-9.779a.75.75 0 0 0-1.06 0L12.5 6.44V4.006a.75.75 0 0 0-1.5 0V8.25c0 .414.336.75.75.75h4.243a.75.75 0 0 0 0-1.5H13.56l4.47-4.47a.75.75 0 0 0 0-1.06"/></svg>`;
}
