/**
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
/* Generated by `yarn generate:workflow-icons` from icon-source/workflow/. Do not edit by hand. */

/**
 * The OrderOneDown workflow icon as a framework-agnostic SVG string. Usable via `innerHTML`,
 * React `dangerouslySetInnerHTML`, Vue `v-html`, or Lit `unsafeSVG`. Color follows
 * `var(--swc-icon-color, currentColor)`.
 */
export function Icon_OrderOneDown(): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path fill="var(--swc-icon-color, currentColor)" d="m13.148 15.452 4.205-2.901c.132-.092.147-.241.147-.301s-.015-.209-.147-.3l-4.206-2.902a.25.25 0 0 0-.294 0l-4.206 2.901c-.132.092-.147.241-.147.301s.015.209.147.3l4.206 2.902a.255.255 0 0 0 .295 0" opacity=".2"/><path fill="var(--swc-icon-color, currentColor)" d="m5.494 13.564-2 1.75a.75.75 0 0 1-.988 0l-2-1.75a.75.75 0 0 1 .988-1.128l.756.661V5.25a.75.75 0 0 1 1.5 0v7.847l.756-.661a.75.75 0 0 1 .988 1.128M14 7.813l4.204 2.902c.498.344.796.917.796 1.535s-.298 1.191-.796 1.535l-4.203 2.902c-.607.42-1.394.42-2.001 0l-4.204-2.902C7.298 13.441 7 12.868 7 12.25s.298-1.191.796-1.535L12 7.813c.304-.21.652-.315 1-.315.349 0 .696.106 1 .315m-.852 7.64 4.205-2.902c.132-.092.147-.241.147-.301s-.015-.209-.147-.3l-4.206-2.902a.25.25 0 0 0-.294 0l-4.206 2.901c-.132.092-.147.241-.147.301s.015.209.147.3l4.206 2.902a.255.255 0 0 0 .295 0"/><path fill="var(--swc-icon-color, currentColor)" d="M17.916 9.25a.748.748 0 0 1-.523-1.287.37.37 0 0 0 .102-.291.33.33 0 0 0-.14-.25L13.15 4.549a.26.26 0 0 0-.301 0L8.646 7.423a.33.33 0 0 0-.141.249c-.009.11.03.22.102.29a.75.75 0 1 1-1.046 1.075 1.85 1.85 0 0 1-.55-1.494 1.83 1.83 0 0 1 .787-1.358l4.204-2.875a1.76 1.76 0 0 1 1.995 0l4.205 2.875c.453.31.74.805.787 1.358a1.85 1.85 0 0 1-.55 1.494.75.75 0 0 1-.523.213"/></svg>`;
}
