/**
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
/* Generated by `yarn generate:workflow-icons` from icon-source/workflow/. Do not edit by hand. */

/**
 * The Order workflow icon as a framework-agnostic SVG string. Usable via `innerHTML`,
 * React `dangerouslySetInnerHTML`, Vue `v-html`, or Lit `unsafeSVG`. Color follows
 * `var(--swc-icon-color, currentColor)`.
 */
export function Icon_Order(): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path fill="var(--swc-icon-color, currentColor)" d="M13 12.502c-.348 0-.696-.106-1-.315L7.796 9.285C7.298 8.941 7 8.368 7 7.75s.298-1.191.796-1.535L12 3.313a1.75 1.75 0 0 1 2.001 0l4.203 2.902c.498.344.796.917.796 1.535s-.298 1.191-.796 1.535L14 12.187c-.304.21-.651.315-1 .315M13 4.5a.26.26 0 0 0-.147.048L8.647 7.449c-.132.092-.147.241-.147.301s.015.209.147.3l4.206 2.902a.25.25 0 0 0 .294 0l4.206-2.901c.132-.092.147-.241.147-.301s-.015-.209-.147-.3l-4.205-2.902A.26.26 0 0 0 13 4.5"/><path fill="var(--swc-icon-color, currentColor)" d="M13 17.001c-.348 0-.694-.104-.997-.31l-4.205-2.876a1.83 1.83 0 0 1-.787-1.358 1.85 1.85 0 0 1 .55-1.494.75.75 0 1 1 1.047 1.074.37.37 0 0 0-.103.291c.006.06.03.174.14.25l4.205 2.874a.26.26 0 0 0 .301 0l4.203-2.875a.33.33 0 0 0 .141-.249.37.37 0 0 0-.102-.29.75.75 0 1 1 1.046-1.075c.398.387.6.932.55 1.494a1.83 1.83 0 0 1-.787 1.358l-4.204 2.875c-.304.207-.65.311-.998.311m-8.494-4.565-.756.661V6.903l.756.661a.75.75 0 0 0 .988-1.128l-2-1.75a.75.75 0 0 0-.988 0l-2 1.75a.75.75 0 0 0 .988 1.128l.756-.661v6.194l-.756-.661a.75.75 0 0 0-.988 1.129l2 1.75c.037.032.081.049.123.073.032.018.06.042.095.056q.134.054.276.056c.142.002.187-.02.276-.056.035-.014.063-.038.095-.056.042-.024.086-.04.123-.074l2-1.75a.75.75 0 0 0-.988-1.128"/></svg>`;
}
