/**
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
/* Generated by `yarn generate:workflow-icons` from icon-source/workflow/. Do not edit by hand. */

/**
 * The Pattern workflow icon as a framework-agnostic SVG string. Usable via `innerHTML`,
 * React `dangerouslySetInnerHTML`, Vue `v-html`, or Lit `unsafeSVG`. Color follows
 * `var(--swc-icon-color, currentColor)`.
 */
export function Icon_Pattern(): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path fill="var(--swc-icon-color, currentColor)" d="M11.945 14.42a.75.75 0 0 1-1.061 0l-2.121-2.122a.75.75 0 0 1 1.06-1.06l2.122 2.12a.75.75 0 0 1 0 1.061m3.182-5.303-2.122 2.121a.75.75 0 0 1-1.06-1.06l2.12-2.122a.75.75 0 0 1 1.062 1.061m-3.89-.353a.75.75 0 0 1-1.06 0L8.055 6.64a.75.75 0 0 1 1.061-1.06l2.121 2.12a.75.75 0 0 1 0 1.062M8.055 9.823l-2.12 2.122a.75.75 0 0 1-1.062-1.061l2.122-2.121a.75.75 0 0 1 1.06 1.06"/><path fill="var(--swc-icon-color, currentColor)" d="M15.75 2H4.25C3.01 2 2 3.01 2 4.25v11.5C2 16.99 3.01 18 4.25 18h11.5c1.24 0 2.25-1.01 2.25-2.25V4.25C18 3.01 16.99 2 15.75 2m0 14.5h-1.643l.312-.313a.75.75 0 0 0-1.06-1.06L11.985 16.5H7.743l1.02-1.02a.75.75 0 0 0-1.061-1.06l-2.08 2.08H4.25a.75.75 0 0 1-.75-.75v-.936l.313.312a.75.75 0 0 0 1.06-1.06L3.5 12.692V7.036l1.02 1.02a.75.75 0 0 0 1.06-1.061L3.5 4.915V4.25a.75.75 0 0 1 .75-.75h1.643l-.312.313a.75.75 0 0 0 1.06 1.06L8.015 3.5h4.242l-1.02 1.02a.75.75 0 0 0 1.061 1.06l2.08-2.08h1.372a.75.75 0 0 1 .75.75v.936l-.313-.312a.75.75 0 0 0-1.06 1.06L16.5 7.308v5.656l-1.02-1.02a.75.75 0 0 0-1.06 1.061l2.08 2.08v.665a.75.75 0 0 1-.75.75"/></svg>`;
}
