/**
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
/* Generated by `yarn generate:workflow-icons` from icon-source/workflow/. Do not edit by hand. */

/**
 * The PinOn workflow icon as a framework-agnostic SVG string. Usable via `innerHTML`,
 * React `dangerouslySetInnerHTML`, Vue `v-html`, or Lit `unsafeSVG`. Color follows
 * `var(--swc-icon-color, currentColor)`.
 */
export function Icon_PinOn(): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path fill="var(--swc-icon-color, currentColor)" d="M15.787 11.404 14 9.901V5.424A1.927 1.927 0 0 0 12.791 2H7.21A1.927 1.927 0 0 0 6 5.423V9.9l-1.775 1.495a1.73 1.73 0 0 0-.547 1.94 1.73 1.73 0 0 0 1.65 1.164H9.25v2.75a.75.75 0 0 0 1.5 0V14.5h3.924c.752 0 1.4-.457 1.65-1.164a1.725 1.725 0 0 0-.537-1.932m-.878 1.431a.23.23 0 0 1-.235.165H5.327c-.146 0-.209-.09-.235-.165s-.035-.183.089-.283l2.052-1.729a.75.75 0 0 0 .267-.573V5a.75.75 0 0 0-.473-.696c-.154-.063-.24-.197-.24-.378 0-.235.19-.426.423-.426h5.581c.233 0 .424.191.424.426 0 .18-.086.315-.242.378A.75.75 0 0 0 12.5 5v5.25a.75.75 0 0 0 .267.574l2.064 1.738c.113.09.105.198.078.273"/></svg>`;
}
