/**
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
/* Generated by `yarn generate:workflow-icons` from icon-source/workflow/. Do not edit by hand. */

/**
 * The PinOff workflow icon as a framework-agnostic SVG string. Usable via `innerHTML`,
 * React `dangerouslySetInnerHTML`, Vue `v-html`, or Lit `unsafeSVG`. Color follows
 * `var(--swc-icon-color, currentColor)`.
 */
export function Icon_PinOff(): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path fill="var(--swc-icon-color, currentColor)" d="M17.38 6.566 13.436 2.62a1.9 1.9 0 0 0-1.36-.562 1.9 1.9 0 0 0-1.361.563 1.9 1.9 0 0 0-.557 1.565L6.992 7.35l-2.311-.199a1.72 1.72 0 0 0-1.76.986 1.73 1.73 0 0 0 .344 1.99L6.038 12.9 2.22 16.72a.75.75 0 1 0 1.06 1.06l3.82-3.818 2.774 2.774a1.73 1.73 0 0 0 1.99.344 1.72 1.72 0 0 0 .986-1.746l-.2-2.326 3.165-3.166a1.9 1.9 0 0 0 1.565-.554c.363-.363.563-.846.564-1.36s-.199-.998-.562-1.362M16.32 8.228a.39.39 0 0 1-.437.095.745.745 0 0 0-.827.158l-3.713 3.713a.75.75 0 0 0-.217.595l.231 2.688a.23.23 0 0 1-.138.249.23.23 0 0 1-.283-.05L4.325 9.067a.23.23 0 0 1-.05-.284.23.23 0 0 1 .224-.14l.04.003 2.672.229c.222.02.437-.06.595-.217l3.712-3.712a.75.75 0 0 0 .158-.827c-.066-.153-.031-.307.098-.437a.42.42 0 0 1 .301-.124.42.42 0 0 1 .299.123l3.946 3.946a.425.425 0 0 1-.002.6"/></svg>`;
}
