/**
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
/* Generated by `yarn generate:workflow-icons` from icon-source/workflow/. Do not edit by hand. */

/**
 * The Polygon3 workflow icon as a framework-agnostic SVG string. Usable via `innerHTML`,
 * React `dangerouslySetInnerHTML`, Vue `v-html`, or Lit `unsafeSVG`. Color follows
 * `var(--swc-icon-color, currentColor)`.
 */
export function Icon_Polygon3(): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path fill="var(--swc-icon-color, currentColor)" d="M16.949 18H3.05c-.813 0-1.542-.42-1.948-1.125a2.23 2.23 0 0 1 0-2.25L8.052 2.59C8.459 1.886 9.187 1.465 10 1.465s1.542.42 1.948 1.125l6.949 12.035a2.23 2.23 0 0 1 0 2.25A2.23 2.23 0 0 1 16.95 18M10 2.965a.74.74 0 0 0-.65.375L2.403 15.375a.74.74 0 0 0 0 .75.74.74 0 0 0 .65.375H16.95a.74.74 0 0 0 .65-.375.74.74 0 0 0 0-.75L10.648 3.34A.74.74 0 0 0 10 2.965"/></svg>`;
}
