/**
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
/* Generated by `yarn generate:workflow-icons` from icon-source/workflow/. Do not edit by hand. */

/**
 * The ProjectCreate workflow icon as a framework-agnostic SVG string. Usable via `innerHTML`,
 * React `dangerouslySetInnerHTML`, Vue `v-html`, or Lit `unsafeSVG`. Color follows
 * `var(--swc-icon-color, currentColor)`.
 */
export function Icon_ProjectCreate(): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><circle cx="16" cy="8" r=".75" fill="var(--swc-icon-color, currentColor)"/><path fill="var(--swc-icon-color, currentColor)" d="M11.5 9.875c-.758 0-1.375-.617-1.375-1.375s.617-1.375 1.375-1.375 1.375.617 1.375 1.375-.617 1.375-1.375 1.375m0-1.75a.376.376 0 0 0 0 .75.376.376 0 0 0 0-.75"/><path fill="var(--swc-icon-color, currentColor)" d="m10.595 1.396-.323-.277a1.95 1.95 0 0 0-1.54-.451 2.24 2.24 0 0 0-1.414.771L1.44 8.259c-.782.908-.729 2.24.118 2.97l.323.278c.183.158.39.276.613.355A2.23 2.23 0 0 0 2 13.25v3A2.753 2.753 0 0 0 4.75 19h4.725a.75.75 0 0 0 0-1.5H4.75c-.69 0-1.25-.56-1.25-1.25v-3a.75.75 0 0 1 .75-.75h5.13a.75.75 0 0 0 0-1.5H4.995l5.718-6.634c.782-.908.73-2.24-.118-2.97m-1.017 1.99-5.88 6.821a.75.75 0 0 1-.467.263.48.48 0 0 1-.372-.099l-.322-.278c-.217-.187-.2-.578.038-.854l5.88-6.82a.75.75 0 0 1 .54-.268c.086 0 .2.02.298.104l.323.277c.217.187.2.578-.038.854"/><path fill="var(--swc-icon-color, currentColor)" d="M8.525 15.5c-.414 0-.762-.336-.762-.75S8.086 14 8.5 14h.025a.75.75 0 0 1 0 1.5m6.102-9.553a.625.625 0 0 1-.6-.45l-.756-2.592a.625.625 0 0 1 .425-.776l2.592-.756a.624.624 0 0 1 .775.425l.756 2.592a.625.625 0 0 1-.424.775l-2.592.757a.6.6 0 0 1-.176.025m.019-2.793.406 1.392 1.392-.406-.406-1.392zM15 10.521a4.5 4.5 0 1 0 0 9 4.5 4.5 0 0 0 0-9m2.5 5.125h-1.875v1.875a.625.625 0 1 1-1.25 0v-1.875H12.5a.625.625 0 1 1 0-1.25h1.875v-1.875a.625.625 0 1 1 1.25 0v1.875H17.5a.625.625 0 1 1 0 1.25"/></svg>`;
}
