/**
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
/* Generated by `yarn generate:workflow-icons` from icon-source/workflow/. Do not edit by hand. */

/**
 * The Refresh workflow icon as a framework-agnostic SVG string. Usable via `innerHTML`,
 * React `dangerouslySetInnerHTML`, Vue `v-html`, or Lit `unsafeSVG`. Color follows
 * `var(--swc-icon-color, currentColor)`.
 */
export function Icon_Refresh(): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path fill="var(--swc-icon-color, currentColor)" d="M18.207 3.897a.75.75 0 0 0-.906.554l-.38 1.575A7.97 7.97 0 0 0 10 2.02 7.98 7.98 0 0 0 2.24 8.1a.75.75 0 1 0 1.457.36A6.48 6.48 0 0 1 10 3.52a6.47 6.47 0 0 1 5.809 3.633l-2.102-.508a.75.75 0 0 0-.353 1.459l3.245.784a.75.75 0 0 0 .612.12c.048-.011.086-.04.13-.06.069-.019.142-.02.205-.058a.75.75 0 0 0 .338-.464l.875-3.624a.75.75 0 0 0-.552-.906m-.997 7.136a.755.755 0 0 0-.907.55A6.48 6.48 0 0 1 10 16.521a6.47 6.47 0 0 1-5.81-3.634l2.103.508a.75.75 0 0 0 .353-1.459l-3.255-.786a.74.74 0 0 0-.602-.119c-.015.004-.026.015-.04.02a.73.73 0 0 0-.633.563l-.875 3.624a.75.75 0 0 0 1.458.352l.38-1.575A7.97 7.97 0 0 0 10 18.021a7.98 7.98 0 0 0 7.76-6.08.75.75 0 0 0-.549-.909"/></svg>`;
}
