/**
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
/* Generated by `yarn generate:workflow-icons` from icon-source/workflow/. Do not edit by hand. */

/**
 * The Ribbon workflow icon as a framework-agnostic SVG string. Usable via `innerHTML`,
 * React `dangerouslySetInnerHTML`, Vue `v-html`, or Lit `unsafeSVG`. Color follows
 * `var(--swc-icon-color, currentColor)`.
 */
export function Icon_Ribbon(): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path fill="var(--swc-icon-color, currentColor)" d="m16.345 16.38-1.928-4.456a6.23 6.23 0 0 0 1.833-4.418c0-3.446-2.804-6.25-6.25-6.25S3.75 4.06 3.75 7.506a6.23 6.23 0 0 0 1.833 4.418l-1.928 4.455a.75.75 0 0 0 .073.727.76.76 0 0 0 .657.32l1.858-.103L7.44 18.75a.75.75 0 0 0 1.268-.198L10 15.41l1.292 3.142a.75.75 0 0 0 1.268.198l1.197-1.426 1.858.103a.75.75 0 0 0 .73-1.047M5.25 7.505c0-2.619 2.13-4.75 4.75-4.75s4.75 2.131 4.75 4.75-2.13 4.75-4.75 4.75-4.75-2.13-4.75-4.75m2.542 9.329-.642-.764a.76.76 0 0 0-.616-.266l-1.02.056 1.294-2.99a6.2 6.2 0 0 0 2.28.811zm5.674-1.03a.75.75 0 0 0-.616.266l-.641.764-1.297-3.153a6.2 6.2 0 0 0 2.28-.812l1.294 2.991z"/></svg>`;
}
