/**
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
/* Generated by `yarn generate:workflow-icons` from icon-source/workflow/. Do not edit by hand. */

/**
 * The Ruler workflow icon as a framework-agnostic SVG string. Usable via `innerHTML`,
 * React `dangerouslySetInnerHTML`, Vue `v-html`, or Lit `unsafeSVG`. Color follows
 * `var(--swc-icon-color, currentColor)`.
 */
export function Icon_Ruler(): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path fill="var(--swc-icon-color, currentColor)" d="M18.09 4.026 15.975 1.91c-.85-.85-2.334-.85-3.182 0L1.91 12.798a2.253 2.253 0 0 0 0 3.182l2.117 2.118c.425.424.99.659 1.591.659s1.166-.235 1.591-.66L18.092 7.209a2.253 2.253 0 0 0-.001-3.182m-1.06 2.121L6.149 17.037a.77.77 0 0 1-1.06 0L2.97 14.92a.75.75 0 0 1 0-1.062l1.01-1.01 1.764 1.764a.75.75 0 0 0 1.06 0 .75.75 0 0 0 0-1.06L5.04 11.787l1.541-1.541 1.058 1.058a.75.75 0 0 0 1.06 0 .75.75 0 0 0 0-1.06l-1.058-1.06 1.54-1.54 1.767 1.766a.75.75 0 0 0 1.06 0 .75.75 0 0 0 0-1.06l-1.766-1.767 1.54-1.541 1.06 1.06a.75.75 0 0 0 1.06 0 .75.75 0 0 0 0-1.061l-1.06-1.06 1.01-1.011a.746.746 0 0 1 1.06 0l2.118 2.117a.75.75 0 0 1 0 1.06"/></svg>`;
}
