/**
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
/* Generated by `yarn generate:workflow-icons` from icon-source/workflow/. Do not edit by hand. */

/**
 * The SelectNone workflow icon as a framework-agnostic SVG string. Usable via `innerHTML`,
 * React `dangerouslySetInnerHTML`, Vue `v-html`, or Lit `unsafeSVG`. Color follows
 * `var(--swc-icon-color, currentColor)`.
 */
export function Icon_SelectNone(): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path fill="var(--swc-icon-color, currentColor)" d="M12.75 3.5H11.5a.75.75 0 0 1 0-1.5h1.25a.75.75 0 0 1 0 1.5m0 14.5H11.5a.75.75 0 0 1 0-1.5h1.25a.75.75 0 0 1 0 1.5M8.5 3.5H7.25a.75.75 0 0 1 0-1.5H8.5a.75.75 0 0 1 0 1.5m0 14.5H7.25a.75.75 0 0 1 0-1.5H8.5a.75.75 0 0 1 0 1.5m8.75-13a.75.75 0 0 1-.75-.75.75.75 0 0 0-.75-.75.75.75 0 0 1 0-1.5C16.99 2 18 3.01 18 4.25a.75.75 0 0 1-.75.75m0 4.25a.75.75 0 0 1-.75-.75V7.25a.75.75 0 0 1 1.5 0V8.5a.75.75 0 0 1-.75.75m-14.5 0A.75.75 0 0 1 2 8.5V7.25a.75.75 0 0 1 1.5 0V8.5a.75.75 0 0 1-.75.75m0 4.25a.75.75 0 0 1-.75-.75V11.5a.75.75 0 0 1 1.5 0v1.25a.75.75 0 0 1-.75.75m14.5 0a.75.75 0 0 1-.75-.75V11.5a.75.75 0 0 1 1.5 0v1.25a.75.75 0 0 1-.75.75m-13 4.5C3.01 18 2 16.99 2 15.75a.75.75 0 0 1 1.5 0c0 .413.337.75.75.75a.75.75 0 0 1 0 1.5m11.5 0a.75.75 0 0 1 0-1.5c.413 0 .75-.337.75-.75a.75.75 0 0 1 1.5 0c0 1.24-1.01 2.25-2.25 2.25m-13-13A.75.75 0 0 1 2 4.25C2 3.01 3.01 2 4.25 2a.75.75 0 0 1 0 1.5.75.75 0 0 0-.75.75.75.75 0 0 1-.75.75m8.31 5 1.72-1.72a.75.75 0 1 0-1.06-1.06L10 8.94 8.28 7.22a.75.75 0 1 0-1.06 1.06L8.94 10l-1.72 1.72a.75.75 0 1 0 1.06 1.06L10 11.06l1.72 1.72a.747.747 0 0 0 1.06 0 .75.75 0 0 0 0-1.06z"/></svg>`;
}
