/**
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
/* Generated by `yarn generate:workflow-icons` from icon-source/workflow/. Do not edit by hand. */

/**
 * The Select workflow icon as a framework-agnostic SVG string. Usable via `innerHTML`,
 * React `dangerouslySetInnerHTML`, Vue `v-html`, or Lit `unsafeSVG`. Color follows
 * `var(--swc-icon-color, currentColor)`.
 */
export function Icon_Select(): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path fill="var(--swc-icon-color, currentColor)" d="M6.281 18.547c-.292 0-.589-.058-.876-.177a2.22 2.22 0 0 1-1.387-2.078l-.004-12.47c0-.928.532-1.725 1.39-2.08a2.22 2.22 0 0 1 2.452.489l8.892 8.914c.655.655.84 1.594.486 2.45a2.22 2.22 0 0 1-2.079 1.387h-4.078c-.197 0-.39.08-.53.22l-2.691 2.683a2.22 2.22 0 0 1-1.575.662M6.277 3.068a.8.8 0 0 0-.3.06.735.735 0 0 0-.463.693l.004 12.471c0 .465.354.648.462.692a.73.73 0 0 0 .817-.162l2.691-2.682c.426-.424.99-.658 1.589-.658h4.078c.465 0 .648-.354.693-.462s.166-.488-.161-.816L6.795 3.29a.7.7 0 0 0-.518-.222"/></svg>`;
}
