/**
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
/* Generated by `yarn generate:workflow-icons` from icon-source/workflow/. Do not edit by hand. */

/**
 * The Share workflow icon as a framework-agnostic SVG string. Usable via `innerHTML`,
 * React `dangerouslySetInnerHTML`, Vue `v-html`, or Lit `unsafeSVG`. Color follows
 * `var(--swc-icon-color, currentColor)`.
 */
export function Icon_Share(): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path fill="var(--swc-icon-color, currentColor)" d="m13.527 5.49-3.002-2.997a.75.75 0 0 0-1.06 0L6.467 5.491a.75.75 0 1 0 1.06 1.06L9.25 4.83v8.181a.75.75 0 0 0 1.5 0V4.837l1.718 1.715a.75.75 0 1 0 1.06-1.062"/><path fill="var(--swc-icon-color, currentColor)" d="M15.75 18.021H4.25c-1.24 0-2.25-1.01-2.25-2.25v-5.75a.75.75 0 0 1 1.5 0v5.75c0 .414.336.75.75.75h11.5a.75.75 0 0 0 .75-.75v-5.75a.75.75 0 0 1 1.5 0v5.75c0 1.24-1.01 2.25-2.25 2.25"/></svg>`;
}
