/**
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
/* Generated by `yarn generate:workflow-icons` from icon-source/workflow/. Do not edit by hand. */

/**
 * The ShoppingCart workflow icon as a framework-agnostic SVG string. Usable via `innerHTML`,
 * React `dangerouslySetInnerHTML`, Vue `v-html`, or Lit `unsafeSVG`. Color follows
 * `var(--swc-icon-color, currentColor)`.
 */
export function Icon_ShoppingCart(): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path fill="var(--swc-icon-color, currentColor)" d="M17.18 4.809A2.24 2.24 0 0 0 15.453 4H5.087l-.141-.861a2.24 2.24 0 0 0-2.22-1.889H1a.75.75 0 0 0 0 1.5h1.724c.37 0 .68.265.74.63l1.59 9.731A2.24 2.24 0 0 0 7.275 15H16a.75.75 0 0 0 0-1.5H7.275a.75.75 0 0 1-.74-.63L6.23 11h8.768a2.25 2.25 0 0 0 2.214-1.848l.455-2.5a2.24 2.24 0 0 0-.487-1.843m-.989 1.576-.455 2.499a.75.75 0 0 1-.738.616H5.985l-.653-4h10.12c.306 0 .493.169.577.27s.217.314.162.615m-1.19 12.865a1.25 1.25 0 1 1 0-2.5 1.25 1.25 0 0 1 0 2.5m-8 0a1.25 1.25 0 1 1 0-2.5 1.25 1.25 0 0 1 0 2.5"/></svg>`;
}
