/**
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
/* Generated by `yarn generate:workflow-icons` from icon-source/workflow/. Do not edit by hand. */

/**
 * The Slideshow workflow icon as a framework-agnostic SVG string. Usable via `innerHTML`,
 * React `dangerouslySetInnerHTML`, Vue `v-html`, or Lit `unsafeSVG`. Color follows
 * `var(--swc-icon-color, currentColor)`.
 */
export function Icon_Slideshow(): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path fill="var(--swc-icon-color, currentColor)" d="M13.75 16h-7.5C5.01 16 4 14.99 4 13.75v-7.5C4 5.01 5.01 4 6.25 4h7.5C14.99 4 16 5.01 16 6.25v7.5c0 1.24-1.01 2.25-2.25 2.25M6.25 5.5a.75.75 0 0 0-.75.75v7.5c0 .413.336.75.75.75h7.5a.75.75 0 0 0 .75-.75v-7.5a.75.75 0 0 0-.75-.75zm-4.5 9.25A.75.75 0 0 1 1 14V6a.75.75 0 0 1 1.5 0v8a.75.75 0 0 1-.75.75m16.5 0a.75.75 0 0 1-.75-.75V6A.75.75 0 0 1 19 6v8a.75.75 0 0 1-.75.75"/><path fill="var(--swc-icon-color, currentColor)" d="M12.196 9.414 9.018 7.706A.69.69 0 0 0 8 8.315v3.416a.69.69 0 0 0 1.018.609l3.178-1.708a.69.69 0 0 0 0-1.218"/></svg>`;
}
