/**
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
/* Generated by `yarn generate:workflow-icons` from icon-source/workflow/. Do not edit by hand. */

/**
 * The Star workflow icon as a framework-agnostic SVG string. Usable via `innerHTML`,
 * React `dangerouslySetInnerHTML`, Vue `v-html`, or Lit `unsafeSVG`. Color follows
 * `var(--swc-icon-color, currentColor)`.
 */
export function Icon_Star(): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path fill="var(--swc-icon-color, currentColor)" d="M5.506 18.63c-.36 0-.719-.112-1.027-.337a1.74 1.74 0 0 1-.66-1.876l.977-3.577a.75.75 0 0 0-.254-.783l-2.893-2.32a1.74 1.74 0 0 1-.57-1.906 1.74 1.74 0 0 1 1.582-1.206l3.703-.176a.75.75 0 0 0 .665-.483l1.313-3.469c.26-.687.902-1.131 1.637-1.131s1.376.444 1.636 1.13v.001l1.31 3.468c.107.28.369.47.667.484l3.704.176a1.74 1.74 0 0 1 1.582 1.207 1.74 1.74 0 0 1-.57 1.906l-2.894 2.32a.75.75 0 0 0-.254.782l.977 3.574a1.74 1.74 0 0 1-.662 1.879 1.735 1.735 0 0 1-1.994.041l-3.07-2.036a.75.75 0 0 0-.827-.002l-3.117 2.045c-.295.193-.628.29-.961.29M9.979 2.866a.235.235 0 0 0-.235.162L8.433 6.496a2.25 2.25 0 0 1-1.998 1.451l-3.704.176a.234.234 0 0 0-.225.172.235.235 0 0 0 .08.273l2.893 2.319a2.25 2.25 0 0 1 .764 2.349l-.977 3.576a.23.23 0 0 0 .094.268.235.235 0 0 0 .285.007l3.117-2.045a2.25 2.25 0 0 1 2.476.005l3.072 2.037c.12.08.221.04.285-.006a.23.23 0 0 0 .094-.268l-.976-3.575a2.25 2.25 0 0 1 .764-2.348l2.893-2.32a.23.23 0 0 0 .081-.272.234.234 0 0 0-.225-.172l-3.705-.176a2.25 2.25 0 0 1-1.998-1.45l-1.31-3.47a.235.235 0 0 0-.234-.161"/></svg>`;
}
