/**
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
/* Generated by `yarn generate:workflow-icons` from icon-source/workflow/. Do not edit by hand. */

/**
 * The StrokeDotted workflow icon as a framework-agnostic SVG string. Usable via `innerHTML`,
 * React `dangerouslySetInnerHTML`, Vue `v-html`, or Lit `unsafeSVG`. Color follows
 * `var(--swc-icon-color, currentColor)`.
 */
export function Icon_StrokeDotted(): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" data-name="ICONS" viewBox="0 0 20 20"><path fill="var(--swc-icon-color, currentColor)" d="M18.087 10.875a.875.875 0 1 1 0-1.75.875.875 0 0 1 0 1.75m-3.242 0a.875.875 0 1 1 0-1.75.875.875 0 0 1 0 1.75m-3.243 0a.875.875 0 1 1 0-1.75.875.875 0 0 1 0 1.75m-3.242 0a.875.875 0 1 1 0-1.75.875.875 0 0 1 0 1.75m-6.485 0a.875.875 0 1 1 0-1.75.875.875 0 0 1 0 1.75m3.242 0a.875.875 0 1 1 0-1.75.875.875 0 0 1 0 1.75"/></svg>`;
}
