/**
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
/* Generated by `yarn generate:workflow-icons` from icon-source/workflow/. Do not edit by hand. */

/**
 * The Tag workflow icon as a framework-agnostic SVG string. Usable via `innerHTML`,
 * React `dangerouslySetInnerHTML`, Vue `v-html`, or Lit `unsafeSVG`. Color follows
 * `var(--swc-icon-color, currentColor)`.
 */
export function Icon_Tag(): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" data-name="outline" viewBox="0 0 20 20"><path fill="var(--swc-icon-color, currentColor)" d="M8.136 18.804a2.16 2.16 0 0 0 1.523-.622l7.633-7.467c.45-.44.708-1.053.708-1.682v-4.68A2.356 2.356 0 0 0 15.646 2h-4.779c-.628 0-1.218.244-1.662.687l-7.571 7.548c-.408.403-.634.942-.634 1.515s.226 1.113.637 1.518l4.975 4.914c.42.415.972.622 1.524.622M15.646 3.5c.471 0 .854.383.854.854v4.679a.86.86 0 0 1-.257.61l-7.636 7.47a.67.67 0 0 1-.94.002L2.69 12.2a.627.627 0 0 1 0-.9l7.575-7.552a.86.86 0 0 1 .602-.249z"/><circle cx="14" cy="6" r="1" fill="var(--swc-icon-color, currentColor)"/></svg>`;
}
