/**
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
/* Generated by `yarn generate:workflow-icons` from icon-source/workflow/. Do not edit by hand. */

/**
 * The TagBold workflow icon as a framework-agnostic SVG string. Usable via `innerHTML`,
 * React `dangerouslySetInnerHTML`, Vue `v-html`, or Lit `unsafeSVG`. Color follows
 * `var(--swc-icon-color, currentColor)`.
 */
export function Icon_TagBold(): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" data-name="ICONS" viewBox="0 0 20 20"><path fill="var(--swc-icon-color, currentColor)" d="M15.393 11.822c-.326-1.6-1.439-2.903-2.915-3.576.62-.92.85-2.04.631-3.134C12.75 3.31 11.12 2 9.232 2H5.125C4.504 2 4 2.504 4 3.125v13.75C4 17.496 4.504 18 5.125 18h5.197a5.18 5.18 0 0 0 4.026-1.902 5.12 5.12 0 0 0 1.045-4.276M6.25 4.25h2.982c.818 0 1.52.548 1.67 1.304a1.9 1.9 0 0 1-.403 1.588c-.317.386-.755.608-1.2.608H6.25zm6.355 10.424a2.94 2.94 0 0 1-2.283 1.076H6.25V10h3.928c1.476 0 2.743.954 3.01 2.27a2.84 2.84 0 0 1-.583 2.404"/></svg>`;
}
