/**
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
/* Generated by `yarn generate:workflow-icons` from icon-source/workflow/. Do not edit by hand. */

/**
 * The TextVariableFontSettings workflow icon as a framework-agnostic SVG string. Usable via `innerHTML`,
 * React `dangerouslySetInnerHTML`, Vue `v-html`, or Lit `unsafeSVG`. Color follows
 * `var(--swc-icon-color, currentColor)`.
 */
export function Icon_TextVariableFontSettings(): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path fill="var(--swc-icon-color, currentColor)" d="M18.25 15.271h-7.669c-.34-1.43-1.621-2.5-3.154-2.5s-2.813 1.07-3.154 2.5H1.75a.75.75 0 0 0 0 1.5h2.523c.34 1.43 1.621 2.5 3.154 2.5s2.814-1.07 3.154-2.5h7.669a.75.75 0 0 0 0-1.5m-10.823 2.5c-.965 0-1.75-.785-1.75-1.75s.785-1.75 1.75-1.75 1.75.786 1.75 1.75-.785 1.75-1.75 1.75M7.25 2h-4.5C1.785 2 1 2.785 1 3.75V4a.75.75 0 0 0 1.5 0v-.25a.25.25 0 0 1 .25-.25h1.5v6h-.366a.75.75 0 0 0 0 1.5h2.2a.75.75 0 0 0 0-1.5H5.75v-6h1.5a.25.25 0 0 1 .25.25V4A.75.75 0 0 0 9 4v-.25C9 2.785 8.215 2 7.25 2m9.5 0h-4.5C11.01 2 10 3.01 10 4.25v.25a1 1 0 1 0 2 0v-.25a.25.25 0 0 1 .25-.25h1.017c-.002.03-.017.055-.017.085V9H13a1 1 0 1 0 0 2h3a1 1 0 1 0 0-2h-.25V4.085c0-.03-.015-.055-.017-.085h1.017a.25.25 0 0 1 .25.25v.25a1 1 0 1 0 2 0v-.25C19 3.01 17.99 2 16.75 2"/></svg>`;
}
