/**
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
/* Generated by `yarn generate:workflow-icons` from icon-source/workflow/. Do not edit by hand. */

/**
 * The TextCapsAll workflow icon as a framework-agnostic SVG string. Usable via `innerHTML`,
 * React `dangerouslySetInnerHTML`, Vue `v-html`, or Lit `unsafeSVG`. Color follows
 * `var(--swc-icon-color, currentColor)`.
 */
export function Icon_TextCapsAll(): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path fill="var(--swc-icon-color, currentColor)" d="M7.75 5h-5.5C1.285 5 .5 5.785.5 6.75v.77a.75.75 0 0 0 1.5 0v-.77a.25.25 0 0 1 .25-.25h2v7.967h-.701a.75.75 0 0 0 0 1.5H6.45a.75.75 0 0 0 0-1.5h-.7V6.5h2a.25.25 0 0 1 .25.25v.77a.75.75 0 0 0 1.5 0v-.77C9.5 5.785 8.715 5 7.75 5m10 0h-5.5c-.965 0-1.75.785-1.75 1.75v.77a.75.75 0 0 0 1.5 0v-.77a.25.25 0 0 1 .25-.25h2v7.967h-.701a.75.75 0 0 0 0 1.5h2.901a.75.75 0 0 0 0-1.5h-.7V6.5h2a.25.25 0 0 1 .25.25v.77a.75.75 0 0 0 1.5 0v-.77c0-.965-.785-1.75-1.75-1.75"/></svg>`;
}
