/**
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
/* Generated by `yarn generate:workflow-icons` from icon-source/workflow/. Do not edit by hand. */

/**
 * The TextAdd workflow icon as a framework-agnostic SVG string. Usable via `innerHTML`,
 * React `dangerouslySetInnerHTML`, Vue `v-html`, or Lit `unsafeSVG`. Color follows
 * `var(--swc-icon-color, currentColor)`.
 */
export function Icon_TextAdd(): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path fill="var(--swc-icon-color, currentColor)" d="M15 10.5a4.5 4.5 0 1 0 0 9 4.5 4.5 0 0 0 0-9m2.5 5.125h-1.875V17.5a.626.626 0 0 1-1.25 0v-1.875H12.5a.626.626 0 0 1 0-1.25h1.875V12.5a.626.626 0 0 1 1.25 0v1.875H17.5a.626.626 0 0 1 0 1.25"/><path fill="var(--swc-icon-color, currentColor)" d="M12.59 1.998H3.41c-1.24 0-2.25 1.01-2.25 2.25v1.11a.75.75 0 0 0 1.5 0v-1.11c0-.413.337-.75.75-.75h3.84v13h-1.5a.75.75 0 0 0 0 1.5h3.13a.75.75 0 0 0 0-1.5h-.13v-13h3.84c.413 0 .75.337.75.75v1.11a.75.75 0 0 0 1.5 0v-1.11c0-1.24-1.01-2.25-2.25-2.25"/></svg>`;
}
