/**
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
/* Generated by `yarn generate:workflow-icons` from icon-source/workflow/. Do not edit by hand. */

/**
 * The TextIncrease workflow icon as a framework-agnostic SVG string. Usable via `innerHTML`,
 * React `dangerouslySetInnerHTML`, Vue `v-html`, or Lit `unsafeSVG`. Color follows
 * `var(--swc-icon-color, currentColor)`.
 */
export function Icon_TextIncrease(): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path fill="var(--swc-icon-color, currentColor)" d="M12.59 1.998H3.41c-1.24 0-2.25 1.01-2.25 2.25v1.11a.75.75 0 0 0 1.5 0v-1.11c0-.413.337-.75.75-.75h3.84v13h-1.5a.75.75 0 0 0 0 1.5H10a.75.75 0 0 0 0-1.5H8.75v-13h3.84c.413 0 .75.337.75.75v1.11a.75.75 0 0 0 1.5 0v-1.11c0-1.24-1.01-2.25-2.25-2.25M18.75 18.5a.75.75 0 0 1-.53-.22l-2.47-2.47-2.47 2.47a.75.75 0 1 1-1.06-1.06l3-3a.75.75 0 0 1 1.06 0l3 3a.75.75 0 0 1-.53 1.28"/></svg>`;
}
