/**
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
/* Generated by `yarn generate:workflow-icons` from icon-source/workflow/. Do not edit by hand. */

/**
 * The TransformWarp workflow icon as a framework-agnostic SVG string. Usable via `innerHTML`,
 * React `dangerouslySetInnerHTML`, Vue `v-html`, or Lit `unsafeSVG`. Color follows
 * `var(--swc-icon-color, currentColor)`.
 */
export function Icon_TransformWarp(): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path fill="var(--swc-icon-color, currentColor)" d="M18.95 5.938a2.127 2.127 0 0 0-2.125-2.125c-.376 0-.725.106-1.032.279-1.318-.94-3.366-2.03-5.793-2.03-2.433 0-4.5 1.095-5.832 2.035a2.1 2.1 0 0 0-1.043-.285A2.127 2.127 0 0 0 1 5.938c0 1.053.773 1.924 1.78 2.09l1.207 6.002a2.12 2.12 0 0 0-.999 1.795c0 1.172.953 2.125 2.125 2.125s2.125-.953 2.125-2.125c0-.106-.016-.209-.031-.311.865-.404 1.887-.764 2.793-.764.93 0 1.924.36 2.738.748a2 2 0 0 0-.033.327c0 1.172.953 2.125 2.125 2.125s2.125-.953 2.125-2.125c0-.664-.313-1.251-.792-1.641l1.064-6.162a2.126 2.126 0 0 0 1.723-2.084m-1.25 0a.876.876 0 0 1-1.75 0 .876.876 0 0 1 1.75 0m-15.45 0a.876.876 0 0 1 1.75 0 .876.876 0 0 1-1.75 0M5.113 16.7a.876.876 0 0 1 0-1.75.876.876 0 0 1 0 1.75m1.353-2.5a2.1 2.1 0 0 0-1.008-.465L4.25 7.733a2.12 2.12 0 0 0 .999-1.795c0-.237-.048-.46-.12-.673C6.284 4.467 8.019 3.563 10 3.563c1.972 0 3.685.896 4.823 1.69a2.1 2.1 0 0 0-.123.685 2.12 2.12 0 0 0 1.05 1.822l-1.028 5.951c-.468.024-.892.2-1.233.479-.988-.477-2.26-.94-3.489-.94-1.24 0-2.53.47-3.534.95m8.364 2.5a.876.876 0 0 1 0-1.75.876.876 0 0 1 0 1.75"/></svg>`;
}
