/**
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
/* Generated by `yarn generate:workflow-icons` from icon-source/workflow/. Do not edit by hand. */

/**
 * The TransformPerspective workflow icon as a framework-agnostic SVG string. Usable via `innerHTML`,
 * React `dangerouslySetInnerHTML`, Vue `v-html`, or Lit `unsafeSVG`. Color follows
 * `var(--swc-icon-color, currentColor)`.
 */
export function Icon_TransformPerspective(): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path fill="var(--swc-icon-color, currentColor)" d="M17 11.269V8.73a2.12 2.12 0 0 0 1.375-1.981 2.124 2.124 0 0 0-3.882-1.193L5.848 3.482A2.12 2.12 0 0 0 3.75 1.625 2.127 2.127 0 0 0 1.625 3.75c0 .907.574 1.677 1.375 1.981v8.538a2.12 2.12 0 0 0-1.375 1.981c0 1.172.953 2.125 2.125 2.125a2.12 2.12 0 0 0 2.098-1.857l8.645-2.075a2.123 2.123 0 0 0 3.882-1.193c0-.907-.574-1.677-1.375-1.981m-2.848 1.714-8.645 2.074A2.13 2.13 0 0 0 4.5 14.27V5.73a2.13 2.13 0 0 0 1.007-.788l8.645 2.074c.1.789.628 1.44 1.348 1.714v2.538a2.12 2.12 0 0 0-1.348 1.714m2.098-7.108a.876.876 0 0 1 0 1.75.876.876 0 0 1 0-1.75m-12.5-3a.876.876 0 0 1 0 1.75.876.876 0 0 1 0-1.75m0 14.25a.876.876 0 0 1 0-1.75.876.876 0 0 1 0 1.75m12.5-3a.876.876 0 0 1 0-1.75.876.876 0 0 1 0 1.75"/></svg>`;
}
