/**
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
/* Generated by `yarn generate:workflow-icons` from icon-source/workflow/. Do not edit by hand. */

/**
 * The TransformGeneric workflow icon as a framework-agnostic SVG string. Usable via `innerHTML`,
 * React `dangerouslySetInnerHTML`, Vue `v-html`, or Lit `unsafeSVG`. Color follows
 * `var(--swc-icon-color, currentColor)`.
 */
export function Icon_TransformGeneric(): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path fill="var(--swc-icon-color, currentColor)" d="M18.375 10c0-.907-.574-1.677-1.375-1.981V5.73a2.12 2.12 0 0 0 1.375-1.981 2.127 2.127 0 0 0-2.125-2.125c-.907 0-1.677.574-1.982 1.375h-2.286c-.305-.801-1.075-1.375-1.982-1.375S8.323 2.199 8.018 3H5.732A2.12 2.12 0 0 0 3.75 1.625 2.127 2.127 0 0 0 1.625 3.75c0 .907.574 1.677 1.375 1.981V8.02c-.801.303-1.375 1.073-1.375 1.98S2.199 11.677 3 11.981v2.288a2.12 2.12 0 0 0-1.375 1.981c0 1.172.953 2.125 2.125 2.125.907 0 1.677-.574 1.981-1.375h2.287c.305.801 1.075 1.375 1.982 1.375s1.677-.574 1.982-1.375h2.286a2.12 2.12 0 0 0 1.982 1.375 2.127 2.127 0 0 0 2.125-2.125c0-.907-.574-1.677-1.375-1.981V11.98A2.12 2.12 0 0 0 18.375 10m-4.107 5.5h-2.286c-.305-.801-1.075-1.375-1.982-1.375s-1.677.574-1.982 1.375H5.732A2.13 2.13 0 0 0 4.5 14.269V11.98c.801-.304 1.375-1.074 1.375-1.981S5.301 8.323 4.5 8.019V5.73A2.13 2.13 0 0 0 5.731 4.5h2.287c.305.801 1.075 1.375 1.982 1.375s1.677-.574 1.982-1.375h2.286A2.13 2.13 0 0 0 15.5 5.731V8.02c-.801.304-1.375 1.074-1.375 1.981s.574 1.677 1.375 1.981v2.288a2.13 2.13 0 0 0-1.232 1.231m1.982-4.625a.876.876 0 0 1 0-1.75.876.876 0 0 1 0 1.75m0-8a.876.876 0 0 1 0 1.75.876.876 0 0 1 0-1.75m-6.25 0a.876.876 0 0 1 0 1.75.876.876 0 0 1 0-1.75m-6.25 0a.876.876 0 0 1 0 1.75.876.876 0 0 1 0-1.75m0 6.25a.876.876 0 0 1 0 1.75.876.876 0 0 1 0-1.75m0 8a.876.876 0 0 1 0-1.75.876.876 0 0 1 0 1.75m6.25 0a.876.876 0 0 1 0-1.75.876.876 0 0 1 0 1.75m6.25 0a.876.876 0 0 1 0-1.75.876.876 0 0 1 0 1.75"/></svg>`;
}
