/**
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
/* Generated by `yarn generate:workflow-icons` from icon-source/workflow/. Do not edit by hand. */

/**
 * The UnLink workflow icon as a framework-agnostic SVG string. Usable via `innerHTML`,
 * React `dangerouslySetInnerHTML`, Vue `v-html`, or Lit `unsafeSVG`. Color follows
 * `var(--swc-icon-color, currentColor)`.
 */
export function Icon_UnLink(): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path fill="var(--swc-icon-color, currentColor)" d="M13.5 17.771a.75.75 0 0 1-.716-.527l-.821-2.642a.749.749 0 1 1 1.432-.446l.82 2.643a.75.75 0 0 1-.715.972m3.5-3.5a.7.7 0 0 1-.224-.034l-2.657-.829a.75.75 0 1 1 .447-1.431l2.658.829A.75.75 0 0 1 17 14.27M7.316 6.405a.75.75 0 0 1-.716-.528l-.817-2.634A.75.75 0 0 1 7.217 2.8l.816 2.634a.75.75 0 0 1-.717.971M5.64 8.09a.7.7 0 0 1-.223-.033l-2.64-.82a.749.749 0 1 1 .446-1.431l2.64.819a.749.749 0 0 1-.223 1.466M5.313 18.77a4.05 4.05 0 0 1-2.873-1.19 4.07 4.07 0 0 1 0-5.747l1.927-1.927a.75.75 0 1 1 1.06 1.06l-1.926 1.928c-1 1-1 2.626 0 3.626a2.57 2.57 0 0 0 3.626 0l1.952-1.954a.75.75 0 1 1 1.06 1.06L8.188 17.58a4.06 4.06 0 0 1-2.875 1.189m9.787-8.413a.75.75 0 0 1-.53-1.28l1.928-1.928c1-1 1-2.627.001-3.626-.969-.968-2.657-.968-3.626 0l-1.952 1.953a.75.75 0 1 1-1.06-1.06l1.951-1.953a4.04 4.04 0 0 1 2.875-1.192 4.04 4.04 0 0 1 2.873 1.192 4.07 4.07 0 0 1 0 5.746l-1.93 1.929a.75.75 0 0 1-.53.22"/></svg>`;
}
