/**
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
/* Generated by `yarn generate:workflow-icons` from icon-source/workflow/. Do not edit by hand. */

/**
 * The UploadToCloud workflow icon as a framework-agnostic SVG string. Usable via `innerHTML`,
 * React `dangerouslySetInnerHTML`, Vue `v-html`, or Lit `unsafeSVG`. Color follows
 * `var(--swc-icon-color, currentColor)`.
 */
export function Icon_UploadToCloud(): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path fill="var(--swc-icon-color, currentColor)" d="M19.739 11.668c0 1.158-.45 2.246-1.27 3.063S16.564 16 15.407 16h-.657a.75.75 0 0 1 0-1.5h.657a2.8 2.8 0 0 0 2.003-.83 2.8 2.8 0 0 0 .83-2.002c0-.728-.277-1.418-.78-1.942a2.83 2.83 0 0 0-1.902-.872.75.75 0 0 1-.625-1.095q.19-.364.287-.739.103-.392.103-.791c0-.894-.347-1.734-.979-2.366-1.208-1.207-3.296-1.274-4.568-.14-.6.536-.99 1.272-1.094 2.072a.75.75 0 0 1-1.055.586 2.55 2.55 0 0 0-2.865.487 2.4 2.4 0 0 0-.682 2.226c.034.158.086.316.152.466a.75.75 0 0 1-.637 1.053 1.96 1.96 0 0 0-1.298.606 1.94 1.94 0 0 0 .042 2.71 1.94 1.94 0 0 0 1.38.571h2.1a.75.75 0 0 1 0 1.5h-2.1a3.43 3.43 0 0 1-2.44-1.01 3.43 3.43 0 0 1-1.012-2.442c0-.882.335-1.72.942-2.361.387-.408.86-.71 1.382-.89a3.89 3.89 0 0 1 1.124-3.503A4.05 4.05 0 0 1 7.39 4.731a4.86 4.86 0 0 1 1.387-2.127 4.8 4.8 0 0 1 3.202-1.22c1.293 0 2.51.504 3.425 1.419a4.82 4.82 0 0 1 1.418 3.426 4.6 4.6 0 0 1-.187 1.297 4.33 4.33 0 0 1 3.104 4.142"/><path fill="var(--swc-icon-color, currentColor)" d="M13.854 10.824 10.85 7.826a.75.75 0 0 0-1.06 0l-2.998 2.998a.75.75 0 1 0 1.061 1.06l1.722-1.722v8.184a.75.75 0 0 0 1.5 0V10.17l1.718 1.714a.75.75 0 0 0 1.06-1.061"/></svg>`;
}
