/**
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
/* Generated by `yarn generate:workflow-icons` from icon-source/workflow/. Do not edit by hand. */

/**
 * The UserAvatarCursor workflow icon as a framework-agnostic SVG string. Usable via `innerHTML`,
 * React `dangerouslySetInnerHTML`, Vue `v-html`, or Lit `unsafeSVG`. Color follows
 * `var(--swc-icon-color, currentColor)`.
 */
export function Icon_UserAvatarCursor(): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" data-name="strokes" viewBox="0 0 20 20"><path fill="var(--swc-icon-color, currentColor)" d="M10 1.25c-4.825 0-8.75 3.925-8.75 8.75s3.925 8.75 8.75 8.75q.504-.001.991-.056a.75.75 0 0 0 .662-.828.755.755 0 0 0-.828-.662 7.2 7.2 0 0 1-5.598-1.76c1.07-1.188 3.269-1.907 5.4-1.739a.75.75 0 0 0 .122-1.494c-2.534-.204-5.125.655-6.538 2.136A7.2 7.2 0 0 1 2.75 10c0-3.998 3.252-7.25 7.25-7.25s7.25 3.252 7.25 7.25c0 .372-.028.746-.085 1.112a.75.75 0 0 0 1.482.229A9 9 0 0 0 18.75 10c0-4.825-3.925-8.75-8.75-8.75"/><path fill="var(--swc-icon-color, currentColor)" d="M10.054 11c-.02 0-.018-.016-.062-.001-.59 0-1.166-.168-1.665-.485A3.3 3.3 0 0 1 7.17 9.248a3.7 3.7 0 0 1-.418-1.758 3.44 3.44 0 0 1 1.571-2.946 3.12 3.12 0 0 1 3.342-.005c.491.318.89.753 1.163 1.26.282.52.429 1.112.423 1.71a3.7 3.7 0 0 1-.419 1.747 3.4 3.4 0 0 1-1.158 1.27 3 3 0 0 1-1.62.474m-.044-1.501h.01c.306-.004.591-.074.842-.235.268-.173.49-.416.639-.702.169-.324.255-.686.249-1.048a2.03 2.03 0 0 0-.243-1.002 1.94 1.94 0 0 0-.653-.711 1.61 1.61 0 0 0-1.72.004c-.564.369-.897 1-.883 1.682-.006.387.08.746.247 1.066.148.284.368.524.637.696.256.163.552.25.858.25zm4.248 8.862A1.254 1.254 0 0 1 13 17.104v-4.37c0-.51.304-.964.774-1.16a1.25 1.25 0 0 1 1.37.27l2.986 2.978c.364.365.47.911.27 1.395a1.255 1.255 0 0 1-1.158.783h-1.114l-.979.988a1.25 1.25 0 0 1-.891.373m.242-5.04v3.192l.665-.672q.338-.34.893-.341h.628z"/></svg>`;
}
