/**
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
/* Generated by `yarn generate:workflow-icons` from icon-source/workflow/. Do not edit by hand. */

/**
 * The VolumeOff workflow icon as a framework-agnostic SVG string. Usable via `innerHTML`,
 * React `dangerouslySetInnerHTML`, Vue `v-html`, or Lit `unsafeSVG`. Color follows
 * `var(--swc-icon-color, currentColor)`.
 */
export function Icon_VolumeOff(): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path fill="var(--swc-icon-color, currentColor)" d="M18.78 17.74 2.28 1.24A.75.75 0 1 0 1.22 2.3l2.72 2.72h-.69A2.255 2.255 0 0 0 1 7.271v5.5c0 1.24 1.01 2.25 2.25 2.25h1.629a.75.75 0 0 1 .53.22l2.604 2.604a1.745 1.745 0 0 0 1.906.379A1.74 1.74 0 0 0 11 16.606V12.08l6.72 6.72a.747.747 0 0 0 1.06 0 .75.75 0 0 0 0-1.06M9.5 16.605a.24.24 0 0 1-.154.232.24.24 0 0 1-.273-.054L6.47 14.18a2.23 2.23 0 0 0-1.591-.658H3.25a.75.75 0 0 1-.75-.75v-5.5a.75.75 0 0 1 .75-.75h2.191L9.5 10.58zM8.259 4.073l.814-.814a.24.24 0 0 1 .273-.055c.07.03.154.093.154.232v2.59a.75.75 0 0 0 1.5 0v-2.59a1.748 1.748 0 0 0-2.987-1.237l-.815.814a.75.75 0 1 0 1.06 1.06m4.965 5.752a.75.75 0 1 0 1.492-.154c-.1-.963-.573-1.794-1.299-2.277a.75.75 0 0 0-.832 1.248c.348.231.586.673.639 1.183m4.027.193c0 .866-.284 1.686-.8 2.31a.752.752 0 0 0 .577 1.228.75.75 0 0 0 .578-.272c.739-.892 1.145-2.053 1.145-3.266 0-1.686-.798-3.266-2.083-4.124a.751.751 0 0 0-.834 1.248c.874.583 1.417 1.685 1.417 2.876"/></svg>`;
}
