/**
 * Copyright 2026 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
/* Generated by `yarn generate:workflow-icons` from icon-source/workflow/. Do not edit by hand. */

/**
 * The Wallet workflow icon as a framework-agnostic SVG string. Usable via `innerHTML`,
 * React `dangerouslySetInnerHTML`, Vue `v-html`, or Lit `unsafeSVG`. Color follows
 * `var(--swc-icon-color, currentColor)`.
 */
export function Icon_Wallet(): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" data-name="ICONS" viewBox="0 0 20 20"><path fill="var(--swc-icon-color, currentColor)" d="M4.128 6.072a.75.75 0 0 1-.724-.558 2.14 2.14 0 0 1 .22-1.633 2.14 2.14 0 0 1 1.31-1l6.786-1.796a2.15 2.15 0 0 1 2.633 1.531L15 5.064a.749.749 0 1 1-1.45.385L12.904 3a.65.65 0 0 0-.799-.466L5.32 4.331a.656.656 0 0 0-.465.8.748.748 0 0 1-.726.941M18.25 10h-.326a3.756 3.756 0 0 0-3.674-3h-11C2.01 7 1 8.01 1 9.25v6.5C1 16.99 2.01 18 3.25 18h11c1.81 0 3.325-1.29 3.674-3h.326a.75.75 0 0 0 .75-.75v-3.5a.75.75 0 0 0-.75-.75m-.75 3.5h-3v-2h3zm-3.25 3h-11a.75.75 0 0 1-.75-.75v-6.5c0-.413.337-.75.75-.75h11c.976 0 1.801.63 2.112 1.5H13.75a.75.75 0 0 0-.75.75v3.5c0 .414.336.75.75.75h2.612a2.25 2.25 0 0 1-2.112 1.5"/></svg>`;
}
