name: Beta Release

on:
    push:
        branches:
            - main
            - feat/changesets

jobs:
    release:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout PR branch
              uses: actions/checkout@v4

            - name: Setup Job and Install Dependencies
              uses: ./.github/actions/setup-job

            - name: Install semver
              run: npm install -g semver

            - name: Set Git identity
              run: |
                  git config --global user.email "support+actions@github.com"
                  git config --global user.name "github-actions-bot"

            - name: Update package versions for beta release
              run: |
                  yarn changeset pre enter testing
                  # Apply the changeset with specific beta tag
                  yarn changeset version

            - name: Configure NPM for changeset publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
              run: |
                  echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

            - name: Publish beta release
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
              run: |
                  git commit -am "chore: publish beta version"
                  yarn prepublishOnly
                  yarn changeset publish --no-git-tag --tag testing
                  git reset --hard HEAD^
