name: Beta Release

on:
    push:
        branches:
            - main
            - pvashish/update-snapshot-script

jobs:
    release:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout PR branch
              uses: actions/checkout@v4

            - name: Setup Job and Install Dependencies
              uses: ./.github/actions/setup-job

            - name: Set Git identity
              run: |
                  git config --global user.email "support+actions@github.com"
                  git config --global user.name "github-actions-bot"

            - name: Get current package version and latest beta number
              id: version-info
              run: |
                  # Fetch the latest beta version
                  LATEST_BETA=$(npm view @spectrum-web-components/bundle --tag beta version || echo "none")
                  echo "Latest beta: $LATEST_BETA"

                  if [[ $LATEST_BETA == *beta* ]]; then
                    # Extract beta number
                    BETA_NUMBER=$(echo $LATEST_BETA | grep -oP 'beta\.\K\d+')
                    # Increment the beta number
                    NEXT_BETA_NUMBER=$((BETA_NUMBER + 1))
                  else
                    # Start with beta.0 if no beta version exists
                    NEXT_BETA_NUMBER=0
                  fi

                  echo "Next beta number: $NEXT_BETA_NUMBER"
                  echo "next_beta_number=$NEXT_BETA_NUMBER" >> $GITHUB_OUTPUT

            - name: Update package versions for beta release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NEXT_BETA_NUMBER: ${{ steps.version-info.outputs.next_beta_number }}
              run: |
                  yarn changeset pre enter beta.$NEXT_BETA_NUMBER
                  # Apply the changeset with specific beta tag
                  yarn changeset version
                  yarn lint:versions --fix
                  yarn update-version

            - name: Configure NPM for changeset publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
              run: |
                  echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

            - name: Publish beta release
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
              run: |
                  git add .
                  git commit -am "chore: publish beta version"
                  yarn changeset pre exit
                  yarn prepublishOnly
                  yarn changeset publish --no-git-tag --tag beta
                  git reset --hard HEAD^
