name: Beta Release

on:
    push:
        branches:
            - ruben/beta-releases

jobs:
    release:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '20'

            - name: Install dependencies
              run: yarn install --frozen-lockfile

            - name: Set Git identity
              run: |
                  git config --global user.email "rcarvalho@adobe.com"
                  git config --global user.name "Ruben Carvalho"

            - name: Get Lerna current version
              id: get_lerna_version
              run: echo "::set-output name=version::$(npx lerna ls --json | jq -r '.[0].version')"

            - name: Get latest published beta version
              id: get_latest_published_beta
              run: echo "::set-output name=latest_beta_version::$(npm view @spectrum-web-components/button@beta version || echo 'none')"

            - name: Calculate next beta version
              id: calculate_next_beta_version
              run: |
                  LERNA_VERSION="${{ steps.get_lerna_version.outputs.version }}"
                  LATEST_BETA_VERSION="${{ steps.get_latest_published_beta.outputs.latest_beta_version }}"

                  if [ "$LATEST_BETA_VERSION" == "none" ]; then
                      echo "::set-output name=beta_version::$LERNA_VERSION-beta.0"
                  else
                      LATEST_BETA_BASE_VERSION=$(echo "$LATEST_BETA_VERSION" | sed 's/-beta\.[0-9]*//')

                      if [ "$LERNA_VERSION" != "$LATEST_BETA_BASE_VERSION" ]; then
                          echo "::set-output name=beta_version::$LERNA_VERSION-beta.0"
                      else
                          CURRENT_BETA_NUMBER=$(echo "$LATEST_BETA_VERSION" | sed 's/.*beta\.\([0-9]\+\)/\1/')
                          NEXT_BETA_NUMBER=$((CURRENT_BETA_NUMBER + 1))
                          echo "::set-output name=beta_version::$LERNA_VERSION-beta.$NEXT_BETA_NUMBER"
                      fi
                  fi

            - name: Update package versions for beta release
              run: |
                  npx lerna version ${{ steps.calculate_next_beta_version.outputs.beta_version }} --no-git-tag-version --no-push --yes

            - name: Configure NPM for Lerna publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
              run: |
                  echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

            - name: Publish beta release
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
              run: |
                  yarn lerna publish from-package --dist-tag beta
