name: Lint
#
# This workflow lints the library and reports back suggested fixes
#

on:
    push:
        branches:
            - main

    pull_request:
        branches:
            - main

        types:
            - opened
            - synchronize
            - reopened
            - auto_merge_enabled

permissions:
    contents: read
    pull-requests: write

concurrency:
    group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
    cancel-in-progress: true

defaults:
    run:
        shell: bash

jobs:
    # -------------------------------------------------------------
    # Returns all changed pull request files.
    # --------------------------------------------------------------
    changed_files:
        runs-on: ubuntu-latest
        name: Capture changed-files
        outputs:
            styles_added_files: ${{ steps.changed-files.outputs.styles_added_files }}
            styles_modified_files: ${{ steps.changed-files.outputs.styles_modified_files }}
            eslint_added_files: ${{ steps.changed-files.outputs.eslint_added_files }}
            eslint_modified_files: ${{ steps.changed-files.outputs.eslint_modified_files }}
        permissions:
            pull-requests: read

        steps:
            - name: Check out code
              uses: actions/checkout@v4

            - name: Get changed files
              id: changed-files
              uses: step-security/changed-files@v46
              with:
                  files_yaml: |
                      styles:
                        - '*.css'
                        - '**/*.css'
                      eslint:
                        - '*.{js,json,ts}'
                        - '**/*.{js,json,ts}'
                        - '!*.d.ts'
                        - '!**/*.d.ts'

    # --- Lint pre-compiled assets for consistency --- #
    eslint:
        name: Eslint
        runs-on: ubuntu-latest
        needs: [changed_files]
        timeout-minutes: 5
        steps:
            # install but don't build - we're linting pre-compiled assets
            - name: Check out code
              uses: actions/checkout@v4
            - name: Setup Job and Install Dependencies
              uses: ./.github/actions/setup-job
              with:
                  node-version: 20
                  skip-build: true

            - name: Lint styles
              if: ${{ needs.changed_files.outputs.styles_added_files != '' || needs.changed_files.outputs.styles_modified_files != '' }}
              uses: reviewdog/action-stylelint@v1.30.2
              with:
                  fail_level: error
                  filter_mode: diff_context
                  level: error
                  reporter: github-pr-review
                  stylelint_input: '${{ needs.changed_files.outputs.styles_added_files }} ${{ needs.changed_files.outputs.styles_modified_files }}'
                  stylelint_config: '${{ github.workspace }}/.stylelintrc.json'
                  packages: 'stylelint-header stylelint-config-standard'

            - name: ESLint
              uses: reviewdog/action-eslint@v1.33.2
              if: ${{ needs.changed_files.outputs.eslint_added_files != '' || needs.changed_files.outputs.eslint_modified_files != '' }}
              with:
                  fail_level: error
                  level: error
                  reporter: github-pr-review
                  filter_mode: diff_context
                  eslint_flags: '${{ needs.changed_files.outputs.eslint_added_files }} ${{ needs.changed_files.outputs.eslint_modified_files }}'
